### ISSUE TITLE
Password change not possible if GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION enabled. Error: "update requires reauthentication" - not possible to provide Nonce

### ISSUE THREAD

**Issue by tomekit** [supabase/gotrue#1015]
If: `GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION` option is enabled for the GoTrue API it is not possible to change password using `updateUser`, e.g.: 

```
final res = await supabase.auth.updateUser(
                                      UserAttributes(
                                        password: password,
                                      ),
                                    );
```
According to current docs: 
https://github.com/supabase/gotrue#get-reauthenticate
https://github.com/supabase/gotrue#put-user

user will need to reauthenticate first, however it doesn't seem is currently possible to provide `nonce` using Flutter library.

I am using Flutter gotrue v`1.5.7`.

**Comment by kangmingtay** [comment]
Hi everyone, we've added the methods to the supabase-js client library already and have also updated the docs for the following:

* Sending a reauthentication nonce (https://supabase.com/docs/reference/javascript/auth-reauthentication)
* Sending a nonce + password in the update user method (https://supabase.com/docs/reference/javascript/auth-updateuser)
