### ISSUE TITLE
Generate access_tokens via API

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#104]
it would be useful to generate access_token + refresh_token via an admin protected endpoint and return them

similarly (or alternatively?) it would be useful to generate and return a magic link

**Comment by awalias** [comment]
related: https://github.com/supabase/gotrue/issues/65

**Comment by hf** [comment]
Hey,

This is not something we wish to encourage. In the Supabase Dashboard you get full access to the JWT signing secret, and you can mint whatever JWT you want.

Issuing arbitrary refresh tokens is not something that we'll likely support. There are many reasons for this: 
- A "default is secure" position where only basic settings are required for a secure GoTrue deployment.
- Not all developers are created equal -- although having access to the database is a problem, we want to make it more difficult for malicious actors to impersonate users.
- Backward compatibility -- as GoTrue evolves, custom information associated with refresh tokens may not be well supported.

If you really need this though, you are free to modify your database as it suits you.

I'll be closing the issue for now. If you feel very strongly about this and have a valid use case, please re-open an issue.
