### ISSUE TITLE
supabase auth provide with one tap google login

### ISSUE THREAD

**Issue by M-NaveedAshraf-work** [supabase/gotrue#1054]
### Discussed in https://github.com/supabase/supabase/discussions/8035

<div type='discussions-op-text'>

<sup>Originally posted by **M-NaveedAshraf-work** August  3, 2022</sup>
 I'm actually trying to auth my users with supabase with google on tap login provider. it's working fine for a user having one google account register in a browser. but if a user has multiple accounts in a browser then the supabase auth function redirects to google  select an account page. However, the user already selected an account in one tap login iframe.

here I selected a user to login
![InkedWMh18B452VZh](https://user-images.githubusercontent.com/107533241/182521155-8422fd32-8741-4514-8879-54ad24b44d02.jpg)
 
and it redirects me to this page.
![Inked0jja68vxyWQN](https://user-images.githubusercontent.com/107533241/182521393-b98c8104-7470-471a-9b47-c0343b7c48ee.jpg)

</div>

**Comment by J0** [comment]
Hey team,

Thanks for patiently waiting. Wanted to flag that [One Tap Login is now available on Supabase](https://supabase.com/blog/native-mobile-auth)

Going to close this issue now but feel free to revert back if there are still unadressed concerns.

Thanks!
