### ISSUE TITLE
Bug: Github Auth - Unable to exchange external code

### ISSUE THREAD

**Issue by kangmingtay** [supabase/gotrue#106]
# Bug report

## Describe the bug
Using github as an external provider results in an error during the redirect phase after the sign in attempt. 
```
error: server_error
error_description: Unable to exchange external code: 7cf84a55c55bd5f9ac26
```

## Additional context
Seems to work locally, checking prod to see why its failing 
https://github.com/supabase/supabase/discussions/1192

**Comment by ElesGergo** [comment]
I experienced ghe same with facebook as a provider.

**Comment by kangmingtay** [comment]
Hi @ElesGergo, at the moment, I can't seem to reproduce the bug, could you please highlight the steps you took to enable facebook as an auth provider? If it helps, we have a [tutorial](https://www.youtube.com/playlist?list=PL5S4mPUpp4OvE6MLbO1xAMvKLKT1sFsHF) that provides a step-by-step guide on enabling 3rd-party providers on Supabase. Let me know if this helps 👍

**Comment by awalias** [comment]
a lot of people are reporting getting spaces when they copy-paste the github client secret, might be worth checking for anyone experiencing the same

**Comment by awalias** [comment]
also there are backend auth logs inside the Supabase dashboard at Auth > Settings (scroll to the bottom), there should be some additional info there
