### ISSUE TITLE
Signups not allowed for otp with phone 

### ISSUE THREAD

**Issue by kresogalic8** [supabase/gotrue#1063]
Hey guys, 

I am getting the error when I try to use signInWithOtp => **Signups not allowed for otp**, version I am using is 2.8.0

This is the code block that I am using to trigger the function:

```
const { data, error } = await supabase.auth.signInWithOtp({
    phone,
    options: {
      shouldCreateUser: false,
    },
  });
```

Any help with it

**Comment by kangmingtay** [comment]
closing the issue because it seems stale - feel free to reopen if my comment didn't help @kresogalic8

**Comment by ahanusek** [comment]
This issue still exists. I'm creating account via admin auth. Then when I'm trying send otp with this method

```
 const { error } = await supabase.auth.signInWithOtp({
      email: email?.toLowerCase(),
      options: {
        shouldCreateUser: false,
      },
    });
```

API returns  "Signups not allowed for otp", but this user already exists with status "Waiting for verification".

<img width="1330" alt="Zrzut ekranu 2024-01-9 o 20 02 03" src="https://github.com/supabase/gotrue/assets/16654786/6790fd39-66da-47cd-84a9-24255f9ef1be">
