### ISSUE TITLE
Documentation to make authentication with Google incomplete

### ISSUE THREAD

**Issue by ildaneta** [supabase/gotrue#1066]
# Improve documentation

I could bring the user data using a Google auth method following the code bellow:

```tsx
import { StatusBar } from "expo-status-bar";
import { Button, StyleSheet, Text, View } from "react-native";
import * as Google from "expo-auth-session/providers/google";

import "react-native-url-polyfill/auto";
import { createClient } from "@supabase/supabase-js";
import { IAuthResponse } from "./interface";

export default function App() {
  const { SUPABASE_URL } = process.env
  const { SUPABASE_ANON_KEY } = process.env

  const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

  const [req, _res, promptAsync] = Google.useAuthRequest({
    expoClientId: "",
    iosClientId: "",
    androidClientId: "",
  });

  const loginWithGoogle = async () => {
    promptAsync({
      url: `${SUPABASE_URL}/auth/v1/authorize?provider=google&redirect_to=${req?.redirectUri}`,
    })
      .then(async (res: any) => {
        let response: IAuthResponse = res;

        const { user, session, error } = await supabase.auth.signIn({
          refreshToken: response.params.refresh_token,
        });
        console.log("user: ", user, "session: ", session, "error: ", error);
      })
      .catch((error) => console.log("error: ", error));
  };

  return (
    <View style={styles.container}>
      <StatusBar style="auto" />
      <Text style={styles.text}>Supabase login</Text>

      <Button title="Login with Google" onPress={loginWithGoogle} />
    </View>
  );
}

```

But the problem is that this way is with an old version of supabase library: `"@supabase/supabase-js": "1.35.6"`

Could you help me to make the code works with the latest version of `"@supabase/supabase-js": "2.7.0"`?

I tried to use this new version, but inside of data only returned to me: `data:  {"provider": "google", "url": "https://***supabase.co/auth/v1/authorize?provider=google"}
`.

The current documentation it's not clear to me, I have to do more steps? 
Should I use `expo-auth-session`? But how can I built with it?

I followed all the steps described into your documentation:

1 - Create the Google Cloud consent screen  (but this screen even open inside the emulator)
![screencapture-console-cloud-google-apis-credentials-consent-edit-2023-02-04-21_20_34 (1)](https://user-images.githubusercontent.com/21963291/216788210-dd2b8f73-cf9d-4ce3-a227-57bef3840294.png)

2 - Create the credentials
![Screenshot 2023-02-04 at 21 25 22](https://user-images.githubusercontent.com/21963291/216788257-271a3c4e-dc60-4f41-bd4c-afee9e484538.png)

3 - Insert the credentials inside Supabase Google Provider configs:
![Screenshot 2023-02-04 at 21 26 46](https://user-images.githubusercontent.com/21963291/216788311-b917cf89-94ad-4c6d-913e-6eda61d3728e.png)

4 - Add the code

```tsx
import React from "react";
import { View, Text, Button } from "react-native";
import { createClient } from "@supabase/supabase-js";

const Login = (): JSX.Element => {
  const { SUPABASE_URL } = process.env
  const { SUPABASE_ANON_KEY } = process.env

  const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

  async function signInWithGoogle() {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: "google",
    });

    if (data) {
      console.log("data: ", data);
    }

    if (error) {
      console.log("error: ", error);
    }
  }

  async function signout() {
    const { error } = await supabase.auth.signOut();
  }

  return (
    <View>
      <Text style={{ marginVertical: 40, fontSize: 24, alignSelf: "center" }}>
        Login
      </Text>

      <Button title="Signin with Google" onPress={signInWithGoogle} />
    </View>
  );
};

export default Login;
```

Could you help me describing in steps?

I have tried a lot of solutions, included I saw this video of one of supabase's developers

**https://www.youtube.com/watch?v=dE2vtnv83Fc&t=240s**

But it's outdated as well.

I would love utilize this method of authentication.

**Comment by kangmingtay** [comment]
Hi everyone, i'm not too familiar with react native but i'll try my best to answer some questions:

> Should I use expo-auth-session?

I don't think this is necessary if you don't mind being redirected to a web page from the mobile app. 

You will need to open the URL returned by `signInWithOAuth` in the mobile app since i think it doesn't automatically redirect the user to the web browser. 

I'm gonna be closing this issue now but if anyone has any questions or comments about this, feel free to drop them and reopen the issue.

**Comment by caprica** [comment]
@ildaneta I have ended up at the same position as you describe in your original post, did you ever find a solution for this?  I'm really struggling to find a complete example that actually works in Expo.

**Comment by lucksp** [comment]
i also am having a tough time with the Google Auth sign in using Expo/ReactNative.  The main reason being that we need to open a browser in your mobile device to handle the auth, I think, something like this:

```
const signInWithGoogle = async () => {
// first signInWithOAuth to get the URL to visit
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: 'google',
    });
    if (error) {
      setMessage(['error', error.message]);
      return;
    }
// then open a browser in your mobile device
    if (data.url) {
      const result = await openAuthSessionAsync(
        data.url,
        ('sign-in')
      );
// gets stuck here
      console.log(result);
    }
  };
```

What's more concerning is that the supabase client is not getting any update...despite seeing my user show up in the admin dashboard.

```
useEffect(() => {
    async function getSession() {
      console.log('getSession');

      const {
        data: { session },
        error,
      } = await supabase.auth.getSession();
      console.log('getSession', { session });

      if (error) {
        setMessage(['error', error.message]);
      } else {
        setSession(session ?? null);
      }
    }
    try {
      setIsLoading(true);
      getSession();
    } catch (e) {
      setMessage(['error', (e as Error).message]);
    } finally {
      setIsLoading(false);
    }

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange(async (_event, session) => {
      console.log('onAuthStateChange');
      console.log(_event);
      console.log(session);

      setSession(session ?? null);
    });

    return () => {
      subscription?.unsubscribe();
    };
  }, [setMessage]);
```

after success auth from google, redirect fails, tries for localhost: after success auth from google, redirect fails

Why does it try localhost; Is it my linking schema? Or something else?

Is there a way for the expo-web-browser to close automatically after success? I tried adding a Linking.addEventListener, but it also doesn't fire.

**Comment by kangmingtay** [comment]
hi @lucksp,

> Why does it try localhost; Is it my linking schema? Or something else?

The redirect defaults to your site URL if the redirectTo param specified is not in the allow list

In your code, i noticed that you didn't specify a `redirectTo` param in the `signInWithOAuth` method. Can you try specifying a mobile deeplink so that google redirects back to your application after successfully completing the oauth flow?

**Comment by lucksp** [comment]
> In your code, i noticed that you didn't specify a `redirectTo` param in the `signInWithOAuth` method. Can you try specifying a mobile deeplink so that google redirects back to your application after successfully completing the oauth flow?

Thanks @kangmingtay .  I did try some things, but my code snippet wasn't clear.  I have updated the original.

According to my expo `app.config`, my scheme name is `mfi`, so therefore, I would think my 2nd argument should be `mfi://${route}` where `route` is back to the `sign-in` page, so it should be `mfi://sign-in` if I am understanding this correctly.  If so, the completed OAuth flow still gets stuck on localhost...

**Comment by kangmingtay** [comment]
@lucksp have you updated the [allow list for redirect urls](https://app.supabase.com/project/_/auth/url-configuration) in the dashboard to include `mfi://sign-in` ? you can take a look at [this guide](https://supabase.com/docs/guides/auth#redirect-urls-and-wildcards) for configuring the allow list for your redirect URLs

**Comment by lucksp** [comment]
wow, completely missed that in the docs.  let me give it a try 🙏

**Comment by ReactiveFilos** [comment]
> wow, completely missed that in the docs. let me give it a try 🙏

Hi, did you have the opportunity to solve the problem? I'm working on it right now. here's my instagram if you'd like to write me there @filos__
