### ISSUE TITLE
Permissions issue for postgres user on auth table objects (unable to drop triggers)

### ISSUE THREAD

**Issue by jamesallchin** [supabase/gotrue#1067]
# Bug report

## Describe the bug

The supabase examples sometimes take advantage of creating a trigger against the `auth.users` table - so that on sign up (or update of user information) you can also subsequently populate another table (e.g. your own application's `public.profile` table via a function that is called from the trigger). 

To do this, supabase provides a `postgres` db user. In the default setup, the `postgres` user is able to create a trigger on `auth.users`.

## To Reproduce

Connect to your supabase db using the `postgres` user with the connection details provided by supabase console.

Create a function to populate your own `profile` table when a user signs up.

``
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;
``

Works fine.

Now add a trigger to call this function when data is inserted into `auth.users`

``
  create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
``

Works fine.

However, subsequently try and drop the trigger.

``
drop trigger if exists on_auth_user_created on auth.users;
``

This errors with 

``
ERROR:  must be owner of relation users
``

Understandably the internal auth schema is owned by a separate internal account `supabase_auth_admin` but some looks like perhaps the permission to create trigger has been granted to `postgres` user but not drop. 

## Expected behavior

Should be able to drop the trigger after creating it.

**Comment by J0** [comment]
Hey all,

Closing this issue as it seems to have gone stale. Moving forward, we've cut back on references in the docs in terms of adding triggers to the `auth.users` table. Instead, we are now recommending the creation of a profiles table with a foreign key table to auth.users. We'll be looking at a webhook based solution to allow users to react to events (e.g. signup/in). 


Let us know if there are any questions or concerns.
