### ISSUE TITLE
Custom email templates and sending

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/gotrue#109]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm currently using Firebase Authentication which gives me full control over magic link emails. Their admin library simply [generates the email action links](https://firebase.google.com/docs/auth/admin/email-action-links) and I'm responsible for creating and sending the emails:

```typescript
const email = 'johndoe@example.com';
const link = await admin.auth().generateSignInWithEmailLink(email);
await sendMyCustomLoginEmail(link);
```

## Describe the solution you'd like

I want to have an API like Google's ☝️ where I can generate all the email action links using a server-side Node.js library (or simply the GoTrue REST API already provided by Supabase) and then send the emails myself.

## Describe alternatives you've considered

Your [pricing page](https://supabase.io/pricing) specifies that people on any paid plan (i.e. "Pro" or "Enterprise") can remove Supabase branding from the authentication emails.

It also looks like I can customize the email templates send by Supabase in my project's "Authentication" tab:

![image](https://user-images.githubusercontent.com/20798889/119693528-38ac6900-be01-11eb-9202-c8568bbe8771.png)

But, while that ☝️ is really nice (and will probably work for most use-cases), I would like to be able to use whatever email templating library that I want. I already send other transactional emails to my users (e.g. meeting notifications, purchase confirmations) and I want all my emails to look the same. Thus, I want my authentication emails to use the same email templating solution that all my other transactional emails use.

## Additional context

Currently, I [use SendGrid](https://github.com/tutorbookapp/tutorbook/blob/develop/lib/mail/send.ts) to send all my transactional emails that are composed of [React components with inline styling](https://github.com/tutorbookapp/tutorbook/blob/develop/lib/mail/components.tsx) and rendered with [`ReactDOMServer.renderToStaticMarkup`](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup).

For example, for my current login link setup, my front-end simply calls [`POST /api/login`](https://github.com/tutorbookapp/tutorbook/blob/develop/pages/api/login.tsx) with the user's email and location:

```tsx
// pages/api/login.tsx
import LoginEmail from 'lib/mail/login';
import send from 'lib/mail/send';

export default async function login(req: Req, res: Res<void>): Promise<void> {
  const actionCodeSettings = {
    url: `http://${
      req.headers.host || 'tutorbook.org'
    }/confirm?href=${encodeURIComponent(req.body.redirect)}`,
  };
  const link = await auth.generateSignInWithEmailLink(req.body.email, actionCodeSettings)
  if (err) throw new APIError(`${err.name} creating link: ${err.message}`, 500);
  await send({
    to: [{ email: req.body.email }],
    subject: `Tutorbook Login Confirmation (${req.body.location}).`,
    html: renderToStaticMarkup(
      <LoginEmail link={link as string} location={req.body.location} />
    ),
  });
  res.status(200).end();
}
```

And then that [`LoginEmail`](https://github.com/tutorbookapp/tutorbook/blob/develop/lib/mail/login.tsx) template is defined using those reusable React components (that each have inline styling):

```tsx
// lib/mail/login.tsx
import { Button, Email, Footer, Header, Item, P } from 'lib/mail/components';

export interface LoginEmailProps {
  link: string;
  location: string;
}

export default function LoginEmail({
  link,
  location,
}: LoginEmailProps): JSX.Element {
  return (
    <Email>
      <Header />
      <Item left='48px' right='48px'>
        <P style={{ marginTop: '0px !important' }}>Hi there,</P>
        <P>
          We just received a login attempt from {location}. To complete the
          login process, simply click the button below:
        </P>
        <br />
        <Button href={link}>CONFIRM LOGIN</Button>
      </Item>
      <Footer>
        <P style={{ marginBottom: '0px !important' }}>
          If you didn&apos;t attempt to log in but received this email, or if
          the location doesn&apos;t match, please ignore this email. If you are
          concerned about your account&apos;s safety, please reply to this email
          to get in touch with us.
        </P>
      </Footer>
    </Email>
  );
}
```

**Comment by nicholaschiang** [comment]
Also, you guys should update the authentication [docs](https://supabase.io/docs/guides/auth#tips) and [reference](https://supabase.io/docs/reference/javascript/reset-password-email) to make it clear that developers can customize the email templates from their project's "Authentication" tab. I had no idea that I could until I created a new project and opened that tab.

**Comment by kangmingtay** [comment]
Hey @nicholaschiang, thanks for the feedback! We've just made a PR for this issue so stay tuned! :)

**Comment by kangmingtay** [comment]
Gonna close this issue now, we're currently testing it in our staging environment.
