### ISSUE TITLE
Resend endpoint issue (resend email change issue)

### ISSUE THREAD

**Issue by mirland** [supabase/gotrue#1095]
# Bug report

The endpoint /[resend](https://github.com/supabase/gotrue/pull/912/files) is not working properly. When you have a user that was registered by phone, and it's confirmed. Then if you add an email to the user and try to resend the verification email using /resend endpoint, the confirmation email is not sent.

## Describe the bug

1. Register a user with a phone
2. Verify the phone
3. Add email to that user, using the method `updateUser` (the confirmation email is sent)
4. Call the endpoint /resend to resend the confirmation email (the mail is not sent)

Issue: 
To invoke 4, we are calling the `resend` endpoint with two parameters:
```
{
          'email': email,
          'type': 'email_change',
        },
``` 

Then, if I take a look at your code:
```go
	if params.Email != "" {
		user, err = models.FindUserByEmailAndAudience(db, params.Email, aud)
	} else if params.Phone != "" {
		user, err = models.FindUserByPhoneAndAudience(db, params.Phone, aud)
	}

	if err != nil {
		if models.IsNotFoundError(err) {
			return sendJSON(w, http.StatusOK, map[string]string{})
		}
		return internalServerError("Unable to process request").WithInternalError(err)
	}

```
The server finds the user by the email address. However in the DB table, the email address is null, and the email is in `email_change` column. The reason is that the email is not associated with the user because it's not verified.

To fix this issue, in the case that the user has not had a confirmed email, the resend method should accept the phone number as the identifier (the confirmed method).

**Comment by kangmingtay** [comment]
Hi @mirland, thanks for catching this! We just put up a PR for this already so it should be fixed soon.

**Comment by mirland** [comment]
Hi @kangmingtay thanks for the fix. However, I'm testing exactly the same case and it's not working.
I'm invoking the same endpoint with the same data, the server returns 200 but the email is not sent.
Can you help me? 

BTW: I checked and the email is in `email_change` column. 
Also I testing sending the resend with type `email_change` and also with `signup` but it's not working
