### ISSUE TITLE
chore: Set last_sign_in on access_token generation

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#11]
`last_sign_in` exists in the auth schema (`auth.users.last_sign_in`) but is not set anywhere in gotrue

there is an opportunity to update this value each time an access_token is generated by gotrue

it will then be shown on the supabase dashboard since it's already hooked up to read this value from the DB

<img width="714" alt="image" src="https://user-images.githubusercontent.com/458736/93745091-8561f380-fc25-11ea-91c6-d9e80908a24c.png">

**Comment by awalias** [comment]
this actually looks like a bug since the value _should_ be being set [here](https://github.com/supabase/gotrue/blob/67dfa6254becd677d544c5fd0fea8e6fa4126bf6/api/token.go#L215)

**Comment by carantunes** [comment]
can i do this one?

**Comment by awalias** [comment]
sure thing @carantunes ! If you need any help you can leave a comment here and we'll take a look 👍
