### ISSUE TITLE
Confirmation URL in Email Template not giving back link with subdirectory

### ISSUE THREAD

**Issue by derseitenschneider** [supabase/gotrue#1104]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

My app sits in a subdirectory of the homepage e.g.  https://my-page.com/app. Therefore I obviously need the {{ .ConfirmationURL }} in the email template of my "confirm signup" settings to put the access token at the end of /app and not the base URL. 

My email configuration looks to be correct (see first screenshot) but the link I get back when I sign up with a new user points to the base URL and puts the access-token there (see second screenshot). It seems to ignore the /app in the site URL. So I guess there's a bug in the creation of the .ConfirmationURL?

## Expected behavior

To generate the .ConfirmationURL with the correct Site URL even with subdirectory apps.

## Screenshots
![SiteURL](https://github.com/supabase/gotrue/assets/97043252/d5b0cd6e-c93c-4105-a3d1-58d9d2c6286b)
![Email URL](https://github.com/supabase/gotrue/assets/97043252/e018fc4a-21e1-4625-81b9-89446aea5756)

**Comment by hf** [comment]
Is this occurring on a live project? If not, what version of GoTrue are you using?

**Comment by derseitenschneider** [comment]
yes, in a live project thats deployed

**Comment by kangmingtay** [comment]
hi @derseitenschneider, are you using a custom domain here?

**Comment by kangmingtay** [comment]
hi @derseitenschneider, can you please provide a snippet of the code you're using for the signup? are you using the supabase-js library?

**Comment by hf** [comment]
@derseitenschneider I think it's best if you could reach out to [Supabase support](https://supabase.com/dashboard/support/new) as this appears to be an issue with your project and not with this open-source codebase. If we identify a bug, then we can create a fix immediately or open an issue here for tracking.
