### ISSUE TITLE
Error loading template from /home/mail/templates/invite.html: Unable to fetch mail template

### ISSUE THREAD

**Issue by rienheuver** [supabase/gotrue#1111]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have changed the docker-compose file such that the gotrue container will now have a volume mount:
```
      GOTRUE_MAILER_TEMPLATES_INVITE: '/var/lib/mail/templates/invite.html'
volumes:
      - ./volumes/mail/templates/:/var/lib/mail/templates:z
```
I've used `docker exec -it supabase-auth /bin/sh` to confirm the volume is mounted correctly and the file invite.html exists.

When I send an invite email however, I get the following in the logs of the supabase-auth container:
```
2023/05/19 15:19:27 Error loading template from /var/lib/mail/templates/invite.html: Unable to fetch mail template
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow basic instructions to self-host supabase
2. Edit docker-compose as described above
3. Add the mentioned volume
4. Add a invite.html file with any contents
5. Invite a user
6. Observe the logs

## Expected behavior

The template should be used to send the email

**Comment by hf** [comment]
Hey @rienheuver,

If I'm not mistaken, the template system uses HTTP(S) to fetch the templates. There have been a few issues we've seen internally with this library we're using to do the fetching, which is unmaintained. We've got plans to re-do the whole templating system, but for now if you could expose the template on a server somewhere it should fix your problems.

Let me know if this helps!
