### ISSUE TITLE
Custom Storage Provider Polling Too Frequently

### ISSUE THREAD

**Issue by hjaber** [supabase/gotrue#1118]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. (I tried two different frameworks, I'm not sure if they are specific to my implementation or supabase)
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've been trying to create a customStorageAdapter and noticed that `getItem` and `removeItem` were running every few seconds repeatedly and indefinitely. I am calling them on the server so the console logs appear in my server terminal.

I'm not sure if this is because I am not correctly declaring them but could not stop it from basically polling while my site was on idle despite turning `persistSession: 'false'` I noticed this on both nextjs and sveltekit.

```ts
const db = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
	auth: {
		storage: {
			getItem(key) {
				console.log('getItem has run');
				return key;
			},
			setItem(key, value) {
				console.log('setItem has run');
					return;
			},
			removeItem(key) {
				console.log('removeItem has run');
				return;
			}
		}
	}
});
```

## Expected behavior

To be run on initialization and when called on auth events (signIn, signOut, etc)

**Comment by kangmingtay** [comment]
Hey @hjaber, what did you set your JWT expiry duration to? We also use the methods in the custom storage adapter in the background to ensure that the session is refreshed. Can you try setting `autoRefreshToken` to `false` and see if that helps to solve the problem?

**Comment by hjaber** [comment]
Thanks for your prompt reply @kangmingtay 

> what did you set your JWT expiry duration to?

I didn't get that far yet as I am trying to understand the storage provider better. I am trying to build a server-sided backend with `pkce` and use cookies as my `customStorageAdapter` instead of localStorage.

Would not having a JWT expiry trigger the storage adapter to run over 20x in a minute?

I'm away from my computer but I'll give setting `authRefreshToken: 'false'` a try, but I thought that was a useful setting to keep on.

 I'd like `getItem` and `setItem` to appropriately refresh the token when necessary (in my situation, set the cookie with a new value when necessary such as upon expiration)

**Comment by hjaber** [comment]
When I use `autoRefreshToken: 'false'` there seems to be less polling but it still is unpredictable behavior on the server, it is running every few minutes.

Switching tabs and refocusing causes predictable behavior on the client, the supabase client reruns on every  focus event. But, when using the  supabase client on the server, I'm unable to trace why the supabase client is re-running.

I'm going to close and wait until pkce is more stable with auth helpers before attempting my own `customStorageAdapter`.
