### ISSUE TITLE
user or account does not exist

### ISSUE THREAD

**Issue by NuvensCorporation** [supabase/gotrue#1119]
hello there, it would be nice if you could add the return: user or account does not exist.
Currently when user does not exist it just returns: Invalid login credentials.

**Comment by J0** [comment]
Hey, ,

Thanks for the feedback! This is actually intended as we don't wish to disclose whether or not a user is signed up on the platform. We're working to make the login flow more extensible though - this is one of the use cases that we'll keep in mind.

Going to close this issue for now but feel free to re-open if there are further questions/concerns or if I've misunderstood the query.

Thanks!
