### ISSUE TITLE
Unable to use OAuth login when captcha is enabled

### ISSUE THREAD

**Issue by aarushthukral** [supabase/gotrue#1120]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After enabling hCaptcha protection in the Auth settings of my project, I'm unable to sign in users using OAuth, getting a `AuthApiError: hCaptcha verification process failed` error message anytime I redirect users to an API route afterwards that has the following code:

```ts
const code = url.searchParams.get("code");

if (code) {
  await supabase.auth.exchangeCodeForSession(code);
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable hCaptcha protection in Auth settings
2. Run the `supabase.auth.signInWithOAuth({ provider: "...", options: { redirectTo: "..." } })` method on the client with the `options.redirectTo` parameter set to an API route that executes the aforementioned code
3. Complete the OAuth flow
4. See error mentioned above

## Expected behavior

Session should be created without expecting a captcha token, or captchaToken should be accepted in the options parameter of the `supabase.auth.signInWithOAuth()` method

## System information

- Version of supabase-js: 2.23.0
- Version of Node.js: 18.12.1

**Comment by silentworks** [comment]
Thank you for reporting this issue, we are currently looking into it.

**Comment by J0** [comment]
Hey @aarushthukral,

Thanks for reporting the issue! We've [put out a fix](https://github.com/supabase/gotrue/pull/1121) but we've yet to release it to all projects. If you need the fix urgently do feel free to reach out to us via [our support channel](https://app.supabase.com/support/new)

Hope this helps!
