### ISSUE TITLE
Gotrue unable to send webhook to localhost

### ISSUE THREAD

**Issue by iowathe3rd** [supabase/gotrue#1122]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 

- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I ran into a problem with webhook gotrue. The problem is that with all authorization / authentication events, GoTrue cannot send a webhook request to the local supabase edge functions runtime (on the docker compose network) server. When you try to authorize, you receive a response with the 502 bad gateway code:
```
{
     code: 502
     "msg": "Failed to connect to http://web:9000/webhook",
     "error_id": "65b9e205-cf0a-4add-9f5c-6c5cc0868ffc"
}
```
What is most interesting about this error is that it only happens after 10-15 authorization attempts (yes, I thought :)). After that the request passes and I get my webhook data.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

To repeat my mistake, you can raise supabase/gotrue and supabase/edge-runtime in the docker compose network, and create a function in edge-runtime "webhook", write any code that will accept a post request and use it as a webhook-url in gotrue.
Here is my function code:

GoTrue webhook config:

`  
      GOTRUE_WEBHOOK_URL: "http://web:9000/webhook"
      GOTRUE_WEBHOOK_SECRET: ""
      GOTRUE_WEBHOOK_RETRIES: 10
      GOTRUE_WEBHOOK_TIMEOUT_SEC: 30
      GOTRUE_WEBHOOK_EVENTS: "signup"
`

```
import {serve} from "https://deno.land/std@0.177.0/http/server.ts";

console.log('🦕Listening to GoTrue webhooks on port 8000...🦕');

async function handler(_req: Request): Response {
     try {
         console.time("webhook start")
         const body = await _req.json();
         // Process the received data from the webhook
         console.log('Webhook received:', JSON.stringify(body));
         // Further processing...
         // Sending data to the file server.
         // const response = await fetch('https://localhost:3000/user/init', {
         // method: 'POST',
         // headers: {
         // 'Content-Type': 'application/json',
         // },
         // body: JSON.stringify(body),
         // });

         // if (!response.ok) {
         // throw new Error(`Error sending data: ${response.status} ${response.statusText}`);
         // }
         const headers = new headers();
         headers.append("Content-type", "applications/json");
         console.timeEnd("webhook start")
         return new Response(JSON.stringify({message: ""}), {headers: headers, status: 200,})
     } catch (error) {
         console.timeEnd("webhook start")
         console.error('Error processing webhook:', error);
         const headers = new headers();
         headers.append("Content-type", "application/json");
         return new Response({error: error}, {headers: headers, status: 500})
     }
}

serve(handler, { port: 8000 });
```

## Expected behavior

When deploying my edge-runtime function on fly.io, requests went through immediately, and without errors, when working locally, everything does not work correctly, as I described in the bug description

## Screenshots

<img width="897" alt="изображение" src="https://github.com/supabase/gotrue/assets/81327678/620f9b59-57d4-4287-a80c-9ea36fb4d89c">

## GoTrue logs
{"auth_event":{"action":"user_signedup","actor_id":"d4d71e95-7a37-46fd-b2c2-67aa6568d59b","actor_username":"exampleuser2@mail.ru","log_type":"team","traits":{"provider":"email"}},"component":"api","error":"502: Failed to connect to http://web:9000/webhook","level":"error","method":"POST","msg":"502: Failed to connect to http://web:9000/webhook","path":"/signup","referer":"","remote_addr":"172.28.0.5:54180","timestamp":"2023-05-29T22:10:00Z"}

<img width="1011" alt="изображение" src="https://github.com/supabase/gotrue/assets/81327678/b6705a39-06ce-4534-8def-01e7dff1a517">

## System information

- OS: macOS Ventura 13.0
- Version of GoTrue: supabase/gotrue:latest
- Version of Edge runtime: ghcr.io/supabase/edge-runtime:v1.2.18
- Version of docker: Docker version 23.0.5, Docker Compose version v2.17.3

**Comment by hf** [comment]
The "webhook" support in GoTrue is inherited from Netlify and all references to it are for basic backward compatibility. Supabase's GoTrue does not use it nor do we plan to maintain those code paths. We are working on a different approach to webhooks and should have something about it this year.

I'll close this issue as not planned.
