### ISSUE TITLE
how to use kakao provider??

### ISSUE THREAD

**Issue by artifacts3** [supabase/gotrue#1126]
I know that the Kakao provider has recently been merged.
But my project auth doesn't have kakao in it.
When can I check it?

![스크린샷 2023-06-04 오전 12 02 01](https://github.com/supabase/gotrue/assets/119643740/55707ccf-8091-4d0c-a237-edc05c3de8da)

**Comment by hf** [comment]
Hey, this project is the open-source version of Supabase Auth. Features merged here take a while to be added to the platform itself.
