### ISSUE TITLE
how to use kakao provider?

### ISSUE THREAD

**Issue by artifacts3** [supabase/gotrue#1127]
i use 
```
supabase.auth.signInWithOAuth(Provider.kakao)
```
{
  "code": 400,
  "msg": "Unsupported provider: Provider kakao could not be found"
}

![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-06-03 at 23 36 34](https://github.com/supabase/supabase-flutter/assets/119643740/493a2f25-6cd2-4855-89ab-4d5119ab12e7)

**Comment by hf** [comment]
Actually may take a bit longer than end of week until the UI and everything is connected. Check the monthly updates newsletter to see when it arrives exactly.

I'll close the issue now as it's not related to this project specifically.
