### ISSUE TITLE
Apple Social login secret gen tool doesn't work on Safari. 

### ISSUE THREAD

**Issue by rtorcato** [supabase/gotrue#1131]
Apple Social login secret gen tool doesn't work on Safari. Works fine in Chrome. 

Docs need to be updated to mention the tool is broken in Safari or will never work in Safari.

https://supabase.com/docs/guides/auth/social-login/auth-apple#generate-a-client-secret

**Comment by hf** [comment]
Checking what's wrong with it. (Safari is the new IE.)

**Comment by hf** [comment]
Couldn't see any obvious errors, it's probably some issue with WebCrypto. Added a notice here: https://github.com/supabase/supabase/pull/20578
