### ISSUE TITLE
Discord Auth Identity Object possibly needs to be updated for new ``global_name`` value

### ISSUE THREAD

**Issue by Flohhhhh** [supabase/gotrue#1133]
Discord's recent update to a unique username system also brought with it a new global "Display Name" (known as ``global_name`` in user structure) for users.

The ``identities`` object included in the metadata received from Auth doesn't include that value.

[Structure from Discord](https://discord.com/developers/docs/resources/user#user-object-user-structure)

_Note: this value can be empty and would be ``null``/not included in response._

[Supabase discord.go auth provider](https://github.com/supabase/gotrue/blob/aab7c3481219f136729d80d37731aa64fb8c380a/internal/api/provider/discord.go)

**Comment by Flohhhhh** [comment]
I'm not familiar with GO or the back-end of Auth, but this is a quick example of how I would imagine it being changed:
![image](https://github.com/supabase/gotrue/assets/48927090/e5f07948-0f95-498b-bdcb-60f9e3ff156f)

**Comment by kangmingtay** [comment]
hey @Flohhhhh, thanks for reporting this issue, we have a fix in place [here](https://github.com/supabase/gotrue/pull/1171)
