### ISSUE TITLE
Unable to specify `emailRedirectTo` for resend of type 'signup'

### ISSUE THREAD

**Issue by lucadalli** [supabase/gotrue#1142]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unlike `auth.signup` which accepts a `option.emailRedirectTo` parameter, `resend` with `{ type: 'signup' }` does not allow this option to be specified.

## To Reproduce

N/A

## Expected behavior

`auth.resend` accepts a `emailRedirectTo` parameter similarly to `auth.signup`

## Screenshots

N/A

## System information

N/A

**Comment by kangmingtay** [comment]
hey @Elvincth and @lucadalli, thanks for reporting this - we've made the fix in the client library in [this PR](https://github.com/supabase/gotrue-js/pull/724)

**Comment by Elvincth** [comment]
> hey @Elvincth and @lucadalli, thanks for reporting this - we've made the fix in the client library in [this PR](https://github.com/supabase/gotrue-js/pull/724)
Thanks a lot!
