### ISSUE TITLE
Seemingly impossible to handle auth flow yourself

### ISSUE THREAD

**Issue by oliv-tree** [supabase/gotrue#1147]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

My app lets users Sign in with Steam, which uses OpenID 2.0. I have implemented this in my SvelteKit app with the help of [node-steam-openid](https://github.com/LeeviHalme/node-steam-openid). It simply returns the user's unique `steam_id` once authenticated.

I need to then link this with Supabase auth, in order to create policies like this example on my `public.users` table:
```
((((auth.jwt() -> 'user_metadata'::text) ->> 'steam_id'::text))::bigint = steam_id)
```

I want to use SSR sometimes, so I was trying to follow the [SvelteKit auth-helper example](https://github.com/supabase/auth-helpers/tree/main/examples/sveltekit). 

However, the bug is that there is seemingly a blind spot for auth that works like this. I can't create a user without supplying an email/password, which clearly does not apply in this case.

Am I missing something, or is there absolutely no way to use Supabase RLS auth (including letting it handle sessions, refresh tokens etc.,) unless you use email/password, one of the OAuth providers, phone, magic link, SSO, or OTP? I've been really shocked by this after banging my head against the wall for several days.

**Comment by kangmingtay** [comment]
Hey @oliv-tree, unfortunately, we don't really support creating a user through a custom token (in this case, the `steam_id`). However, as a workaround, you can always just the `POST /admin/users` method to create a user with email + a random password and set `email_confirm = true`. Are you able to get the steam user's email from the API? If you aren't able to get a steam user's email, you can come up with a fake email like `<steam_id>@example.com`.

**Comment by kangmingtay** [comment]
hey @oliv-tree, i'm gonna be closing this PR since it has been stale for a month, but feel free to reopen it if you wish to discuss this further
