### ISSUE TITLE
Provider error redirects: Handle redirect URLs with query parameters

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/gotrue#1150]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions). 

## Describe the bug

When an OAuth flow using a provider fails, users are redirected to the redirect URL with the `?error=...&error_description=...` query parameters appended:
https://github.com/supabase/gotrue/blob/02cb9273ec759b2ff55bea1f6eedb7b8db7a2880/internal/api/external.go#L557-L566

However, if the redirect URL has a query parameter already, this will result in the appended error detail query parameters being appended to the back of the last query parameter in the URL, which causes the `error` query parameter to effectively "disappear".

Eg. `http://REDIRECT_URL/path?existing=query?error=...&description=...`

## To Reproduce

Provide a redirect URL containing a query parameter and sign in using an provider which causes an error to be triggered.

## Expected behavior

The redirect URL should be parsed, and if it contains a query parameter, the error details should be appended using `&` instead.

**Comment by kangmingtay** [comment]
hey @bnjmnt4n, i think this should've been resolved by @J0 's PR: https://github.com/supabase/gotrue/pull/1129

**Comment by bnjmnt4n** [comment]
Hey @kangmingtay, I don't think it has been fixed: there hasn't been any change to the code block I linked to:
https://github.com/supabase/gotrue/blob/02cb9273ec759b2ff55bea1f6eedb7b8db7a2880/internal/api/external.go#L557-L566

**Comment by J0** [comment]
I'll file a PR for this today. Thanks both for flagging!

**Comment by J0** [comment]
Going to close as it should be resolved by #1224 but feel free to re-open if issue persists
