### ISSUE TITLE
Allow non http schemes for SITE_URL

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#117]
I haven't tried to repro this one yet, investigation is needed, but @farzd has [reported](https://github.com/supabase/supabase/issues/1802) that redirects don't work for none http schemes in SITE_URL

we should be very cautious of security when implementing this change, strict validation of the custom scheme will be necessary for any change

**Comment by farzd** [comment]
I'm also getting strange inconsistent results with just a HTTP url.
This is my URL
![image](https://user-images.githubusercontent.com/1423413/122970904-55977600-d386-11eb-8421-e954880eb0dd.png)

When i try do magic link via an API call
```
 const { error } = await supabase.auth.signIn({
  email: 'farzad.qasim@gmail.com',
 });
```

i'm getting [without /signin suffix in the redirect link]
![image](https://user-images.githubusercontent.com/1423413/122970709-2123ba00-d386-11eb-8a69-497c7c129021.png)

But if i send magiclink via backend CMS
![image](https://user-images.githubusercontent.com/1423413/122970798-3c8ec500-d386-11eb-9b41-0ebdc9247123.png)

I'm getting the correct url [with the /signin suffix in the redirect link]
![image](https://user-images.githubusercontent.com/1423413/122970844-47e1f080-d386-11eb-8940-d56fac2b6d0f.png)

**Comment by kiwicopple** [comment]
@farzd  - could you please check the network tab of your client, and let us know the URL when it calls [`/magiclink`](https://github.com/supabase/gotrue-js/blob/b887af5567409a189b0e700880a032c65d0d21e8/src/GoTrueApi.ts#L106)? Are there any params added to the end of the URL? It's definitely strange that there is different behaviour between the 2 systems

**Comment by farzd** [comment]
@kiwicopple from my client 
```
POST
Request URL: https://MYSUPABASEURL.supabase.co/auth/v1/magiclink
Request Payload: {email: "farzad.qasim[AT]gmail.com"}
```
I noticed that in the request headers, [i'm running a local React client]
```
origin: http://localhost:3000
referer: http://localhost:3000/
```
so i just ran the client from my IP address instead e.g: http://192.168.4.36:3000/
and now i'm getting the correct link so not sure if localhost as the referer and Site URL has something to do with it

**Comment by awalias** [comment]
@farzd I think you'll need to explicitly set `http://localhost:3000/signin` as the `redirectTo` option in the js function,

in this case the server is seeing the referer header and using that, but explicit `redirect_to` query params will take precedent

**Comment by awalias** [comment]
the original bug here seems to be an issue with the validation on the supabase dashboard, I tested the backend and it seems happy to receive alternate schemes

have opened an issue in our dashboard repo

**Comment by awalias** [comment]
hey @farzd this issue is now fixed it should be deployed into the dashboard today or tomorrow 👍

**Comment by farzd** [comment]
amazing turn around time guys 🚀 🚀 🚀  

Thanks
