### ISSUE TITLE
Add Twitch as an auth provider

### ISSUE THREAD

**Issue by iipanda** [supabase/gotrue#118]
# Feature request

## Is your feature request related to a problem? Please describe.
My application requires users to be able to authenticate with their Twitch account.

## Additional context
https://dev.twitch.tv/docs/authentication

**Comment by dougwithseismic** [comment]
I'll try to take this one - First request ever though.

**Comment by OscarWoHA** [comment]
I'm not that familiar with Go so I'll pass on this one for now, but I think a nice place to start would be here: https://github.com/twitchdev/authentication-go-sample/blob/main/oidc-authorization-code/main.go along with the official documentation. @dougwithseismic

**Comment by kangmingtay** [comment]
Hey everyone, gonna close this issue! We now have twitch as a new provider thanks to @ph1p 🎉
