### ISSUE TITLE
Chore: Return a "successful" response to avoid leaking information about who is signed up for the service

### ISSUE THREAD

**Issue by kangmingtay** [supabase/gotrue#119]
for this one we should start returning a "successful" response to avoid leaking information about who is signed up for the service

ref: https://security.stackexchange.com/a/234757

related to #114 

_Originally posted by @awalias in https://github.com/supabase/gotrue/pull/115#discussion_r655149348_

**Comment by gozeloglu** [comment]
Hi @kangmingtay. I want to solve the issue. So, you can assign to me. Before starting, I want to make sure that I am on the right point.
https://github.com/supabase/gotrue/blob/ceba0d5991b5230f25187baca9592cce576c5ca3/api/signup.go#L92

Here, this is the line that you talk on https://github.com/supabase/gotrue/pull/115#discussion_r655149348. I think I just need to change the inside of the `badRequestError` function. Am I right? Also, "**Thanks for registering, now go check your email to complete the process.**" message is suitable for this issue?
