### ISSUE TITLE
Setting Email Headers for Auth Mails

### ISSUE THREAD

**Issue by christiancito** [supabase/gotrue#120]
# Feature request

I'm currently having some email deliverability issues with @gmx and @yahoo addresses.

After some research I think it is because the auth emails don't have the "From" email header set.

## Describe the solution you'd like

Add a "From" field to the auth templates so we can set the email header.  

## Describe alternatives you've considered

Add a "From" field to the account settings to have it set global.

Thanks for your time!

**Comment by awalias** [comment]
@christiancito what value do you have in the "SMTP_ADMIN_EMAIL" field in the supabase dashboard? Is this address verified with your mail provider?

**Comment by christiancito** [comment]
@kangmingtay I'm sorry I worded the issues incorrectly. 

What I mean is that I'm unable to set the name of the sender not the email address. So the emails just come from "theater@zeitimpuls.at" not '"zeitimpuls shortfilm festival" <theater@zeitimpuls.at>'.

@awalias I have "theater@zeitimpuls.at". This email is verified with the mail provider.

**Comment by christiancito** [comment]
To fix this issue I switched from Mailjet to Postmark (all around better tool).
There I was able to set the a sender name.

Not sure if Mailjet is unique in not providing a sender name for a sender email or if it would be good to have this in Supabase. As far as I can tell the default Supabase emails also don’t have a header set.
This led tons of email servers to block us.

**Comment by kangmingtay** [comment]
> What I mean is that I'm unable to set the name of the sender not the email address. So the emails just come from "[theater@zeitimpuls.at](mailto:theater@zeitimpuls.at)" not '"zeitimpuls shortfilm festival" [theater@zeitimpuls.at](mailto:theater@zeitimpuls.at)'.

Hey @christiancito! Yeah you're right, I realised the 3rd party library we were using doesn't have the option to format the "From" header to allow for a custom sender name. I've made the fix on our end and it should be possible to do so when we enable it on the UI. Stay tuned! :)
