### ISSUE TITLE
Auth.SignUp forces email or phone

### ISSUE THREAD

**Issue by andrhubb** [supabase/gotrue#1201]
I want to create a user to have both email and phone provider auth and it is proving rather difficult to get past the following implemented  [goTrue-dart line](https://github.com/supabase/supabase-flutter/blob/main/packages/gotrue/lib/src/gotrue_client.dart).

149 - assert((email != null && phone == null) || (email == null && phone != null),
150 - 'You must provide either an email or phone number');

The ability to create a user with both email and phone parameters makes things a lot easier when verifying both before future authentications.

Is there a reason for this implementation? Can it be tweaked for the condition where both phone and email providers are being used?

**Comment by kangmingtay** [comment]
@andrhubb you can always call signUp with either email / phone first and then call the updateUser method subsequently, there are quite a few edge cases around allowing one to signUp with both email and phone which aren't trivial to tackle.

**Comment by kangmingtay** [comment]
i'm gonna close this issue for now since we don't plan to work on this but feel free to reopen it if i've misunderstood the issue, thanks!
