### ISSUE TITLE
DB_NAMESPACE other than "auth" causes error in migrations

### ISSUE THREAD

**Issue by dlebech** [supabase/gotrue#1218]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using `DB_NAMESPACE=public` on a fresh database gives the error "ERROR: schema "auth" does not exist".

The reason is that after #669, at least [one instance of `auth.X`](https://github.com/supabase/gotrue/blob/4ff1fe058cfab418c445808004091e89dcf87124/migrations/00_init_auth_schema.up.sql#L78) was not updated to use the `DB_NAMESPACE`.

I have not checked the other migration files.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use a fresh install of postgresql with just the public schema (default)
2. Use `DB_NAMESPACE=public`  as part of the environment variables
3. Run the server and receive the error on startup.

## Expected behavior

I expected that `DB_NAMESPACE` would allow me to use the `public` schema.

For now, I will just create an `auth` schema an use that.

## Screenshots

N/A

## System information

- OS: Linux
- Browser (if applies): N/A
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

With the current pattern of using a dynamically inserted environment variable for schema selection e.g. `{{ index .Options "Namespace" }}.users`, I find it quite likely that this could occur again for new migrations. This could be mitigated with a test that runs all migrations for a fresh database with a non-"auth" schema (and without the `auth` schema present).

The name `DB_NAMESPACE` is also a little bit misleading, since it's unclear what it does from the documentation, and since it doesn't really work for anything other than `auth` anyway, it could be an opportunity to perhaps rename it to `DB_SCHEMA` which would be much clearer for all Postgres user.

This is just my opinion, and you can of course feel free to ignore it :slightly_smiling_face: 

Thank you for a great library.

**Comment by szczepad** [comment]
Hey @kangmingtay (shamelessly tagging you as you've liked that proposal :P )
I've fixed the issues in the existing migrations to allow other namespaces.

Although I think the other aspects mentioned have a very valid point. In regards of testing this there were 2 ways I initially saw: 
- Adding e.g. testcontainers and running migration (and possibly other integration tests) with those. -> This would introduce another dependency
- Extending the /hack directory and adding/adapting existing Makefile-targets to also test this scenario. 

I think the first way makes more sense, as the 'hacks' impose a bigger barrier of entry for new gotrue users. Instead I would try to decrease the logic there. e.g. by moving the user creation into the Dockerfile of the DB where most users would expect it etc.

Feel free to share your thoughts and I migh extend the PR with that info. :)

**Comment by kangmingtay** [comment]
Hey @szczepad, thanks for taking the time to contribute #1279 - a nice way to catch this from happening again in the future would be to set up some sort of linting rule to ensure that the resources referenced in the migrations are not hard-coded to a specific schema and use the `{{ index .Options "Namespace" }}` go template
