### ISSUE TITLE
Enabling custom SMTP with bad credentials then disabling custom SMTP breaks sending of confirmation emails

### ISSUE THREAD

**Issue by IMakeDiscordBots** [supabase/gotrue#1238]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When enabling custom smtp in auth settings, then providing incorrect/bad entries in the custom smtp fields, saving changes, then disabling custom smtp, confirmation email for new user sign up keeps failing to send with error "Error sending confirmation email".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [Project Auth Settings](https://supabase.com/dashboard/project/PROJECT_NAME/settings/auth)
2. Scroll down to 'SMTP Settings'
3. Click on 'Enable Custom SMTP'
4. Enter incorrect/bad SMTP provider entries in given fields
5. Save changes
6. Click on 'Enable Custom SMTP' to disable it
7. Save changes
8. Attempt to sign up new user
9. Error produced, failed to send confirmation email despite sign up working fine previously before even having touched custom smtp settings, and even with custom SMTP off.

## Expected behavior

Enabling custom smtp with bad data, saving, then disabling custom smtp and saving, should make verification emails come from supabase built in smtp service.

## Screenshots
Custom SMTP is off, and yet supabase is still using the incorrect credentials I provided for a custom smtp provider, to send emails

![image](https://github.com/supabase/supabase/assets/77121499/709a6c9c-6156-484e-b53d-56b7b3abada5)

Error received when making request to my API endpoint which handles user signup(the api itself works fine, I've been testing it for a couple hours now)

![image](https://github.com/supabase/supabase/assets/77121499/b14da5dc-2b4f-4d46-abf0-e3711bad670f)

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js: v2.26.0
- Version of Node.js: v18.16.1

**Comment by hf** [comment]
I don't seem to be able to reproduce this. When you do see it, please [open a support ticket](https://supabase.com/dashboard/support/new) so that we can investigate your project's setup privately.

**Comment by GaryAustin1** [comment]
It is no longer happening for me either.
