### ISSUE TITLE
Multiple accounts with the same email address in the same linking domain detected

### ISSUE THREAD

**Issue by hexcowboy** [supabase/gotrue#1242]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The bug is described here, along with reproduction and expected behavior https://github.com/supabase/auth-helpers/issues/574

**Comment by hf** [comment]
@hexcowboy Please check this workaround: https://github.com/supabase/auth-helpers/issues/574#issuecomment-1667175171

This is not a bug (though the error should be handled better) and you need to implement a strategy in your app that will manually reconcile the duplicate accounts.

**Comment by feychenie** [comment]
@hf this link is a 404, can you post an updated link?

**Comment by marcospgp** [comment]
just ran into this error, not sure what to do about it?

I'm just trying to sign in to my app with github, and I already signed in with google using an account with the same email (let's call this email A)

I already signed in with a google and X account where the two have the same email (a different one, let's call it email B)

`Multiple+accounts+with+the+same+email+address+in+the+same+linking+domain+detected`

edit: after getting the error repeatedly, I deleted email B, and managed to log in with github successfully with an account that uses email A!

**Comment by Preetam7064** [comment]
yes same issue faced by me
