### ISSUE TITLE
Textlocal send OTP not working

### ISSUE THREAD

**Issue by iamshivkumar** [supabase/gotrue#1243]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Textlocal send OTP not working. Giving an error: "400: Error sending sms OTP: nil"
log event:
{
    "auth_event": {
        "action": "user_recovery_requested",
        "actor_id": "f532886f-ea19-4db5-bf28-3058b5d3114a",
        "actor_username": "919284103047",
        "actor_via_sso": false,
        "log_type": "user",
        "traits": {
            "channel": "sms"
        }
    },
    "component": "api",
    "error": "400: Error sending sms OTP: \u003cnil\u003e",
    "level": "info",
    "method": "POST",
    "msg": "400: Error sending sms OTP: \u003cnil\u003e",
    "path": "/otp",
    "referer": "http://localhost:3000",
    "remote_addr": "167.88.158.75",
    "time": "2023-09-07T05:32:12Z",
    "timestamp": "2023-09-07T05:32:12Z"
}
<img width="568" alt="Screenshot 2023-09-07 at 11 22 38 AM" src="https://github.com/supabase/gotrue/assets/59016883/a647e80d-9976-4a4b-889f-d215e885fb8f">

**Comment by iamshivkumar** [comment]
@hf

**Comment by sgbud** [comment]
Even I'm facing this exact issue.
I'm getting the same error response as @iamshivkumar when trying to implement sms OTP-based login.

**Comment by mahes-2** [comment]
I am facing the same issue too. Calling TextLocal API is working but when called through supabase it gives this error.

**Comment by J0** [comment]
Hey team,

Unfortunately, we're unable to test the integration as the Auth team isn't currently in possession of a phone number with the +91 prefix. However, if anyone would like to pick this up (and provide corresponding guide) I'd be happy to provide guidance.

Let us know!

**Comment by acetrondi** [comment]
It's working. There is no problem from Supabase side you have to contact Textlocal they will approve template and then it will start working. Hope this will help.

**Comment by acetrondi** [comment]
> 

I had previously approved the template for use in Supabase. However, I encountered an issue, so I reached out to the TextLocal team for assistance, and they promptly resolved it within 1-1.5 hours.

**Comment by shivkumarordrio** [comment]
I connected to Textlocal team. There was template issue. In template, I used same variable name for both variables, one for otp code and another for hash key. Variable names should be unique. 

Incorrect:
Company Name: Your code is %%|name^{"inputtype" : "text", "maxlength" : "8"}%% %%|name^{"inputtype" : "text", "maxlength" : "12"}%% - App Name

Correct:
Company Name: Your code is %%|otp^{"inputtype" : "text", "maxlength" : "8"}%% %%|hash^{"inputtype" : "text", "maxlength" : "12"}%% - App Name

**Comment by iamshivkumar** [comment]
I connected to the Textlocal team. There was a template issue. In the template, I used the same variable name for both variables, one for OTP code and another for the hash key. Variable names should be unique.

Incorrect:
Company Name: Your code is %%|name^{"inputtype" : "text", "maxlength" : "8"}%% %%|name^{"inputtype" : "text", "maxlength" : "12"}%% - App Name

Correct:
Company Name: Your code is %%|otp^{"inputtype" : "text", "maxlength" : "8"}%% %%|hash^{"inputtype" : "text", "maxlength" : "12"}%% - App Name

**Comment by J0** [comment]
Thanks team for jumping in and working together to fix the issue. Glad the issue was resolved! Feel free to let us know if there are any further questions

We'd still very much appreciate a guide similar to our [twilio and messagebird](https://github.com/supabase/supabase/tree/master/apps/docs/pages/guides/auth/phone-login) examples if anyone is keen to contribute.

**Comment by emmyduruc** [comment]
const {data, error} = await supabase.auth.signInWithOtp({
        phone: phone,
      });
      
      data logs  AuthApiError: Error sending sms OTP: <nil>
      
      i am running supabase locally and also enabled 
      [auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = true
i also added the twilo config into config.toml file.. HELP@ME

**Comment by J0** [comment]
Hey @emmyduruc,

 Are you attempting to send via Textlocal? If so you should probably add the textlocal config into the `config.toml` file instead of the Twilio config

**Comment by girish-algotech** [comment]
> > It's working. There is no problem from Supabase side you have to contact Textlocal they will approve template and then it will start working. Hope this will help.
> 
> This is not correct. We are using a template approved by TextLocal (more complete info - it's a template approved by DLT and uploaded on TextLocal). The TextLocal API is working fine when called directly, but failing when using Supabase.

Hey @sgbud, I'm facing the exact same issue today. Were you able to solve this?
 
Additional context: The SMS template is approved by DLT and Textlocal. I'm able to send SMS through Textlocal dashboard and through Textlocal API using postman. But sending sms via supabase fails, even though the I have added the exact same template and sender in supabase Providers Phone config.

**Comment by acetrondi** [comment]
> > > It's working. There is no problem from Supabase side you have to contact Textlocal they will approve template and then it will start working. Hope this will help.
> > 
> > 
> > This is not correct. We are using a template approved by TextLocal (more complete info - it's a template approved by DLT and uploaded on TextLocal). The TextLocal API is working fine when called directly, but failing when using Supabase.
> 
> Hey @sgbud, I'm facing the exact same issue today. Were you able to solve this?
> 
> Additional context: The SMS template is approved by DLT and Textlocal. I'm able to send SMS through Textlocal dashboard and through Textlocal API using postman. But sending sms via supabase fails, even though the I have added the exact same template and sender in supabase Providers Phone config.

Ask Textlocal team they will resolve it within 1-2 hour.
