### ISSUE TITLE
`GenerateTokenHash` is highly questionable

### ISSUE THREAD

**Issue by Manouchehri** [supabase/gotrue#1245]
https://github.com/supabase/gotrue/blob/577e3207aab8ee4c4661f5a8148f02296210f1d8/internal/crypto/crypto.go#L41-L43

This function gives the false security to developers that there's 224-bits of entropy when they see the `TokenHash` in an email.

e.g. when I saw `TokenHash` in an email, I thought `3f4cef3ebadfa21c8a4559e025966e5806dcc6081d3cf657444c0054` definitely couldn't be brute forced, so it would be safe to have a high OTP token lifetime.

Then... I realized that if you know the email address...

```sh
dave@mbp yep % printf "gotrue@testing.email.ai.moda131337" | sha224sum
3f4cef3ebadfa21c8a4559e025966e5806dcc6081d3cf657444c0054  -
```

And there you have it, what I thought was 224-bits of entropy, is actually less than 20-bits.

**Comment by Manouchehri** [comment]
Ah, found our internal ticket on this from a few months ago. Here's the URL to brute-force:

```sh
curl -v "https://your_instance_id_here.supabase.co/auth/v1/verify?token=calculated_hash_here&type=magiclink&redirect_to=http://127.0.0.1:31337"
```

You will hit rate limiting. I personally don't feel comfortable with rate limiting being the primary layer of defense, the OTP token should not be <20-bits to begin with.

**Comment by kangmingtay** [comment]
Hi @Manouchehri, thanks for raising this concern up! There is a tradeoff between security and UX here that we had to make. To provide more context, this should also support email and phone OTPs which require the user to enter a 6-10 digit OTP. Obviously, it would be pretty annoying to have your users enter a hash manually (yes they can copy and paste but we have had customers who reported that their users view the OTP on a separate device / don't know how to copy and paste the OTP). 

We like the idea of having a defence in-depth solution, which is also why we allow you to customise the length of the OTP for a slightly higher entropy. However, we don't want it to compromise the UX too. I don't think that these are mutually exclusive choices and I think we can definitely improve on this solution by separating the logic for generating the OTPs and the token hash embedded in the email links. That way, developers who are developing more security-sensitive applications can opt to use the email link over the OTP.

**Comment by Manouchehri** [comment]
I'm not sure why I understand the point of hashing at all here?

**Comment by kangmingtay** [comment]
@Manouchehri you don't want to have the raw values stored in the database - this is akin to hashing a user's password

**Comment by Manouchehri** [comment]
With the way you're doing the hash, it's pointless; it can always be cracked in seconds.

**Comment by kangmingtay** [comment]
@Manouchehri i think the assumption you're making here is that the attacker has access to the database system already, at which point, there are more severe issues at hand than compromising a single user's account. 

i definitely do see where you're coming from, and one of the benefits of an open-source community is that we can leverage different expertise to make the product better. It would be nice if you also supplemented your points with potential solutions too, whilst noting [the tradeoffs](https://github.com/supabase/gotrue/issues/1245#issuecomment-1736034385) i mentioned above. 

We also have a security policy [here](https://supabase.com/.well-known/security.txt) and if you do find any other potential vulnerabilities, we would really appreciate it if you communicate them through that channel.

**Comment by Manouchehri** [comment]
I'm not sure I see how this is similar to hashing a password; you hash a password so the plaintext version is difficult to recover. This is more like obfuscation, but like I mentioned at the beginning, it ends up being obfuscation for the _developer_, not to an attacker.

> with potential solutions

Change `TokenHash` to be a uniquely random (i.e. not a hash of known value).

From a quick glance, it looks like you're more or less using `TokenHash` like a `code` in a Authorization Code Flow.

> we would really appreciate it if you communicate them through that channel.

As you correctly pointed out in https://github.com/supabase/gotrue/issues/1245#issuecomment-1736034385, this is hopefully mitigated by rate limiting. (I am slightly concerned that the rate limiting is per-IP and not per target user.)

I don't think this is really a security bug. There is no increased risk in using `TokenHash` over `Token`; the problem is that `TokenHash` is basically still `Token`, but gives developers the false impression that it's something else.

**Comment by hf** [comment]
@Manouchehri Thanks for the issue. I think the discussion is getting a bit sidetracked, so could I please ask you to provide a list of short steps outlining an "attack" scenario so we can focus on identifying the severity and class of this issue.

If you feel uncomfortable doing it in public, you can always use security@supabase.com to responsibly disclose security issues. This is outlined in our [security.txt](https://supabase.com/.well-known/security.txt) file.

As for the following:

> the problem is that TokenHash is basically still Token, but gives developers the false impression that it's something else.

I don't fully agree with you about the impression bit, but I do see the point in that better docs or possibly name should have been chosen. My disagreement comes from the fact that the word _hash_ in this case means hash value from a one-way (non-password) hashing function. It's not wise to expect everyone to have a deep knowledge of hash functions, but it's generally widely known that hash functions don't change the "entropy" of the hashed value. Therefore, if `TokenHash` is important to you, in the context of the email message, then it's safe to assume that it's coming from the `Token` value.

We'll try to plan for a change in the Supabase Dashboard and docs that this makes this more prominent, but we do also accept community contributions if you have some ideas!

**Comment by Manouchehri** [comment]
Using the word "hash" is any security related context (like logging in) is fairly going to be assumed to be a cryptographic hash.

**Comment by Manouchehri** [comment]
To simplify the discussion, can you clarify these two questions:

1. What *is* the purpose of TokenHash?

2. What is the intended reason to use TokenHash over Token?

**Comment by hf** [comment]
Yes, hashing provides a security benefit. There are multiple layers of security here, entropy is not just one aspect of the issue.

Inside GoTrue / the database, token hash provides these layers of security:

1. Prevents read-only users to the database from impersonating real users.
2. Prevents large-scale account takeover attacks by binding the email address with the OTP code, so that a separate dictionary of hashes of the OTP code must be used per account, not just one set of hashes for all possible OTP codes. This also makes it more difficult to use rainbow tables techniques to "reverse" the hash function and guess the OTP code.

(Again, the method of "attack" in the above scenario is an attack from within, such as: disgruntled employee / staff member, partial or total data leak.)

Outside of GoTrue, when sent out in an email:

1. Does not have a different security benefit than just using the Token, both can be used interchangably depending on the application's use case (as pointed out by @kangmingtay).

This is why I'm not super clear what is questionable in the function, or the hashing, and would like to see an attack outline before we can have a reasonable discussion about the security of the system.

**Comment by kangmingtay** [comment]
closing this issue since it's more of a discussion rather than a bug with gotrue

**Comment by Manouchehri** [comment]
The solution is to remove GenerateTokenHash.

I think you meant to close this as won’t fix, not complete?

**Comment by tomekit** [comment]
I am with @Manouchehri on this.

In my opinion if you really aim to [("build the best Auth solution")](https://www.reddit.com/r/Supabase/comments/123yogq/comment/jerf67a/?utm_source=share&utm_medium=web2x&context=3) not just shiny play tool you need to focus on security pretty seriously.

Valid points were raised. There are couple possible resolutions here and likely longer discussion is required, but closing it doesn't solves anything and only discourages people from taking their time to report potential security issues.

**Comment by superBertBerg** [comment]
any movement regarding this?
