### ISSUE TITLE
Phone auth not working with testing phone numbers when using Twilio Verify

### ISSUE THREAD

**Issue by azlekov** [supabase/gotrue#1252]
![](https://user-images.githubusercontent.com/2267270/266400333-7d74c123-210e-47ac-9ef0-9289dce63919.png)

I have configured Twilio Verify with some testing phone numbers and test OTP.
On sign up or phone number change using a test phone number, SMS is being send via Twilio, on production nothing happens. 

When trying to enter the test OTP agains the test phone number entered before that I got:

```
Token has expired or is invalid
```

I checked the `GoTrue` source code and I think I found the issue. It looks that when Twilio Verify is configured all the OTP verification in done against it, can be observed here:

https://github.com/supabase/gotrue/blob/6ea135aa5e6745ff7cbd2e2df242218a66025ca8/internal/api/verify.go#L603-L618

The expectation is when a test phone number is used, to be verified against the test OTP, instead.

Unfortunately I'm not experienced in Go, so I cannot help with a PR, but I hope I helped with this analysis.

This issue is important as I saw many discussions and issues regarding AppStore GooglePlay reviews. Our mobile apps are also blocked being reviewed because of missing test phone auth.

We will be happy to see this quickly resolved and shipped, so we can continue using this great Supabase platform in production.

**Comment by J0** [comment]
Hey Team,

This should be patched now -  going to close but please let us know if there are still issues.

Thank you 🙏

**Comment by jibin2706** [comment]
@J0 getting the same error when using test numbers on local supabase
also, test numbers don't have to be tied to the sms provider right?
