### ISSUE TITLE
auth.resend() is not sending emails with `type: 'email_change'`

### ISSUE THREAD

**Issue by igorlanko** [supabase/gotrue#1283]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Email change confirmation triggered from `resend()` is not being sent out.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to my example I created from the Supabase SvelteKit auth template https://github.com/igorlanko/supabase-resend-bug and clone it.
2. I'm facing this issue both locally using Supabase CLI and on a hosted instance, so try using the CLI first.
3. Sign up as a new user. Open Inbucket, verify your email.
4. After logging in, go to https://localhost:3001/dashboard and change your user email by entering a different (any if it's local) email and hit “Update”.
5. To validate previous step, go to the Studio http://localhost:54323 and open `auth.users` table. Find your user and see if the `email_change` column has a value of the email you just entered.
6. Then go to Inbucket http://localhost:54324/monitor and see if you received a “Confirm Email Change” email. _Do not_ click on a link in it.
7. Now go back to the Dsahboard page https://localhost:3001/dashboard and click “Resend email confirmation”. 

## Expected behavior
After step 7 a new “Confirm Email Change” email should be sent to Inbucket.

## System information

- OS: macOS Sonoma 14.0
- supabase-js: 2.33.1
- Node.js: 20.7.0
- Supabase CLI 1.106.1

## Additional context

- An initial email change confirmation is always sent out fine for every user I tried, but it's the resend specifically that doesn't do anything;
- I can't see any errors logs in Supabase. Auth log shows `/user request started` event followed by `/user request completed` with status `200`;
- `email_change_sent_at` column in `auth.users` matches with the initial email. Not updated with `resend()`;
- No errors on the client either;
- The code responsible for the resend is in `src/routes/(app)/dashboard/+page.server.ts` of the example repo, but basically it's this:
```ts
resendEmailConfirmation: async ({ locals: { supabase } }) => {
  const userData = await supabase.auth.getUser()
  const newEmail = userData.data.user?.new_email

  const { error: resendEmailConfirmationError } = await supabase.auth.resend({
    type: 'email_change',
    email: newEmail
  })

  if (resendEmailConfirmationError) {
    console.log('Could not resend email verification email', resendEmailConfirmationError)
    return fail(500)
  }

  console.log('email change confirmation resent')
}
```

**Comment by kangmingtay** [comment]
hey @igorlanko, can you please reach out to us via support so we can look into your project? (https://supabase.com/dashboard/support/new)

**Comment by igorlanko** [comment]
@shakatakas helped debug this. Turns out you need to pass _current_ user email as an argument to `auth.resend({})`, not _new_. I had no idea, and it's not immediately clear here from the documentation https://supabase.com/docs/reference/javascript/auth-resend?example=resend-email-change-email.

@kangmingtay, would it make sense to add a note in the docs there about it? Happy to create a PR.

**Comment by kangmingtay** [comment]
@igorlanko ah yes, that's correct, feel free to create a PR and tag me to review it

**Comment by k-thornton** [comment]
running into this same issue with a slightly new quirk.  I'm using anonymous sign in, which means my user doesn't have any current email address...they ONLY have newEmail.  Is there a way to resend the email in this case?  has anyone figured it out?

**Comment by k-thornton** [comment]
Not sure if this is correct but I've worked around this case by calling updateUser again, instead of resend()

`await supabase.auth.updateUser({ email: user.new_email })
`
seems to give the correct user experience, despite feeling a little wrong

**Comment by matthova** [comment]
@k-thornton thanks for sharing. Can confirm this works for me as well with an anonymous user flow

**Comment by raahimkhan** [comment]
I am currently using this syntax. However, not receiving any email:

```
const { data, error } = await supabase.auth.resend({
            type: 'email_change',
            email
        })
```

Note: `email` in above snippet is the new email of the user. I also tried passing in the current user email. I still do not receive any email. There is no issue with my custom SMTP server because I am receiving emails for password change and signup without any issues.
