### ISSUE TITLE
Gracefully handling "Invalid Refresh Token: Already Used"

### ISSUE THREAD

**Issue by solace** [supabase/gotrue#1290]
# Bug report

## Describe the bug

Periodically, the browser console reports the thrown error: "Invalid Refresh Token: Already Used" on page load for an app session that was previously authenticated.

This effectively indicates that the current session is invalid, so the app returns to the login screen. This is fine.

However, because of this error, the user can't log back in because the `supabase.auth` sign in actions still return "Invalid Refresh Token: Already Used".

I tried detecting this error and calling `signOut` before attempting sign in again, but the error is still thrown.

The easy fix is to clear all session cookies from the browser and sign in again, but this is a terrible user experience and I would like to know how best to handle this error gracefully within the app.

## To Reproduce

I have been struggling with this for many months and as the issue is intermittent I have been unable to reliably reproduce it. Only that every now and then in my deployed environment, the session will fail to return successfully and the "Invalid Refresh Token" error will appear, and I will have to clear the browser cookies before it will work again.

I have tried extending and shortening the JWT expiry limit as recommended in some other similar issues but this doesn't help, just changes how long before it is likely to happen again.

## Expected behavior

I would like to know how to prevent this error from occurring or know the supabase recommended way of detecting and resolving the issue without forcing users to manually clear their browser session before being able to sign in again.

Is there a way to etcha-sketch the supabase session stuff entirely when this error occurs so users can cleanly sign in again?

## System information

I am not using Auth UI, but I am using:

* "@supabase/auth-helpers-nextjs": "^0.8.4"
* "@supabase/auth-helpers-react": "^0.4.2"

And used the supabase documentation + video guides for the auth-helpers for NextJS Page routing to implement authentication.

## Additional context

Side note: I am not using the new `@supabase/ssr` because I'm using the NextJS Pages router and the migration documentation does not cover this. I am also not using the app router because I have been unable to get NextJS 13 app router + supabase working. This is not a matter I wish to address at this time.

**Comment by solace** [comment]
Typical. After I submit a ticket I find some other possible solutions for this.

Combined these two:
https://github.com/supabase/gotrue-js/issues/46#issuecomment-821275075
https://github.com/vercel/next.js/issues/40146#issuecomment-1236392823

And use `middleware.ts` to identify if `supabase.auth.getSession()` returns an error and if it does, delete the cookie. Which prevents the `Invalid Refresh Token` from getting thrown on page load and locking up the other auth functions.

This appears to be a workaround, but I will be unable to confirm that it successfully manages the problem until it surfaces again as the issue is intermittent and I cannot repro even with adjusting expiries and I don't know how to forcibly trigger the error to throw in a way that will accurately replicate what is occurring.

https://github.com/supabase/auth-helpers/issues/436 suggests the error is acceptable behaviour, but it's not a great user or developer experience especially if it causes subsequent auth calls to fail rather than just clearing out the session and letting users carry on.

Closing out as 436 appears to still be discussing it and I have my possible workaround.

**Comment by bernatfortet** [comment]
@solace Would you be so kind to share the the specific code? thanks!

**Comment by solace** [comment]
@bernatfortet:

Here's the gist for `middleware.ts` placed in my Next.js source root. I am using v12. 

https://gist.github.com/solace/0414f12616f3fb362787d35a7b499d31

YMMV. As I said, I'm not sure if this actually fixes the problem and am basically waiting for it to happen again, so good luck to both of us. ;)
