### ISSUE TITLE
Return the user's Discord ID in the Supabase Auth user_metadata

### ISSUE THREAD

**Issue by fredguest** [supabase/gotrue#130]
# Feature request

## Is your feature request related to a problem? Please describe.

Many interactions with the Discord API require the authenticated user's Discord ID. The user's Discord ID is available in the Oauth flow here https://github.com/supabase/gotrue/blob/master/api/provider/discord.go#L26 but it is omitted from the Supabase Auth `user_metadata` here https://github.com/supabase/gotrue/blob/master/api/provider/discord.go#L90-L93

This is a show stopping issue for Discord specifically, but I imagine it may be useful to have the user's ID on other provider's platforms as well.

## Describe the solution you'd like

Include the user's Discord ID from the Oauth flow in the Supabase Auth `user_metadata`. Currently, when fetching either the Supabase Auth Session or the Supabase Auth User, the `user_metadata` looks like this:

```
user_metadata: {
  avatar_url: "some url",
  full_name: "some name"
}
```

This feature would change it to this:

```
user_metadata: {
  discord_id: "some id",
  avatar_url: "some url",
  full_name: "some name"
}
```

Or if it makes more sense to have a generic solution for all providers:

```
user_metadata: {
  provider_id: "some id",
  avatar_url: "some url",
  full_name: "some name"
}
```

## Describe alternatives you've considered

It's easy enough to Oauth with Discord directly through their `/users/@me` endpoint, without using the supabase-js client, and therefore have access to the user's Discord ID from the Discord Oauth response. However, this solution does more harm than good because you lose the automatic user management on the Supabase side if you bypass the supabase-js client.

**Comment by fredguest** [comment]
It does seem odd that this issue has never been raised with another provider, but I think the reason may be that most of the familiar auth providers have made their platform APIs more restricted and less useful over time, such that most developers use them exclusively for authentication at this point. Discord is the exact opposite. It has a very broad API that has only expanded in functionality over time, such that most developers primarily use it to build integrations, and therefore use the auth as well in a supporting role. In any case, the user's Discord ID is essential.

**Comment by kangmingtay** [comment]
Hi @fredguest, thanks for spotting this! I've included it in the PR [here](https://github.com/supabase/gotrue/pull/136) and it will be in the upcoming release, so stay tuned! Keep hacking 😎

**Comment by fredguest** [comment]
@kangmingtay thanks for getting this merged. Has this change flowed through to `supabase-js` yet? I'm still not seeing the 'provider_id' in the `user_metadata`.

Also, not directly related but another Discord issue, I don't see how we can specify Oauth scopes. Discord has a bunch of different scopes that can be requested during the Oath flow https://discord.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes and the scopes determine which parts of the Discord API your app is allowed to use, so they are super important. It looks like there is a placeholder for them here https://github.com/supabase/gotrue/blob/master/api/provider/discord.go#L50 but I don't see how I can actually pass any additional scopes through. Am I missing something in the docs or is it just not implemented yet?

The scopes our app specifically needs are `guilds` and `guilds.join` and there's no way to get them outside of the Oauth flow. I guess maybe I would expect to be able to specify additional  scopes on the https://app.supabase.io/project/{projectId}/auth/settings page in the same place where you toggle to enable the provider. I realize this might not the best place to discuss the issue, but I wasn't sure which of the various supabase repos to open the issue in, I figured you might have a better idea about that.
