### ISSUE TITLE
Email OTP on SignUp or SignIn sends same otp code every time and fail to verifyOtp

### ISSUE THREAD

**Issue by willieee802** [supabase/gotrue#1300]
# Bug report
The 6-digit otp within email when signing up or resending email or passwordless signing in is always same, and could not pass verifyOtp and therefore user cannot confirm that email to complete register.

- [yes] I confirm this is a bug with Supabase, not with my own application. 
- [yes] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am implementing email auth in my application. When I sign up user as below, the email with otp is received.
```typescript
    const { data, error } = await this._client.auth.signUp({
      email: email,
      password: password,
    });
```

But when I then call verify otp like below, it says 'Token has expired or is invalid. An unusual behavior here is that every time I resend email otp for signup, or completely delete that user to signup again, it always give me the same otp code, which of course would not be valid, but it is not giving me the correct otp. 
```typescript
    const { data, error } = await this._client.auth.verifyOtp({
      email: email,
      token: code,
      type: 'email',
    });
```

But If I also include the {{ .TokenHash }} and {{ .ConfirmationURL }} in email and click that confimration url, which just included the token hash in query string. The email is confirmed and I am able to sign in by password. But after that, still passwordless email sign in with otp is not working, same behaivour as signup above, always same otp.

I can confirm that I passed in correct paramters when calling those auth functions by supabase auth lib.

The only similar problem in github issues is here, and one user might encountered similar problem, email otp auth, I quoted reply that one as well. I checked the things mentioned in this issue, I do see a confirmation token existing after I call signup, and this token disappeared after I clicked on the confirmation url with hashed token.
https://github.com/supabase/gotrue/issues/905#issuecomment-1801017617

I have tried both the default email provider and my own email provider.

I leave the discord link here as well: https://discord.com/channels/839993398554656828/1171442476364607498

## Expected behavior

User email should receive the correct otp when they signup with email and pass in the 6-digit otp to verifyOtp should confirm the email and complete the signup process. Then I think passwordless signin with email would have been resolved together.

## System information

- OS: Linux
- Version of supabase-js: 2.38.4
- Version of Node.js: 20

**Comment by J0** [comment]
Hey @willieee802,

Thanks for reporting the issue - could we trouble you to open a ticket via: https://supabase.com/dashboard/support/new ?

Thanks!

**Comment by willieee802** [comment]
> Hey @willieee802,
> 
> Thanks for reporting the issue - could we trouble you to open a ticket via: https://supabase.com/dashboard/support/new ?
> 
> Thanks!

That's alright, I have submitted the ticket.

**Comment by J0** [comment]
Thanks! We'll take a look and follow up there

**Comment by J0** [comment]
Resolved on ticket

**Comment by tanish-mehta** [comment]
I am facing the same issue, can you share the solution please
