### ISSUE TITLE
Webhook secret isn't used anywhere

### ISSUE THREAD

**Issue by donalffons** [supabase/gotrue#1306]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The webhook (`GOTRUE_WEBHOOK_URL`) is called, but the secret (`GOTRUE_WEBHOOK_SECRET`) isn't sent in the headers or the body of the request. Inspecting this repository's source code indicates that the value isn't use anywhere except in that example .env file.

## Expected behavior

This value should either be used or removed from that .env file.

**Comment by J0** [comment]
Hey! As a whole the webhook configuration is currently defunct. We're working on replacing it  so do check back soon.

Out of curiosity, what modifications were you hoping to make to the flow via Webhooks?

Let us know!

**Comment by donalffons** [comment]
I've added the webhook config today and so far it looks like it's doing what I expect it to...

We're using an external auth provider - Keycloak in our case. Our Keycloak server has a bunch of roles defined for each user, which are all part of the `provider_token` available in the front-end. But since the information stored in that token isn't available in gotrue / via RLS by default (as mentioned [here](https://github.com/supabase/gotrue/issues/83)), I am using that webhook to copy the relevant roles and other bits of information into the user's `app_metadata` (via update `auth.admin.updateUserById()`).

For that use case, it would be an improvement if the `provider_token` was given to the webhook as a parameter (so I don't have to fetch the relevant information again from Keycloak). It would also be great if the webhook could be called on access token refresh's (maybe that's what `validate` is for?).

Thank you very much for your great work on Supabase, by the way. It's been great, so far.

**Comment by donalffons** [comment]
Another use case for the webhook would be this:
- I only want to allow users to sign up, which meet a certain criteria (e.g. some information from the auth provider, or based on the domain in their e-mail address.

**Comment by J0** [comment]
Oh I mean it's defunct in that we're not using it on the hosted Supabase platform - great to hear that it's working as expected though.

> I am using that webhook to copy the relevant roles and other bits of information into the user's app_metadata using the return value of the webhook.

Oh okay that makes sense. I imagine this would happen during an OAuth sign up?

> if the webhook could be called on access token refresh's (maybe that's what validate is for?).
We're working on this, but it will likely take a bit of time

>Thank you very much for your great work on Supabase, by the way. It's been great, so far.
Thanks! The experience is very much a result of the feedback from community members like yourself so thanks for taking the time to share and leave feedback.

>I only want to allow users to sign up, which meet a certain criteria (e.g. some information from the auth provider, or based on the domain in their e-mail address.

Gotcha - this is will probably land the soonest- will take this into account.

**Comment by J0** [comment]
Oh but also to return to the original question I the secret is actually used here - https://github.com/supabase/gotrue/blob/master/internal/api/hooks.go#L165

**Comment by donalffons** [comment]
> I imagine this would happen during an OAuth sign up?

Yes.

> Oh but also to return to the original question I the secret is actually used here - https://github.com/supabase/gotrue/blob/master/internal/api/hooks.go#L165

Thank you for pointing that out!
Based on that, I figured out that the webhook receives a `x-webhook-signature` header with the request. That value is a JWT signed using the `GOTRUE_WEBHOOK_SECRET` env variable. Works great, now.

Thanks a ton for your help and the work on this project!
