### ISSUE TITLE
Revoke Sign in with Apple tokens

### ISSUE THREAD

**Issue by wiverson** [supabase/gotrue#1308]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Apple insists on an in-app option to delete a user account. Sign in with Apple requires that the tokens are revoked when the account is deleted via the REST callback described here:

https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens

## To Reproduce

Any app that supports deleting an account and Sign in with Apple should include this functionality. 

## Expected behavior

I think the easiest way to implement this is via a trigger called when a auth.users row is deleted. But that's just an idea. Alternatively, it could be a GoTrue REST API call & an additional method on the client.

## System information

- OS: macOS, any web app that supports Apple identity

**Comment by hf** [comment]
Please note that deleting a user from Supabase Auth is not equivalent to deleting a user from your app. App developers have different needs and different points at which a user is considered deleted. For example, app A may want to delete users after a timeout, while app B deletes them after they've settled all payments.

For this reason, you should implement the behavior in your app. Supabase Auth does not keep track of provider refresh and access tokens.

**Comment by willsmanley** [comment]
can we request this as an optional feature? like when you configure sign in with apple, there could be an option to turn on "revoke user tokens" automatically

i know different apps have different requirements, but truly every single application in ios has to support this option

so the only apps who wouldnt need this would be those who are using sign in with apple on web only, which would be odd

**Comment by willsmanley** [comment]
fyi @hf thank you in advance

**Comment by willsmanley** [comment]
> implement the behavior in your app

still leads to abstraction leak where now application layer needs to understand where apple auth tokens are stored in auth schema

**Comment by willsmanley** [comment]
and firebase has this capability: https://firebase.google.com/docs/auth/admin/manage-sessions#revoke_refresh_tokens

**Comment by mintunitish** [comment]
@wiverson were you able to figure it out?

**Comment by willsmanley** [comment]
You can make a supabase function like this. For me, I have a user_details table which I am also deleting.

```
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from 'jsr:@supabase/supabase-js@2';
import fetch from 'npm:node-fetch';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') as string;
const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY') as string;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') as string;
const APPLE_CLIENT_ID = Deno.env.get('APPLE_CLIENT_ID') as string;
const APPLE_CLIENT_SECRET = Deno.env.get('APPLE_CLIENT_SECRET') as string;

// For more info on generating apple client secret: https://github.com/supabase/supabase/blob/master/apps/docs/components/AppleSecretGenerator/AppleSecretGenerator.tsx
// For more info revoking apple tokens: https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens/

// This is not an atomic operation. Failures do not rollback previous operations.
Deno.serve(async (req: Request) => {
  try {
    // 1. Auth
    const authHeader = req.headers.get('Authorization');
    const body = await req.json() as {
      refreshToken: string;
      accessToken: string;
    };
    const refreshToken = body.refreshToken;
    const accessToken = body.accessToken;
    if (!authHeader || !refreshToken || !accessToken) {
      return new Response('Unauthorized', { status: 401 });
    }
    const token = authHeader.split(' ')[1];
    const supabaseUserClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    const supabaseServiceClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const { data, error } = await supabaseUserClient.auth.getUser(token);
    if (error || !data.user) {
      return new Response('Unauthorized', { status: 401 });
    }
    const userId = data.user.id;

    // 2. Revoke refresh token
    const refreshResponse = await fetch('https://appleid.apple.com/auth/revoke', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: APPLE_CLIENT_ID,
        client_secret: APPLE_CLIENT_SECRET,
        token: refreshToken,
        token_type_hint: 'refresh_token'
      })
    });
  
    if (!refreshResponse.ok) {
      console.error('Failed to revoke Apple token', await refreshResponse.text());
      return new Response('Failed to revoke Apple token', { status: 400 });
    }

    // 3. Revoke access token
    const accessResponse = await fetch('https://appleid.apple.com/auth/revoke', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: APPLE_CLIENT_ID,
        client_secret: APPLE_CLIENT_SECRET,
        token: accessToken,
        token_type_hint: 'access_token'
      })
    });

    if (!accessResponse.ok) {
      console.error('Failed to revoke Apple token', await accessResponse.text());
      return new Response('Failed to revoke Apple token', { status: 400 });
    }

    // 4. Delete user details
    const { error: deleteDetailsError } = await supabaseServiceClient
      .from('user_details')
      .delete()
      .eq('user_id', userId);
    if (deleteDetailsError) {
      return new Response('Failed to delete user details', { status: 400 });
    }

    // 5. Delete user
    const { error: deleteUserError } = await supabaseServiceClient.auth.admin.deleteUser(userId);
    if (deleteUserError) {
      return new Response('Failed to delete user', { status: 400 });
    }

    return new Response('User successfully deleted', { status: 200 });

  } catch (error) {
    console.error('Error deleting user', error);
    return new Response('Server error', { status: 500 });
  }
});

/* To invoke locally:

  1. Run `supabase start` (see: https://supabase.com/docs/reference/cli/supabase-start)
  2. Make an HTTP request:

  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/deleteUser' \
    --header 'Authorization: Bearer xyz' \
    --header 'Content-Type: application/json' \
    --data '{"name":"Functions"}'

    Note you will also need to add access token and refresh token to the request body.

    Also, the authorization key might be wrong.

        To deploy:

    $ supabase functions deploy deleteUser --project-ref xyz
*/
```

**Comment by wiverson** [comment]
Thanks for the follow up. Short version is that I'm not working on this particular app any more. FWIW I think that the function/capability above should probably be included in the default SB implementation for users w/Apple SSO - it's not crazy complicated but it's just another thing to build/test.

**Comment by willsmanley** [comment]
@JValldejuli like this

```dart
      final AuthResponse response =
          await mySupabaseService.client.auth.signInWithIdToken(
        provider: OAuthProvider.apple,
        idToken: idToken,
        nonce: rawNonce,
      );

        final refreshToken = response.session?.refreshToken;
        final accessToken = response.session?.accessToken;
```

**Comment by abotkin** [comment]
> [@JValldejuli](https://github.com/JValldejuli) like this
> 
>       final AuthResponse response =
>           await mySupabaseService.client.auth.signInWithIdToken(
>         provider: OAuthProvider.apple,
>         idToken: idToken,
>         nonce: rawNonce,
>       );
> 
>         final refreshToken = response.session?.refreshToken;
>         final accessToken = response.session?.accessToken;

@willsmanley Which SDK is this through? I'm on the Swift SDK, but don't seem to be able to find the Apple ID refresh & access tokens as it appears the response's session is giving me Supabase's access & refresh token instead and the `providerRefreshToken` and `providerAccessToken` are nil (which is the other place I think would have it). Manually doing the authorization code to Apple's token endpoint to get the refresh tokens, I've seen what they should look like, but don't seem to see anything in the Session object that would match up & I can't just call Apple's token endpoint myself since the authorization codes are one-time use and Supabase's signInWithIdToken call will make it be used.

You wouldn't happen to know if there's a way to get the refresh/access tokens out of the Supabase database instead?

Also, thanks again for your code on revocation; it was spot on!
