### ISSUE TITLE
Recovery flow for Multi-Factor Authentication?

### ISSUE THREAD

**Issue by ShubhamHande99** [supabase/gotrue#1342]
**Describe the bug**
Currently, I'm using 2FA authentication for the flutter application, and this is the flow for the 2FA as described in the [docs](https://supabase.com/docs/guides/auth/auth-mfa)

When a user logs in:

1. Sign in using `email and password`
2. Check `List Factors API`
3. 1 or more factors `Open authenticator`
4. `Enter code`

Now, in this scenario, if a user deletes the authenticator setup and can no longer access the TOTP codes, what is the recovery flow for the user to regain access to 2FA?

**To Reproduce**

1. Sign in using `email and password`
2. Check `List Factors API`
3. 1 or more factors `Open authenticator`
4. Delete the authenticator setup and can no longer access the TOTP codes
5. What is the Recovery flow to  regain access to 2FA ?

**Expected behavior**
Expecting recovery flow or steps to regain access to 2FA?

**Comment by kangmingtay** [comment]
@ShubhamHande99 there isn't a way to implement recovery flow / codes but you can help the user to reset the MFA factor through the dashboard 

if you want this to be self-served, you can ask the user to create a backup TOTP factor to recover their account.

**Comment by goulashsoup** [comment]
Hacker: Hey can you reset the 2FA, I have lost access!
Admin: Sure thing, let me just disable it in the dashboard...

@kangmingtay Pretty obvious security flaw. And how is a logged out user be able to create a backup TOTP factor?

There is an OBVIOUS need for a recovery code, any other way of dealing with these situations seems unrealistic.

**Comment by pedrosimao** [comment]
I agree with @goulashsoup .
This is not acceptable.
