### ISSUE TITLE
Multiple platforms for OAuth Support?

### ISSUE THREAD

**Issue by chuckcg** [supabase/gotrue#1347]
I'm in the same situation as chrisdhanaraj, and I can't find more information about it. Is there truly no way to add multiple client IDs for OAuth? It's game-breaking, to be honest, because Google requires creating one client per platform. It makes google auth unusable if your app supports multiple platform, which is pretty common... Perhaps I'm overlooking something, but it seems quite strange to me.

### Discussed in https://github.com/orgs/supabase/discussions/4220

<div type='discussions-op-text'>

<sup>Originally posted by **chrisdhanaraj** December  1, 2021</sup>
Hello there! 

Using Google as an example, Google OAuth wants me to create a new client for each platform I'm trying to target; i.e., I have a client for iOS, Android, and Web. In Supabase, I only see the space to add one client, versus Auth0 which allows me to create multiple different applications. 

Does Supabase Auth support multiple platforms, or is it in the works?</div>

**Comment by kangmingtay** [comment]
@chuckcg we do support multiple platforms for google oauth - https://supabase.com/dashboard/project/_/auth/providers

you can add other client IDs under "Authorized Client IDs (for Android, One Tap, and Chrome extensions)"

**Comment by rhyek** [comment]
is this supported for local development in the config.toml?

**Comment by rhyek** [comment]
FYI, for a universal app I'm developing with the local development feature, I'm having to stop supabase, modify the config.toml to comment/uncomment an oauth client id, start the instance again, sign in on the corresponding device, repeat x times for each client id. Then I can work on each version of the app for however long the session lasts.

It would be great to have a better workflow for this.
