### ISSUE TITLE
`supabase.auth.admin.generateLink()` returns only the same OTP

### ISSUE THREAD

**Issue by elbracht** [supabase/gotrue#1357]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When calling the function `generateLink` several times, only the same OTP is generated for the same user. Because of this I can login once with `verifyOtp` but afterwards not anymore.

## To Reproduce

```js
const supabase createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  },
);

const { data } = await supabase.auth.admin.generateLink({
  type: 'magiclink',
  email,
});

const tokenHash = data.properties.hashed_token;

const { error } = await supabase.auth.verifyOtp({
  type: 'email',
  token_hash: tokenHash,
});

console.log(error);
// After the first successful login I get the error message:
// Database error finding user from email link
```

## Expected behavior

In my opinion, I should get a new OTP as soon as the token has been used once or has expired.
With the function `signInWithOtp` I don`t have the problem and get a different token with every call.

## System information

- OS: macOS
- Version of supabase-js: 2.33.2
- Version of Node.js: 20.5.1

**Comment by Airbornharsh** [comment]
this is working fine. I am getting different Otp everytime
