### ISSUE TITLE
Integration tests not passing

### ISSUE THREAD

**Issue by i-pip** [supabase/gotrue#137]
# Bug report

## Describe the bug

Running `make test` as described in [CONTRIBUTING.md](https://github.com/supabase/gotrue/blob/master/CONTRIBUTING.md) after following all the other steps (setup, building, migrations) results in a lot of failing tests and ultimately a null pointer error  `suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference`. Most of the failing test are failing because of a 401 (unauthorized) response 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone repo to local machine 
2. Install dependencies (including soda cli & running `make deps`)
3. Build gotrue 
4. Run migrations (`make migrate_dev` && `make migrate_test`) 
5. Test (`make test`)

## Expected behavior

Passing tests

## Screenshots
![Screenshot 2021-07-09 at 19 06 01](https://user-images.githubusercontent.com/15890505/125113295-c2ca3b80-e0e8-11eb-8915-4d65a4a53033.png)

## System information

- OS: [Ubuntu 20.04 and macOS Big Sur]
- Version of Go: [go1.16.1]

**Comment by kangmingtay** [comment]
Hey @i-pip, thanks for bringing this up! There are 2 reasons why the tests are failing currently:
1. The netlify upstream uses mysql whereas our gotrue repo is based on postgres
2. The netlify upstream uses the `is_super_admin` to determine if a user is an admin. However, our gotrue repo assigns a `role` field in the JWT to determine if a user is an admin or not. 

Going forward, the priority will be to clean up the test suite but in the meantime, we're focusing on unit testing parts of the codebase first. Hope this clarifies! :)

**Comment by i-pip** [comment]
Thanks for the clarification @kangmingtay. I've been racking my head a few days now wondering if there's something wrong with my setup (both linux and mac)... I'll leave this open for any new contributors that run into the same issue

**Comment by J0** [comment]
Closing since all the tests are passing now.

Let us know if you're still facing any issues @i-pip
Thanks for reporting this!
