### ISSUE TITLE
Using @supabase/ssr leads to endpoint issues

### ISSUE THREAD

**Issue by paulm17** [supabase/gotrue#1383]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Running a default version of gotrue and using @supabase/ssr only leads to JSON errors as the ssr library is not hitting the correct endpoint.

## Expected behavior

I have pointed out the issue here: https://github.com/supabase/auth-helpers/issues/724

As you can see here, once I am hard coding the endpoints.  It now works.

![Image](https://i.imgur.com/YgRILty.png)

## Resolution

For gotrue, create the ability to enhance the current endpoint URIs.  Seeing as the js library is hardcoded.  

> https://github.com/supabase/gotrue/blob/0100a80aa2a0e22a4ce0f281079a900cd06c1df0/internal/api/api.go#L136

I resolved this by changing to: `r.Route("/auth/v1", func(r *router) {`

Perhaps this could be overwritten by an .env option?

Thanks!

**Comment by hf** [comment]
GoTrue is not meant to be used on its own without using a proxy in front of it. GoTrue is just a bare-bones server, and there is some setup that needs to be done around it.

`@supabase/ssr` is meant to be used primarily with Supabase Auth, which includes the `/auth/v1` prefix -- which is provided by the Supabase platform. 

Therefore, if you want to use a barebones GoTrue server with `@supabase/ssr` you should put it behind a proxy that rewrites requests to use the `/auth/v1` prefix. In the future we may consider this as an option _under the frontend library_ but not on the server here.

Feel free to open an issue in that repo.
