### ISSUE TITLE
Users table index on recovery_token is not being used in queries

### ISSUE THREAD

**Issue by travis-humata** [supabase/gotrue#1398]
# Bug report

The following query, which should be nearly instant, accounts for 8% of our DB usage and 1500 ms per query:

```sql
SELECT (a bunch of columns) 
FROM users AS users 
WHERE recovery_token = $1 and is_sso_user = $2 
LIMIT $3
```

On investigation this query is running a seq_scan instead of using the index on recovery_token:

<img width="1085" alt="Screenshot 2024-02-05 at 11 43 10 AM" src="https://github.com/supabase/gotrue/assets/151555156/830ff210-9438-4ed4-ac6c-745d8dc972e8">

This is the index in question:

```sql
CREATE UNIQUE INDEX recovery_token_idx ON auth.users USING btree (recovery_token) WHERE ((recovery_token)::text !~ '^[0-9 ]*$'::text)
```

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Run:
```sql
explain analyze SELECT *
FROM auth.users
WHERE recovery_token = 'abc';
```

## Expected behavior

Should be nearly instant and use index in query plan

**Comment by J0** [comment]
closing as this has been deployed - let us know if there are still issues though

**Comment by nthouliss** [comment]
Hi, 

I'm still seeing this issue on my project. Is the index supposed to one provisioned by supabase or should we be creating this index ourselves?

<img width="853" alt="recovery_token_no_index" src="https://github.com/supabase/auth/assets/53867736/2d88c84f-2f31-4293-b5ad-367a2c23bad0">
