### ISSUE TITLE
Bring proper OAuth flow for Mobile Apps

### ISSUE THREAD

**Issue by dshukertjr** [supabase/gotrue#140]
# Feature request

## Is your feature request related to a problem? Please describe.

Please correct me if I am wrong, but currently third party login using OAuth is only supported for web. It would be great if there were a way we could login users on iOS and Android apps. 

With the current setup, when users are logging into mobile application using Supabase OAuth login, they are first redirected to the browser and would complete the login process there. The problem with this is that when doing a social login, most users are not logged in on their browser, so they are required to enter their email and password when using third party login with Supabase. This is a friction that we don't typically expect from social account login. 

I am not by all means an expert in Auth, so please correct me if I am not making sense, but it seems like not every login provider have proper auth flow for mobile apps. Here are some of my findings from a quick google search:

- Google login for mobile on how to obtain an access token note that there is no client secret:
https://developers.google.com/identity/protocols/oauth2/native-app#obtainingaccesstokens

- Facebook login for mobile on how to obtain access token
[For iOS](https://developers.facebook.com/docs/facebook-login/ios/)
[For Android](https://developers.facebook.com/docs/facebook-login/android)
- Twitter login flow seems to be same for mobile and web, so not much to do there
- Other providers are yet to have research done...

## Describe the solution you'd like

Have no idea how to go about implementing this...

## Describe alternatives you've considered

Using the auth flow of redirecting the users to the browser, which are not ideal for some platforms. 

## Additional context

This seems like a massive amount of work, so not looking for any immediate solutions, but just wanted to open this issue so that we have something to point people to when they come with this request. We are getting quite a few requests about proper mobile auth flow from Flutter developers.

**Comment by 10000multiplier** [comment]
Yep, would be nice if we could get the auth flow in react native to work properly ❗

**Comment by NiketanG** [comment]
+1 For this

**Comment by himeshp** [comment]
Hi Team, is there any eta on this from supabase end?

it would be great to know, so we can plan the mobile app development accordingly.

**Comment by dshukertjr** [comment]
With https://github.com/supabase/gotrue/pull/189, this issue is now closed!
