### ISSUE TITLE
Support for Sign in using third party OAuth access token

### ISSUE THREAD

**Issue by amitsingh-007** [supabase/gotrue#146]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to migrate my chrome extension, which currently uses `Firebase Javascript SDK`, to `Supabase`. Currently I use `chrome.identity.getAuthToken()` which returns a Google OAuth access token. Then we pass this access token to `firebase.auth.GoogleAuthProvider.credential(null, access_token)` which initializes the user session.

Is there a way I can directly use the third party OAuth access token for Supabase login?

## Describe the solution you'd like

Just like refresh token, I would like to have support for login via third party OAuth access token.

## Describe alternatives you've considered

I have tried setting the access token via the exposed method `supabase.auth.setAuth(access_token)` but it doesn't work since it only sets the jwt token and does not initialize the session.

## Additional context

I cannot use the usual login flow using Supabase third-party login provider(google) because Google restricts the opening of popups and iframes in Chrome Manifest V3.

**Comment by JanRuettinger** [comment]
@kangmingtay it looks like you gave an explanation for a login flow for an arbitrary auth provider which uses oAuth. Could you elaborate a bit more on how how "initialise the session / signup user in auth scheme" works? There are a lot of requests for new auth integrations. I think a solid guide on how to use them arbitrarily unsupported OAuth providers would help a lot of people.

**Comment by dhruvbhatia7** [comment]
+1 
Would be great to have this feature implemented as well. Refresh token only works once, I have a use-case where I need to log in the user using the same token multiple times. Sign in with access token would solve for this.

**Comment by koba-ninkigumi** [comment]
@amitsingh-007

The functionality you are looking for should be possible by using oidc's idtoken instead of oauth2's access token.

So it is practically the same as this issue.
https://github.com/supabase/gotrue-js/issues/169

And there is already a pull request for this issue.
https://github.com/supabase/gotrue-js/pull/207

Once this pull request is merged, you should have the functionality you are looking for.

Please help us merge this pull request.

**Comment by koba-ninkigumi** [comment]
@kangmingtay @JanRuettinger @dhruvbhatia7
Please Help.

**Comment by kangmingtay** [comment]
Hey everyone, we're not planning to support this in the near future because we prioritising other features such as MFA and SAML for now.
