### ISSUE TITLE
Confirmation url stripped after "#/" by browsers

### ISSUE THREAD

**Issue by tartard** [supabase/gotrue#149]
# Bug report

## Describe the bug
When clicking on the confirmation url of the invite or recover emails, if the value of the redirect_to parameter of the url contains "#/", the part after is stripped by the browser.

## To Reproduce

1. With GOTRUE_SITE_URL = http://localhost:5000/#/
2. Send an invite email.
3. Click on the link in the invite email : http://localhost:8000/ext/auth/verify?token=LxSrVKfTNFRFJK4qhF0wHA&type=invite&redirect_to=http://localhost:5000/#/
4. -> The link is opened by the browser which strips the url on '#/', so Gotrue receives a wrong redirect_to url : http://localhost:5000/ instead of http://localhost:5000/#/ . Then the user is not redirected at the expected location.

## Expected behavior

The redirect_to url should not be stripped when the user clicks on the link.    
To avoid that, Gotrue should urlencode the redirect_to parameter when building the confirmation url in the email.
The link in the email would then look like :
http://localhost:8000/ext/auth/verify?token=LxSrVKfTNFRFJK4qhF0wHA&type=invite&redirect_to=http%3A%2F%2Flocalhost%3A5000%2F%23%2F   
instead of :  
http://localhost:8000/ext/auth/verify?token=LxSrVKfTNFRFJK4qhF0wHA&type=invite&redirect_to=http://localhost:5000/#/

**Comment by MateusAmin** [comment]
This issue effects the Flutter framework as it defaults to a # url strategy. In my case my URLs are:

https://amsbkonxeeapffdsedwm.supabase.co/auth/v1/verify?token=YSt3hWNH0t-gkSIplHaPJg&type=recovery&redirect_to=http://example.com:36969/#authed?

http://example.com:36969/#access_token=asd&expires_in=3600&refresh_token=asdasd&token_type=bearer&type=recovery

While I have a work around it is painful to parse. You can see it does not even send it in a query.  I could switch URL strategies to be without the hash (which I think would fix it?) but it is not that well supported in Flutter.

**Comment by tartard** [comment]
> While I have a work around it is painful to parse. You can see it does not even send it in a query. I could switch URL strategies to be without the hash (which I think would fix it?) but it is not that well supported in Flutter.

Yes, changing URL strategies to be without the hash seems to be the only available workaround currently.

**Comment by kangmingtay** [comment]
Hey @tartard, just checking in, are you still experiencing this issue?

**Comment by tartard** [comment]
Hey @kangmingtay  , I am not on this project anymore and am not planing to take some time to dive again in supabase in the coming weeks, but reading again the discussion in the PR linked to this ticket ( https://github.com/supabase/gotrue/pull/150 ) reminds me that url-encoding the hash '#' with '%23' in the configuration solves this issue : 
`SITE_URL = http://localhost:5000/%23/`  
 
So i guess we can close this issue.  
Thanks
