### ISSUE TITLE
Support arbitrary OpenID Connect providers for external authentication

### ISSUE THREAD

**Issue by aaronpk** [supabase/gotrue#159]
# Feature request

I would like to be able to use arbitrary OpenID Connect providers for external authentication.

While this module has support for significantly more providers than the netlify fork, it is still limiting being stuck with the hardcoded providers listed here https://github.com/supabase/gotrue#external-authentication-providers

It looks like there is already a [Go OIDC client](https://github.com/coreos/go-oidc), so it should be possible to integrate relatively easily.

**Comment by JanRuettinger** [comment]
Are there any documented work arounds for using external OpenID/Auth2 providers till this is implemented?

**Comment by JanRuettinger** [comment]
Any updates?

**Comment by koba-ninkigumi** [comment]
These issues are essentially the same thing.

https://github.com/supabase/gotrue/issues/159
https://github.com/supabase/gotrue/issues/299

It is recommended that you keep one of them and close the others.

**Comment by J0** [comment]
Transferring from #299 
> Currently, id_token, nonce, and provider are required parameters in the IdTokenGrant method of gotrue/token.go.

It would be better if either "issuer and ClientID" or "provider" is specified here. (If both are specified, we need to discuss which one should be adopted.)

All you have to do is to specify the issuer and ClientID parameter directly in the "oidc.NewProvider(ctx, issuer)" part of the getVerifier method in gotrue/token.go.

Once the backend is changed to accept issuer and ClientID parameters, gotrue-js will also need to be changed to allow issuer and ClientID parameters to be specified.

Or, in the future, it may be simpler to remove the provider parameter and specify the issuer and ClientID.

**Comment by koba-ninkigumi** [comment]
@kiwicopple @J0 @mstade @kangmingtay

I wrote a pull request to resolve this issue.
I would appreciate someone who understands the OpenID Connect spec to review and merge it.

**Comment by J0** [comment]
Hey @koba-ninkigumi,

Thanks for the PR. We will look at it once a slot frees up! 

Joel
