### ISSUE TITLE
CUSTOM SMTP not working

### ISSUE THREAD

**Issue by gpaw** [supabase/gotrue#160]
# Bug report

## Describe the bug

I am getting error with sending magic links (and password recovery) emails when trying to use custom smtp

<img width="486" alt="Screen Shot 2021-07-25 at 10 54 15 am" src="https://user-images.githubusercontent.com/39247918/126884392-234d5e2d-3a9a-4871-aebe-0c1c6a23f18e.png">

The issue is happening on both on my next.js app and also supabase web ui.

![Screen Shot 2021-07-25 at 10 58 20 am](https://user-images.githubusercontent.com/39247918/126884428-f15e82a9-dc50-4c17-9ac5-5e243412dbd0.png)

Note:
Gmail less secure access has been activated. I could send emails via python's smtplib library.

## To Reproduce

Enter SMTP details for Gmail

<img width="867" alt="Screen Shot 2021-07-25 at 10 52 42 am" src="https://user-images.githubusercontent.com/39247918/126884363-b12fbe91-e89a-4b1f-8d15-2515a8124480.png">

When right clicking on user to "send magic link" it fails. This also happens to any other actions

<img width="486" alt="Screen Shot 2021-07-25 at 10 54 15 am" src="https://user-images.githubusercontent.com/39247918/126884392-234d5e2d-3a9a-4871-aebe-0c1c6a23f18e.png">

## Expected behavior

Receive an email from custom email for magic links and/or password recovery

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 1.3.2
- Version of Node.js: v14.17.3

## Additional context

N/A

**Comment by kangmingtay** [comment]
Hey @gpaw, hmm i tried reproducing this error on my end and can't seem to do so. Could you check the "Logs" section at the bottom of the "Authentication" -> "Settings" page and see what the issue is? It could be an issue with your SMTP custom config.

**Comment by gpaw** [comment]
@kangmingtay 

So the logs does not produce any recently actioned activity, maybe verbose needs to be turned on? idk

But I followed your thread and I did enabled "less secure app" (which is a must). But what I didn't do was "http://www.google.com/accounts/DisplayUnlockCaptcha " - this fixed the issue!

Mate you went above and beyond to help me on this issue, thank you so much!

Issue resolved.
