### ISSUE TITLE
Reset password (resetPasswordForEmail) ignores "redirectTo" parameter

### ISSUE THREAD

**Issue by andresiggia** [supabase/gotrue#161]
# Bug report

## Describe the bug

When a user requests the Password Reset option, they get a link which points to `...redirect_to=http://localhost:3200`, which is my app's home url, not the one specified in the `redirectTo` parameter. That way, my app router cannot show the user the option to reset the password. Similar to issue https://github.com/supabase/supabase/issues/832.

## To Reproduce

Request the password reset, make sure to specify a `redirectTo` param
```
const { data, error } = await this.supabase.auth.api.resetPasswordForEmail('test@email.com', {
   redirectTo: 'http://localhost:3200/forgot-password',
});
```

## Expected behavior

The user should receive an email containing a link with a URL pointing to `...redirect_to=http://localhost:3200/forgot-password`

## Screenshots

Authentication settings are set to allow the Forgot Password URL
![image](https://user-images.githubusercontent.com/59844981/126909841-dd87fc35-e193-427c-9295-d3af85a0c019.png)

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js: 1.20.0
- Version of Node.js: 12.19.0
- Front-end application using React Router

**Comment by kangmingtay** [comment]
related: https://github.com/supabase/gotrue-js/issues/104

**Comment by kangmingtay** [comment]
Hey @andresiggia, I'm unable to reproduce the issue you encountered and it's actually working for me. Could you send me your project ref so I can help you debug further?

**Comment by andresiggia** [comment]
@kangmingtay sure my project is studio-finder (id `vsxtrjktxzcvygmqmguh`) and I'm getting the following message on Chrome's console when requesting the password reset
![image](https://user-images.githubusercontent.com/59844981/126971136-acd3b11a-72a9-4e4e-ae69-faaf95ee3f83.png)

**Comment by kangmingtay** [comment]
Hmm, this is strange, while I debug this issue, have you tried using the cURL endpoint for sending password recovery / magiclinks? It would be a good sanity check :) 

```
curl -X POST 'https://vsxtrjktxzcvygmqmguh.supabase.co/auth/v1/recover?redirect_to' \
-H "apikey: SUPABASE_KEY" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com"
}'
```

**Comment by andresiggia** [comment]
@kangmingtay I've cleared cache here, restarted my app and now it seems to work, sorry for that.

**Comment by kangmingtay** [comment]
Awesome! Glad it's solved :)
