### ISSUE TITLE
Support Telegram as Auth provider

### ISSUE THREAD

**Issue by jsjoeio** [supabase/gotrue#167]
# Feature request

## Is your feature request related to a problem? Please describe.

For [dip.chat](https://dip.chat), we use Telegram groups. I eventually like to add login with Telegram so users can sign in to the web app and edit their profile, credit card info, etc.

## Describe the solution you'd like

As a user of supabase, I would like to be able to use [Telegram](https://telegram.org/) as an authentication provider. 

## Describe alternatives you've considered

I've requested it on NextAuth.js: https://github.com/nextauthjs/next-auth/issues/2406

I've also considered contributing it there ^ or just writing it myself in my app.

## Additional context

I am not sure where I would start, but I would considering implementing this myself with some guidance/pointers.

### Links from Telegram

- [User Authorization](https://core.telegram.org/api/auth#sign-insign-up)
- [Telegram Login Widget](https://core.telegram.org/widgets/login)
- [Telegram Login for Websites](https://telegram.org/blog/login)

**Comment by J0** [comment]
Hey all,

We'll be managing all provider related issues in #451 As such, we'll be closing this issue and managing replies over there instead.

Feel free to let us know if you have any urgent questions/concerns about this move.

Thanks!
