### ISSUE TITLE
Azure single tenant support - tenant name as parameter in auth endpoint

### ISSUE THREAD

**Issue by solvemon** [supabase/gotrue#179]
# Feature request

When authenticating against AD in Azure I get the following error:
> Application [My application name] is not configured as a multi-tenant application. Usage of the *common* endpoint is not supported for such applications created after 10-15-2018. Use a tenant-specific endpoint or configure the application to be multi-tenant.

Since I want this to be an internal-only application and all our users are in our AD in Azure, I do _not_ want to configure this to be multi-tenant.

## Describe the solution you'd like

[This StackOverflow issue](https://stackoverflow.com/questions/53526121/use-a-tenant-specific-endpoint-or-configure-the-application-to-be-multi-tenant) suggests that the endpoint needs to be specific to my application:

>  (...) the following line:
let kAuthority = "https://login.microsoftonline.com/common"
needed to be changed to:
let kAuthority = "https://login.microsoftonline.com/MY_TENANT_NAME"

This endpoint configuration is found in the [Azure provider API](https://github.com/supabase/gotrue/blob/master/api/provider/azure.go#L46):

```ts
	Endpoint: oauth2.Endpoint{
		AuthURL:  authHost + "/common/oauth2/v2.0/authorize",
		TokenURL: authHost + "/common/oauth2/v2.0/token",
	},
```

I am not sure if the tenant name needs to be in one or both of these endpoints.

One way of supplying this tenant name would be to include this as a parameter in `SupabaseClientOptions`, and another could be to use it in the `auth.signIn`-method. The first seems to me a bit cleaner, while the latter would potentially more easily allow more than one tenant (not sure if that even makes sense). 

Any feedback on this request would be greatly appreciated!

**PS:**
A million thanks to the Supabase team, you are doing a fantastic job! Thank you so much for this service! :heart:

**Comment by CrutchTheClutch** [comment]
Any progress on this?  Would love to start using supabase but this is currently a blocker for my organization.  Any way around this?

**Comment by CrutchTheClutch** [comment]
Attempted to get this started with the above draft pull request.  I'm very inexperienced with golang but I think I'm heading in the right direction.  I believe all we need is to allow the "common" part of the url to be replaceable with a config value (tenant id)

**Comment by kangmingtay** [comment]
Hi @solvemon, @CrutchTheClutch and @jimkytola, 

I'm one of the maintainers for the gotrue repo and saw that @jimkytola recently submitted a PR to fix this issue. I just have a couple of questions about this:

1. What's the difference between using `"https://login.microsoftonline.com/common"` vs `"https://login.microsoftonline.com/MY_TENANT_NAME"`? Are there situations where `/common` must be used instead? Reason for this is because I'm concerned that the PR submitted will break existing implementations that rely on `/common` for azure sign-in.

2. In the context of using Supabase, would you need to be able to set the `EXTERNAL_AZURE_URL` env var via the dashboard to `"https://login.microsoftonline.com/MY_TENANT_NAME"`?

3. What are some of the use cases for allowing more than one tenant? E.g. Will there be some cases where you would want to set the `EXTERNAL_AZURE_URL` dynamically? 

E.g. 
`"https://login.microsoftonline.com/MY_TENANT_NAME_1"`
`"https://login.microsoftonline.com/MY_TENANT_NAME_2"`
`"https://login.microsoftonline.com/MY_TENANT_NAME_3"`

**Comment by solvemon** [comment]
I am by no means competent in the world of Microsoft, so I probably don't know what I am talking about, but here is my situation. I am working in a parent-umbrella company, where other sub-organisations are members, and our Supabase-solution is made available to them. At first (when I started on our project) I thought the best solution would be to get all users into our top-level AD, and then restrict access by only allowing signups and logins from within our AD. However, this is now implemented over the `common`-endpoint, meaning I allow all Microsoft-accounts to log in. I work around this by disabling sign-up and only allowing logins that I have explicitly invited into our system (via the dashboard). This works well for us, but would obviously not scale well if the user base grows large.

1. `https://login.microsoftonline.com/MY_TENANT_NAME` will only allow users that exist in the specified tenant / AD to signup up or log in, while `/common` will allow from any Microsoft business/school account.
2. In order to restrict logins to a specified AD, you must use the name of the tenant in the Azure URL. If tenant-restriction is implemented, the `TENANT_NAME` would have to be set from the dashboard. I don't think the entire URL needs to be specified (unless there exists any other Azure-compatible login flows that uses other external systems?)
3. Allowing a set of tenants would be a very nice feature! In my case, I could potentially use this instead of the common-endpoint. A challenge here would be determining which tenant a user belongs to. Either the system needs to try and potentially fail over multiple endpoints, or maybe the user must select which tenant/organisation they are logging into?

**Comment by cerino-ligutom** [comment]
Would love to have this. Currently a blocker for our organization.

From the looks of it, https://github.com/supabase/gotrue/pull/298 should support single tenant. Not sure where to set this though, is it undocumented? or does that PR only work with self-hosted?

**Comment by kangmingtay** [comment]
Hey @cerino-ligutom, we've already merged the fix in and will deploy it to all projects this week. You will be able to add the tenant url in the authentication settings page on the dashboard. Stay tuned!

**Comment by cerino-ligutom** [comment]
Awesome! I see the option now and it works great! 🎉

![image](https://user-images.githubusercontent.com/6721822/157405596-a338edb2-274f-45f9-ac8a-eb25d369c6d7.png)

**Comment by J0** [comment]
Hey all, 

It seems like a fix has been deployed for this issue. As such, I'm going to close the issue for now but feel free to re-open if there are issues with the fix or concerns that have come up.

Thanks!
