### ISSUE TITLE
Admin API: get user by email

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/gotrue#180]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like to be able to get user details (in particular, the ID) by supplying an email address, using the admin API (with the service role API key).

## Describe the solution you'd like

An admin API which allows getting user details by email address instead of by user ID only.

## Describe alternatives you've considered

I tried to use the admin users API, but I wasn't able to figure out how to use the `filter` query parameter to search for emails (it always returned a database error). Returning all users isn't sustainable for merely looking up a single user as well. The other alternative would be to create a view of the `auth.users` table which is only accessible to the `service_role` role, to allow convenient access to the table via the Supabase JS client.

**Comment by kangmingtay** [comment]
Hey @bnjmnt4n, thanks for raising up this issue! The filter query params to search for emails was broken because it was using mysql dialect. Since this version of gotrue supports postgres, we are working on fixing it. With regards to the supabase js client library, we are also working on splitting the admin api functionality into a separate package. There's an open issue [here](https://github.com/supabase/gotrue-js/issues/90) which will be updated once its ready!

**Comment by bnjmnt4n** [comment]
The filter parameter seems to work now, but I'm not sure how to properly filter by email. Requests to `/users?filter=email%40domain.com` and /users?filter=email@domain.com` both do not return the appropriate email. Would greatly appreciate some guidance in knowing the right format for providing exact emails to filter by. Right now, my workaround is to request `/users?filter=domain.com` and then iterating through the result for the right email.

**Comment by kangmingtay** [comment]
Hi @bnjmnt4n, I tried to filtering by `/admin/users?filter=email@domain.com` and it seems to work for me. You can check out how the filter logic works to look up the email [here](https://github.com/supabase/gotrue/blob/master/models/user.go#L408-L412). Let me know if you're still facing this issue!

**Comment by kangmingtay** [comment]
Hi @came, if you're using the `supabase-js` library, we currently don't support getting a user by id but we have created [an issue](https://github.com/supabase/gotrue-js/issues/190) to keep track of it and will be looking to add it in the next couple of weeks! 

We also currently only support connecting to the public and storage schema so the following wouldn't work:
```
const supabase = createClient(supabase_url, supabase_key, {
  schema: "auth"
})

const res = await supabase.from('users').select('id').eq('email', 'email@domain.com')
```

**Comment by bnjmnt4n** [comment]
Closing this, not sure why the filtering wasn't working for me back then, but it works now!
