### ISSUE TITLE
Improve error message when providers are disabled

### ISSUE THREAD

**Issue by darora** [supabase/gotrue#184]
e.g. "email logins are disabled" would be cleaner than "unsupported email provider"

The latter can cause confusion that a particular email service provider e.g. protonmail is incompatible https://github.com/supabase/supabase/issues/2851

**Comment by nickmancari** [comment]
I'll take care of this. I'd love to help out!

**Comment by nickmancari** [comment]
Submitted the PR to address this issue.

**Comment by darora** [comment]
Closed by #186 , thanks!
