### ISSUE TITLE
Configuration DB_NAMESPACE has no effect

### ISSUE THREAD

**Issue by Mimameid** [supabase/gotrue#185]
# Bug report
DB_NAMESPACE configuration is supposed to add a prefix to the tables.

> Adds a prefix to all table names.

It doesn't have any effect.

## Describe the bug
Changing the value for DB_NAMESPACE doesn't do anything in postgres.

## Expected behavior
That the prefixes of the tables are set accordingly.

## Additional context
After comparing superficially the netlify repo and this one, I figured, that the feature has been removed from the core. I'm convinced that this has to do with supabase using postgres as the underlying DB and defining schemas there, but before digging deeper, it would be interesting to know what the developers motivation and goal was and if it is somehow possible to bring the feature back in. Or is there already another way to have multiple unrelated tables?

**Comment by kangmingtay** [comment]
>  I'm convinced that this has to do with supabase using postgres as the underlying DB and defining schemas there

Hey @Mimameid, thanks for the question! We decided to remove the `DB_NAMESPACE` env var because postgres makes use of schemas instead of namespaces. Do you have some use case for wanting to use the `DB_NAMESPACE` ?

**Comment by Mimameid** [comment]
> Hey @Mimameid, thanks for the question! We decided to remove the `DB_NAMESPACE` env var because postgres makes use of schemas instead of namespaces. Do you have some use case for wanting to use the `DB_NAMESPACE` ? 

The docs should be updated. Apart from that:

Two front end applications. One for customers and one for organizers. I would like to use one supabase project since they use the same underlying data. Organizers can manipulate it and customers can't. 

The issue I see, and correct me if I am wrong: When using one project, customers would be able to authenticate for the organizer's front end and vice versa. Even though there is the possibility to restrict their access type (policies) on the database, the authentication would be valid. 

How would one solve this with supabase?

**Comment by Mimameid** [comment]
> Hey @Mimameid, I see, hmm for your use case, using the `DB_NAMESPACE` wouldn't help much even if it worked. Also, separating the customers and organisers into 2 different schemas isn't ideal. As of now, gotrue doesn't support role-based access control (RBAC) yet but I can think of 2 possible solutions for you:
> 
> 1. you can assign each user to a customer or organiser role and save it in postgres (maybe as another table). And based on the user's role, you decide which UI to show. You can use RLS to limit access to data based on the user's role.
> 2. Alternatively, you can assign each user to a customer or organiser role. If the user is an organiser, you have some backend function to access the organisers' data using the `service_role` key we provide on the dashboard. Customers will be assigned the `anon_key` to use.
> 
> Let me know if this helps!

Those are workarounds, but delegate the issue.

From what I understand it should be able to change the namespace/schema through the config as the original repo does:
https://github.com/netlify/gotrue/blob/4730b6ae9447443bc3d8687a33067574a1403c4f/cmd/migrate_cmd.go#L38-L41

This fork doesn't allow to do so. 

If there is no intention to allow this feature in supabase, which imo would be a pity, it should at least be considered to remove it from the docs [here](https://github.com/supabase/gotrue/blob/master/README.md) and [here](https://supabase.io/docs/gotrue/server/about) before closing this issue.

**Comment by Mimameid** [comment]
Hey @kangmingtay,

would you reopen this?

**Comment by kangmingtay** [comment]
Hey @Mimameid, sorry for the late reply! Didn't mean to close it actually. To address your concerns:
1. We'll add back the support for setting the schema dynamically. It's not a high priority in the current sprint, but you're welcome to contribute if something urgent for you.
2. Are you planning to use the DB_NAMESPACE to separate the customers and organisers in different schemas? I would recommend the solutions I've provided above if you want to implement some form of RBAC. Personally, I feel that RLS is the best option for your use case (and the most secure) because the access-control is restricted on the database level.

**Comment by Mimameid** [comment]
@kangmingtay 

1. Sounds good. I might have a look into it, even though my GO knowledge is limited (as of now).

2. Well, it is maybe a bit more complicated. The register/signup endpoint for organizers shouldn't be public. Matter of fact, only an operator of the service is allowed to register/signup new organizers. Now in supabase a regular user would use the same endpoint to register/signup and furthermore login and authenticate. To guarantee separation between the two using roles or some other flag, extended custom logic is needed. 
At this point I would like to refer to the original documentation regarding the DB_NAMESPACE config: `Adds a prefix to all table names.`
What this means is, that I can use the same postgres, same schema, but 2 different GoTrue gateways, as far as I understand.

**Comment by J0** [comment]
This issue is open for contributions:

One possible approach to consider would be to read the `DB_NAMESPACE` environment variable  in before running the migration and looking into each migration file to replace the corresponding schema name(mysql uses namespaces but postgres uses schema)
