### ISSUE TITLE
Netlify OAuth Provider

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue#187]
# Feature request

## Is your feature request related to a problem? Please describe.

Add Netlify OAuth provider

## Additional context

https://twitter.com/jlengstorf/status/1429611357356187652

<img width="595" alt="image" src="https://user-images.githubusercontent.com/10214025/130551483-e83c85db-62e9-471f-bb37-5dea9e139959.png">

https://app.netlify.com/user/applications

**Comment by kiwicopple** [comment]
Might need to hold off on this one until some of the security issues here are covered: https://community.redwoodjs.com/t/i-implemented-a-netlify-oauth-not-identity-auth-provider-but-im-not-sure-i-should-have-and-why/903

**Comment by J0** [comment]
Hey all,

We plan on tracking all OAuth provider requests on https://github.com/supabase/gotrue/issues/451 so we'll be closing this issue in favor of the thread instead. Please feel free to follow along there instead.

Thanks!
