### ISSUE TITLE
Improve message and move disable logic on magic links to signup only 

### ISSUE THREAD

**Issue by denneralex** [supabase/gotrue#190]
Hey there, I've been following these issues: #184 & supabase/supabase#2851. And looking at the code I have an impression that the message change done on #186 is still not accurate for Magic Links. The new message says `Email logins are disabled` and for me its a bit misleading because the UI on Supabase says Signup and not login. See picture below:

![Screen Shot 2021-08-24 at 8 22 53 PM](https://user-images.githubusercontent.com/5065602/130706776-6075c269-7938-4135-a176-a9bd9916e35d.png)

Now, if I'm not totally off here, I think there's one other thing that's also misleading on this. It's this line here: https://github.com/supabase/gotrue/blob/9b955cbce0f19979d32429a3e5bb5425e7fd05f2/api/magic_link.go#L25

This line throws an error for Magic Links if the Email config is disabled, independent if its a signup (new user) or a signin (existing user) but the toggle on Supabase UI says Signup (same screenshot above). 

I would expect in this case, as a supabase user, that if I disable the signup toggle on the UI, that my existing users would still be able to get a Magic Link and signin and in case it's a new email/user then they would get that error and the message should say `Email signups are disabled` instead of saying logins.  

And if that would be the direction, then the check for `if !config.External.Email.Enabled` would make more sense if it was after this line, where it knows its a signup (new user): (https://github.com/supabase/gotrue/blob/9b955cbce0f19979d32429a3e5bb5425e7fd05f2/api/magic_link.go#L47)

I'm using Supabase and that is the behavior I was expecting when I disabled Email signups on the Auth settings but instead, what its doing today is that it's blocking both signup AND signin for Magic Links, and I think this is the reason.

If this make sense at all I could try to make a PR.

**Comment by zavbala** [comment]
I come from the future, any solution yet? :open_mouth:

**Comment by aunumever** [comment]
I need this feature. It doesn't make sense to me that sign ins are disabled. I also have a limited audience, but would appreciate that login flow. I want it to be invite only, or manually make an API request, not when a user signs in.  I don't want incorrect emails and random bots filling up my DB table with records `Waiting for verification..`.

**Comment by TomasHubelbauer** [comment]
@kangmingtay I think there is some confusion here, very possibly on my part, but in the original message I see this line:

> I would expect in this case, as a supabase user, that if I disable the signup toggle on the UI, that my existing users would still be able to get a Magic Link and signin

You say

> Currently, we don't see a usecase where you would want to enable email sign-ups but not email sign-ins.

I think that's the opposite of what the OP means? I am interested in this thread because I actually have an issue of my own going, #330, and that one is about making it possible to enable email signins but not email signups. And I feel like this issue is very related to this, just instead of email signins it is talking specifically about magic links.

**Comment by kangmingtay** [comment]
@TomasHubelbauer just to clarify, the UI looks different on our platform now - it's been updated to show this: 

If the "Enable email provider" toggle is switched on, then it will allow any email-related signups and sign-ins. Can you please describe why you would want to enable sign-ins only but not signups? 

<img width="989" alt="image" src="https://user-images.githubusercontent.com/28647601/191407574-c2229c8b-081c-4a4e-af9e-8f34244554d9.png">

**Comment by mrmartineau** [comment]
@TomasHubelbauer there's also this setting which would have the intended effect, however it is not specific to email or magic link sign-in

<img width="891" alt="image" src="https://user-images.githubusercontent.com/64883/191717431-2cbfa893-0d51-4b26-a7d3-14f619c7b7a0.png">

**Comment by TomasHubelbauer** [comment]
@mrmartineau I was not aware this existed, I think it is newer than my GitHub issue. I will check this out. Thank you for letting me know! It seems super promising for what I need.

**Comment by juanvilladev** [comment]
Hello, just wanted to ask, if we could update the config.toml file that's used for local development. Currently, the email provider section contains these keys:
```
[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = false
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
```
The overall [auth] section contains the following keys:
```
[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = false
```
If we enable disable the signup key under auth.email, we cannot login anymore. This is quite misleading. We get the same error: 
```
Email logins are disabled
```

If you want to achieve enabled logins but disabled sign ups, you have to disable the signup key in the [auth] section and enable it in the [auth.signup] section which is quite confusing.

Thanks!

**Comment by rdylina** [comment]
> @TomasHubelbauer there's also this setting which would have the intended effect, however it is not specific to email or magic link sign-in
> 
> <img alt="image" width="891" src="https://user-images.githubusercontent.com/64883/191717431-2cbfa893-0d51-4b26-a7d3-14f619c7b7a0.png">

Where is this toggle located? I can't seem to find it.

**Comment by MARCA-Charlie** [comment]
> enable it in the [auth.signup] section which is quite confusing

Actually, I think you made a typo, but you helped fix this confusing problem for me! It should be

[auth.enable_signup] = false
[auth.email.enable_signup] = true

This allows my users to sign in using their email (and in my case passwordless) but does not automatically create new users when attempting to sign in with an email that is not yet registered. 

> @TomasHubelbauer just to clarify, the UI looks different on our platform now - it's been updated to show this:
> 
> If the "Enable email provider" toggle is switched on, then it will allow any email-related signups and sign-ins. Can you please describe why you would want to enable sign-ins only but not signups?
> 
> <img alt="image" width="989" src="https://user-images.githubusercontent.com/28647601/191407574-c2229c8b-081c-4a4e-af9e-8f34244554d9.png">

My scenario is that we create users based on their signup to an external service, therefore we do not want to permit signups via supabase. Instead, they are created using the same email as they used in external service, and can log into services provided by supabase using that same email. Therefore, login but not signup is a very valid use case IMO. 

Thanks everyone for help
