### ISSUE TITLE
TikTok OAuth Provider

### ISSUE THREAD

**Issue by chimon2000** [supabase/gotrue#199]
# Feature request

Create an OAuth provider for TikToke

TikTok recently published their OAuth flow
https://developers.tiktok.com/doc/login-kit-web

## Is your feature request related to a problem? Please describe.

For the application that I am working on, we convert users from TikTok.  Currently, we plan to authenticate them from  using Phone authentication, but TikTok support could drastically improve our conversion.

## Describe the solution you'd like

Social login with TikTok is supported similar to existing 3rd party providers.

## Describe alternatives you've considered

The only other alternative would be to host our own authentication server and use it in tandem with Supabase.  Not particularly ideal.

## Additional context

n/a

**Comment by J0** [comment]
Duplicate of #451
