### ISSUE TITLE
Generate swagger spec from source

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#20]
https://medium.com/@pedram.esmaeeli/generate-swagger-specification-from-go-source-code-648615f7b9d9

**Comment by icecream78** [comment]
I started doing this task by using go-swagger and this is not so easy how it was seamed. But I`ve done some work and have a quastion. @awalias @steve-chavez Do I need include description of /admin/* , /saml/* , /instances/* to result ?

**Comment by kiwicopple** [comment]
> Do I need include description of /admin/* , /saml/* , /instances/* to result ? Because in README that groups aren't been covered

Ideally it will autogen everything - is there some manual work to enable the routes?

**Comment by icecream78** [comment]
Every route need to be described manually and then spec will be generated according to it

**Comment by kiwicopple** [comment]
I see, perhaps we start with a very small set of routes and then expand it if it seems like it's the right long-term solution?

**Comment by icecream78** [comment]
Yeah, I agree. Initial set of routes will be the same as in REAMDE. I think that it's enough to start

**Comment by J0** [comment]
Hey! 

Thanks for looking into the issue! Unfortunately, the Swagger spec has been de-prioritized for the moment as we don't quite have the bandwidth to maintain it. I'm going to close this for now but feel free to re-open if you have any questions or concerns.

Thanks!
