### ISSUE TITLE
Misunderstanding the email_change

### ISSUE THREAD

**Issue by xurshid29** [supabase/gotrue#200]
Hello, I think something wrong with the email_change functionality. I'm successfully getting a verification link after changing the current email, but getting a json message (`{"code":202,"msg":"Email change request accepted"}`) after clicking it, nothing else.

I think,  the 334 line of verify.go should not be returned with nil and interrupt the execution

<img width="1022" alt="Screen Shot 2021-09-03 at 13 11 02" src="https://user-images.githubusercontent.com/5887811/131973965-98521249-2af2-4b74-9e9a-31206ccfaaa1.png">

**Comment by kangmingtay** [comment]
Hey @xurshid29, this is intended as we send 2 emails when a user requests for an email change- one to the old account and one to the new account. We'll add some documentation to make this clearer in the future!

**Comment by xurshid29** [comment]
@kangmingtay  Thanks for the clarification. This is not a bug, this is a feature). How can I remove a bug label from this issue then?

**Comment by DavraYoung** [comment]
Maybe we can specify second `redirect_to `query parameter for this request? When the acceptedTokenError is returned, we will allow developers to redirect users to the specified url, instead of showing blank JSON page?

**Comment by kangmingtay** [comment]
Hey @DavraYoung, yeah this sounds good, will fix this soon!
