### ISSUE TITLE
Cannot Turn Off Automatic Account Merging

### ISSUE THREAD

**Issue by wiverson** [supabase/gotrue#209]
## Describe the bug

Supabase automatically merges different provider accounts by email address.

## To Reproduce

1. Create an account using Supabase Auth with GitHub as provider, where the GitHub account has the email address test@example.com.
2. Log out.
3. Log in again, but this time using Twitter as the provider. The Twitter account has the same email address test@example.com.
4. When the user comes back, they now get the GitHub login information, not the Twitter information.

## Expected behavior

Couple of different options - Firebase has a flow for this scenario, but it's a bit complicated IMHO:

https://firebase.google.com/docs/auth/web/account-linking

Suggestion:

Create a switch in Supabase UI that defaults to off - "Allow Account Merging". If it's off logging in with different providers creates different accounts - the end.

- If Account Merging is set to true, if a sign in with a duplicate is detected generate a new event "request account link" with a flow similar to a password reset.
- Add an auth query to request linked profiles.
- Add an auth operation to unlinked profiles.

**Comment by J0** [comment]
Hi everyone, we currently don't have plans to support manual linking of accounts in the near future. Currently, GoTrue only supports automatic linking of accounts based on the user's email.


We will revisit on the future though, so feel free to follow along on #313
