### ISSUE TITLE
Allow configuration string or template file for custom email templates

### ISSUE THREAD

**Issue by Mimameid** [supabase/gotrue#212]
# Feature request

## Is your feature request related to a problem? Please describe.

The only way to use custom email templates is using a URL via `MAILER_TEMPLATES_<TYPE>` configuration as suggested in [the docs](https://github.com/supabase/gotrue/blob/master/README.md). One can't deploy GoTrue with custom template files or set a string in the config.

## Describe the solution you'd like

1. Be able to set a config/environment variable like `MAILER_TEMPLATES_<TYPE>_CONTENT`.
2. Deploy GoTrue with template files

**Comment by kangmingtay** [comment]
Hey @Mimameid, we've added an endpoint to generate your own signup / recovery / invite or magiclinks [here](https://github.com/supabase/gotrue#post-admingenerate_link) so you can use any email provider / smtp server and customise the email templates freely.

**Comment by Mimameid** [comment]
Hey @kangmingtay, this is not quite it, since it demands quite some work on the developers end and bypasses the mailing functionality of GoTrue.

While the functionality is there. One would just need to allow to overwrite the [the default values](https://github.com/supabase/gotrue/blob/master/mailer/template.go#L21-L44). This would provide some basic email templating functionality and would be simpler and faster for the developer.

What do you think?

**Comment by kangmingtay** [comment]
Hmm I don't think it's necessary to create another env var to support this. If you're planning to self-host gotrue, you can just create your template html files and host them on a storage service (such as AWS S3 or Supabase storage 🤣), and point the `MAILER_TEMPLATES_<TYPE>` to the corresponding URL.

**Comment by Mimameid** [comment]
@kangmingtay Ok, got you. Thanks for the exchange. I think you can close it then.

**Comment by Mimameid** [comment]
@kangmingtay the thing is, GoTrue would need to be connected to the internet witht he suggested solution. But ok. I guess there is no interest in such a feature.

**Comment by Mimameid** [comment]
@kangmingtay I thought about it, your suggestion can work.

I still think, for something very basic and simple, it can be a nice thing to have. But I understand if there is no interest in such a "feature", since there are other means to tackle it.

**Comment by J0** [comment]
Seems like the issue here has been resolved -- going to close for now but feel free to re-open if there are still pressing queries.

Rest assured that we are working on the email templating experience and you should be able to see updates soon.

Thanks
