### ISSUE TITLE
Add Auth0 as a Login Provider

### ISSUE THREAD

**Issue by juanzgc** [supabase/gotrue#215]
# Feature request

## Auth0

Would it be possible to include Auth0 as a login provider. Would like transition over to Supabase however this is preventing me from doing so.

## Describe alternatives you've considered

Tutorial on importing users from Auth0.

**Comment by J0** [comment]
Hey all,

We plan on tracking all OAuth provider requests on https://github.com/supabase/gotrue/issues/451 so we'll be closing this issue in favor of the thread instead. Please feel free to follow along there instead.

Thanks!
