### ISSUE TITLE
Error response for Sign-up with email & password should include error type (or code) to handle the reason of error, in client side.

### ISSUE THREAD

**Issue by sugitlab** [supabase/gotrue#217]
# Feature request

I'm using gotrue client like "gotrue-js" and "gotrue-dart". When calling sign-up with email and password, it return the error as just a **String** message, like "A user with this email address has already been registered". It's meaningful but difficult to handle the error in client side because it doesn't express with programmatic type or code.

## Describe the solution you'd like

Include defined error code with error message in the response.

## Describe alternatives you've considered

For the time being, I've made wrapper code to judge the error type with error message sentence.  But it's not safety, so headache for me.

## Additional context

Firebase has [FirebaseAuthException](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthException). 
Client can identify the reason of error by checking that exception code, like "email-already-in-use", "invalid-email", "week-password" .... .

**I really love the supabase!! I appreciate you to make this fantastic BaaS and packages.**

**Comment by hf** [comment]
This is intentional because the explanatory message would leak information that the user has an account. We are thinking about removing this obfuscation though in a next major version of GoTrue and its client libraries.
