### ISSUE TITLE
User already signed up is throwing a wrong message and supabase.io panel not being respected

### ISSUE THREAD

**Issue by obetomuniz** [supabase/gotrue#228]
# Bug report

## Describe the bug

Even with the "Enable email confirmations" option disabled, I am receiving the message "Thanks for registering, now check your email to complete the process." when I try to signup a user already registered. I don't remember exactly the message, but before this bug start, I was receiving some messages like `User already been registered` when trying to re-signup an already created user. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Disable Email confirmations on Supabase.io
2. Try to register an already registered user
3. See throwing with the wrong message

## Expected behavior

When trying to register an already registered user, the message should be consistent and in sync with supabase.io rules of Authentication. 

## System information

- OS: MacOS
- Version of supabase-js: 1.23.1
- Version of Node.js: v12.13.0

## Additional context

This issue breaks my app for 2 days once this messaging flow is the way that I can ensure that a user exists or not in Supabase User Base.

**Comment by J0** [comment]
Seems like this has been resolved by #237  am going to close this for now but feel free to re-open if you are still facing issues.

Thanks!
