### ISSUE TITLE
[Dashboard] Allow custom proxy URLs for EXTERNAL_X_REDIRECT_URI

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#233]
A user should be able to swap the redirect URL for a vanity proxy address they have set up

### Discussed in https://github.com/supabase/supabase/discussions/3428

<div type='discussions-op-text'>

<sup>Originally posted by **ilyabo** October  5, 2021</sup>
Is it possible to use the actual site URL in the auth callback URL for external OAuth providers? Maybe at least with the Pro plan?

It doesn't look very convincing or trustworthy with the randomly generated hostname:

<img src=https://user-images.githubusercontent.com/351828/136155124-b53dfc19-9f91-4281-b552-e364e129b175.png width=300>

I tried adding a URL-rewrite on Vercel (from `https://…supabase.co/auth/v1/callback` to `https://mysiteurl.com/auth/v1/callback`), but I am getting this error when trying to authenticate with GitHub:
```
?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.
```</div>

**Comment by talmr-k** [comment]
I am having the same issue. Is there any update?

**Comment by TheThirdRace** [comment]
I agree, the current random generated database name is screaming "I've been hacked, don't sign in!!!".

Would it be possible to use the new `_middleware.js` in NextJs 12 to receive the request then await the response from the real database?

ex:

Google => your site => async request to Supabase => back to your site => back to Google

**Comment by J0** [comment]
This looks like it might be a /\subset of the problem described in #143 

Shall we close the issue and continue the discussion there instead?

**Comment by kangmingtay** [comment]
@J0 yeah good call, lets close this one
