### ISSUE TITLE
auth.signUp() - Error messages not directed related to issue

### ISSUE THREAD

**Issue by lucasmrl** [supabase/gotrue#235]
# Bug report

## Describe the bug

**Case 1:** When a user is trying to **sign up with an already existing email**, the error message prints:
`"Thanks for registering, now check your email to complete the process"`

![Image Description](https://hdmlbxshrurxrggmrogp.supabase.co/storage/v1/object/public/gpic/v1/image_2021_fUlL_M7zxP)

**Case 2:** When a user is trying to **sign up without an e-mail**, the error message prints:
`"Signup provider must be either email or phone"`, even though **Phone Signup is disabled**.

![Image Description](https://hdmlbxshrurxrggmrogp.supabase.co/storage/v1/object/public/gpic/v1/image_2021_BmhPV4Zq6Z)
![Image Description](https://hdmlbxshrurxrggmrogp.supabase.co/storage/v1/object/public/gpic/v1/image_2021_iFzCk08Ph0)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

This happens whenever I use:
```
const { user, session, error } = await supabase.auth.signUp({
  email: 'example@email.com',
  password: 'example-password',
})
```

## Expected behavior

Error messages should reflect the respective issue.

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of supabase-js: 1.24.0
- Version of Node.js: 14.17.6

**Comment by bariqhibat** [comment]
Hey, pretty sure this would be fixed in next release, we can close this! @kangmingtay
