### ISSUE TITLE
magic link: improve responses

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#24]
magic link currently returns sign in responses when user doesn't exist (access_token, or confirmation_sent_at etc.)

and returns nothing when user exists and magic link is sent, recover endpoint returns and empty json body `{}` so should standardize

**Comment by icecream78** [comment]
@awalias as far as i understand you want just standardise answers and add to magic link response empty json answer?

**Comment by awalias** [comment]
if successful the response should just be `{}`

if MaxFrequency is broken then we should probably return an error with 429 response code: https://github.com/supabase/gotrue/blob/f82003ca7fec0ba23e1f4ab4fa4325b007063b05/api/mail.go#L61

the problem is we need to suppress the json response from the SignUp method [here](https://github.com/supabase/gotrue/blob/f82003ca7fec0ba23e1f4ab4fa4325b007063b05/api/magic_link.go#L60) and [here](https://github.com/supabase/gotrue/blob/f82003ca7fec0ba23e1f4ab4fa4325b007063b05/api/magic_link.go#L53)

**Comment by icecream78** [comment]
@awalias in cases when SignUp method respond with some error - do we need show same error which reterned from that method? 
I have one option for dealing with response from SignUp method. Just implement struct, that fits Response interface and handle response.
For example:
Response stub code

```go
type responseStub struct {
}

func (rw *responseStub) Header() http.Header {
	return nil
}

func (rw *responseStub) Write(data []byte) (int, error) {
	return 0, nil
}

func (rw *responseStub) WriteHeader(statusCode int) {
}
```
Magic link code
```go
...
if config.Mailer.Autoconfirm {
	// signups are autoconfirmed, send magic link after signup
	if err := a.Signup(fakeResponse, r); err != nil {
		// TODO: handle error
		w.Write(nil)
	}
	newBodyContent := `{"email":"` + params.Email + `"}`
	r.Body = ioutil.NopCloser(strings.NewReader(newBodyContent))
	r.ContentLength = int64(len(newBodyContent))
	return a.MagicLink(fakeResponse, r)
}
// otherwise confirmation email already contains 'magic link'
if err := a.Signup(w, r); err != nil {
	// TODO: handle error
	w.Write(nil)
}

return sendJSON(w, http.StatusOK, make(map[string]string))
....
```
I'm not sure that this solution is "good". What do you think about that?

**Comment by awalias** [comment]
I think it's ok, If you want to make a PR I can test it out today 👍

**Comment by icecream78** [comment]
OK, I''ll try to do it today  =)

**Comment by awalias** [comment]
nice one @icecream78 !!
