### ISSUE TITLE
Add Ethereum login

### ISSUE THREAD

**Issue by chasers** [supabase/gotrue#242]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like to let my users log in with their Eth wallet (Metamask, etc)

## Describe the solution you'd like

Just like Uniswap does.

## Describe alternatives you've considered

Looks like [Redwood has an Eth login](https://github.com/oneclickdapp/ethereum-auth).

## Additional context

n/a

**Comment by HarryET** [comment]
I am not working on looking into this as a provider or a new method of authorizing. It may take some time while I investigate 😄

**Comment by J0** [comment]
[](https://github.com/supabase/gotrue/issues/258#issuecomment-1101921655)Hey all,

We plan on tracking all OAuth provider requests on https://github.com/supabase/gotrue/issues/451 so we'll be closing this issue in favor of the thread instead. Please feel free to follow along there instead.

Thanks!
