### ISSUE TITLE
supabase.auth.SignIn() for Third Party OAuth doesn't accepts Redirect URL option provided

### ISSUE THREAD

**Issue by spaceVStab** [supabase/gotrue#243]
## Description
I have been using Supabase since some time and loving it !! But I am trying to add Google OAuth to my application and facing issues with `redirectTo` option. Although I have mentioned the exact URL in `redirectTo` option, after Google OAuth Consent screen, the user is directed to **Site URL** configured in Supabase Dashboard.

I have provided the `redirectTo` value as:
```
supabase.auth.signIn( { provider:'google' }, { redirectTo:'https://khajaghar.stackmystore.com' } )
```

I have added the same exact URL to my **Additional Redirect URLs**

![image](https://user-images.githubusercontent.com/17889806/138118690-ab99cbde-3faa-4fe2-92ba-7e6c71f4195f.png)

### Actual Behavior
The site is always redirected to the Site URL irrespective of value provided in `redirectTo` option. Only if I change my **Site URL** to the value of redirectTo it works fine which makes `redirectTo` option redundant

### Expected behavior
Provided I have mentioned the exact address in Additional Redirect URL in Supabase Dashboard and the same address is being used in redirectTo value, the redirection should work as desired.

I am using following dependency versions:
```
"@supabase/gotrue-js": "^1.18.0"
"@supabase/supabase-js": "^1.24.0"
```

**Comment by spaceVStab** [comment]
I have attached my supabase dashboard setting which mentions both Site URL and Additional Redirect URLs. Both are configured.

**Comment by kaspnilsson** [comment]
I'm also dealing with this issue, @spaceVStab how did you resolve?
