### ISSUE TITLE
Restrict providers for given email domains

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/gotrue#246]
# Feature request

## Is your feature request related to a problem? Please describe.

#244 requests for SAML SSO support. Commonly, domains which are under SSO have all other sign-in options restricted, to only allow access via the SAML SSO. By restricting the providers available for signing in based on the user's domain name, SSO support would be considerably easier to integrate.

## Describe the solution you'd like

Potentially, a new table could be created which contains the domain name and the list of allowed providers for that domain. By default, all domains would be allowed to have sign-ins though any enabled provider, whereas if a domain is stored in the table, only the list of providers stored in the matching row would be allowed.

If a user logins via an existing provider, their email should then be checked against the list of restricted domains. If their domain is now restricted, and the provider they use now disallowed, they should be prompted to use a different provider, then have the restricted provider and provider ID be removed from their account on next login.

Note: I haven't considered how this would work with gotrue's SMS authentication.

## Describe alternatives you've considered

Without such a solution to restrict the list of providers for given domains, there doesn't seem to be a way to implement industry-standard SSO as users will be able to login through other providers with the same email address.

**Comment by awalias** [comment]
thanks @liaujianjie and @bnjmnt4n !

just to clarify what you're trying to achieve, you want the ability to write rules such as:

- @facebook.com emails can **only** log in with the facebook oauth provider
- @hootsuite.com emails can **only** log in with the google oauth provider

is that correct?

**Comment by liaujianjie** [comment]
Yes, that's right!

**Comment by liaujianjie** [comment]
Just wanted to add that I'm looking to integrate with WorkOS as for SAML SSO and SCIM.

With SCIM or other similar user-provisioning services/standards, we also need the ability to write even more specific rules such as:
- @foo-corp.com emails can **only** log in with Google OAuth provider if the user is in the `designers` Google group
- @bar-corp.com emails can **only** log in with Okta OAuth provider (via WorkOS) if the the user has already been provisioned the app

**Comment by J0** [comment]
Hey,

Just bumping this here. This thread has been inactive for a while so I would just like to highlight that we haven't forgotten about this issue and we are actively working on the WorkOS integration as well as SAML.

Thanks for your patience!
Joel

**Comment by J0** [comment]
Hey all! 

This should be resolved via #244 which @hf is actively working on. Feel free to follow along there -- going to close this issue for now but feel free to re-open if there are further concerns
