### ISSUE TITLE
verify endpoint improve error responses

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#25]
verify token endpoint currently returns User not found if the token has expired, should instead return token expired error

or if not going to be called via API, then can also redirect to something like `<SITE_URL>#error_description=token_expired`

**Comment by icecream78** [comment]
Hi. 
I looked through the source code of verify function and haven`t found any checks for confirmed token expiration. Do you need this type of check? Only thing that I`ve found, when no confirmation_token found in db and returned "User not found" error.
English is not my native language, so if it something was written not correct don`t blame me=)

**Comment by awalias** [comment]
you're correct @icecream78 , the only way to expire a confirmation token right now is to replace it with a more recent one
