### ISSUE TITLE
add SoundCloud OAuth Provider

### ISSUE THREAD

**Issue by stardvst** [supabase/gotrue#258]
# Feature request
Please add SoundCloud OAuth provider.

## Is your feature request related to a problem? Please describe.
To extend music streaming platform authentication.

## Additional context
https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by HarryET** [comment]
I can have a look!

**Comment by HarryET** [comment]
It appears that the SoundCloud API is similar to Netlify - #187 - in the way it dosen't have scopes meaning a Token grants access to all actions, this may need comment from @kiwicopple, @awalias or @kangmingtay.

**Comment by J0** [comment]
Hey all,

We plan on tracking all OAuth provider requests on #451  so we'll be closing this issue in favor of the thread instead. Please feel free to follow along there instead.

Thanks!
