### ISSUE TITLE
Remove `auth.instances`

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/gotrue#266]
# Chore

## Describe the chore

It doesn't seem like Supabase will ever make use of the original multi-tenant style GoTrue since each project has its own database provisioned. It might make sense to remove the `auth.instances` table and `instance_id` foreign key, which don't have any value.

**Comment by kangmingtay** [comment]
Hey @bnjmnt4n, we actually have some long-term plans for using that to allow users to implement multi-tenancy using gotrue 😅

**Comment by bnjmnt4n** [comment]
Cool, interested to see what that would look like. Will close this for now then!
