### ISSUE TITLE
Make audit log entries more detailed for logins

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/gotrue#267]
# Feature request

## Is your feature request related to a problem? Please describe.

The audit log entries for logins do not include details about the kind of login (provider).

## Describe the solution you'd like

The audit log entries for logins could be more detailed by including provider kind, and provider IDs.

**Comment by liaujianjie** [comment]
Alternatively, we could add a FK column that references `auth.identities` instead. That way we can query whatever identity information we need with a join, including provider.

**Comment by bnjmnt4n** [comment]
That's also fine, although I think there is value in making the audit log entries table self-contained (and avoiding any potential issues with referential integrity when identities are deleted).

**Comment by liaujianjie** [comment]
Oh right, the requirements for retaining audit logs definitely takes priority.

**Comment by bnjmnt4n** [comment]
Closed by https://github.com/supabase/gotrue/pull/373.
