### ISSUE TITLE
`auth.identities`: add index for `user_id` column

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/gotrue#268]
# Bug report

## Describe the bug

#208 introduced the `auth.identities` table with the following schema: https://github.com/supabase/gotrue/blob/13c53ec7f43329f587971bfa6644199adb5d9454/migrations/20210909172000_create_identities_table.up.sql.

Each new login with a new provider for an existing user will call the [`user.UpdateAppMetaDataProviders` function](https://github.com/supabase/gotrue/blob/62e7ccd13cd41cd5571f75c4baae5ac0fb187e7c/models/user.go#L221), which will look for [all identities with the specified `user_id`](https://github.com/supabase/gotrue/blob/06de2419be835f1c3760e5dcc90702b84dc4583b/models/identity.go#L74). Currently, this does a sequential scan on the whole table to find all such providers. It might be good to optimize this with an index on `user_id`.

**Comment by kangmingtay** [comment]
thanks for the feedback @bnjmnt4n, we've added it :)
