### ISSUE TITLE
Allow exception created by a user inside of a trigger function to bubble up when using signUp/signIn

### ISSUE THREAD

**Issue by silentworks** [supabase/gotrue#271]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be good if an exception created by a user inside of a Postgres Trigger function would bubble all the way up to the client code. Currently, I have created an exception but I keep on getting the same default "Database error saving new user" error although I know the signUp process is failing due to my exception. I would prefer to see the message from my exception here.

Another related issue is that the confirmation email is sent before the record gets inserted into the database, not sure why this happens, because by raising an exception the database normally rollback all transactions so the email being sent shouldn't happen before the transaction is completed and successful.

**Comment by chipilov** [comment]
I think there is a second, related issue here - if a BEFORE trigger modifies the record to be inserted into the table, the API still returns the data that was passed in the request, NOT the data which was actually saved in the auth.users table.

@kiwicopple Do you want a separate issue for that or can it be handled with this one?

**Comment by silentworks** [comment]
@chipilov that should be raised as a separate issue as it's not directly related to this one.

**Comment by chipilov** [comment]
> @chipilov that should be raised as a separate issue as it's not directly related to this one.

Ok, opened a separate issue: https://github.com/supabase/gotrue/issues/288
