### ISSUE TITLE
send account recovery email on repeated signup attempt

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#286]
following up in this issue we need to improve the UX for users who forget that they have an existing account:

https://github.com/supabase/supabase-js/issues/296

**Comment by bhvngt** [comment]
@awalias Any plans to implement sending magic link / recovery email for existing user signup? Currently, the DX is unwieldy, as I need to detect the existing user signup and then act accordingly

**Comment by J0** [comment]
Repeated Signups with the same email address should now return an error stating that the user has already signed up.

Additionally, we have introduced a [`resetPasswordForEmail` method](https://github.com/supabase/gotrue-js/blob/rc/src/GoTrueClient.ts#L690) which would allow a developer to detect repeat signups at the application level and send a reset password email as necessary

https://github.com/supabase/gotrue-js/blob/rc/src/GoTrueClient.ts#L690

Going to close for now but feel free to comment/reopen if there are unaddressed concerns

**Comment by bhvngt** [comment]
> Repeated Signups with the same email address should now return an error stating that the user has already signed up.

Thanks @J0. Is this change already rolled out or is it expected to roll out with a particular release of `supabase-js/gotrue-js/gotrue server`

**Comment by J0** [comment]
The change should be rolled out  in `supabase-js` for signups which make use of the `signUp` method. Is the change not working as expected on your end?

**Comment by bhvngt** [comment]
I have been using `supabase-js` [v2](https://github.com/supabase/supabase-js/releases/tag/v2.0.0-rc.10) with its latest `rc` release. In one of my test where I signup, confirm signup and then signup once again with the same email, instead of an error I get `faux user` record. 

I am testing this locally with the `gotrue` [v2.16.7](https://hub.docker.com/layers/supabase/gotrue/v2.16.7/images/sha256-d0e6e9b52dde8aed5a10ce2ce79e6cd4b0c99945852b653e70c213026ddcdcad?context=explore) docker image

**Comment by curtisbelt** [comment]
@J0 Emails are not sending again on the live Supabase platform, with latest supabase-js 1.35.7. Can you post the link to the releases note or PR which contains the fix that closed this issue? I cannot find it in https://github.com/supabase/supabase-js/releases.

**Comment by mb21** [comment]
> Repeated Signups with the same email address should now return an error stating that the user has already signed up.

This is only the case if you have autoconfirm enabled in your project config :( (see https://github.com/supabase/gotrue/blob/6c8a96e39190e1d499ab667fcd24bed2b2fa01c8/internal/api/signup.go#L252)

**Comment by doried-a-a** [comment]
Hello, I'm struggling with the same issue indeed. I'm building an app using Flutterflow + Supabase. 
Repeated sign up attempts are not resulting in sending recovery emails. Apparently, as @mb21 mentioned:

> This is only the case if you have autoconfirm enabled in your project

Well I don't want accounts to be auto-confirmed.
There is also no easy work-around to detect this case in the ui, where the developer could have prompted the user to use a magic link. Using the identities array (according to the thread) does not seem reliable and working in all cases but might be a good alternatives, given limited options.
