### ISSUE TITLE
Response from /signup request might NOT return the values that were actually stored in DB

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue#288]
# Bug report

## Describe the bug

When a BEFORE TRIGGER is applied to the data stored in the auth.users table, it's possible to modify some of the values of the new record BEFORE they are stored in the DB. For example, the NEW.raw_user_meta_data value might be changed to include custom values set by the server.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Define a BEFORE INSERT trigger on the auth.users table
2. In the trigger, modify the NEW.raw_user_meta_data value to contain a server-set value
3. Call the /signup REST method

## Actual behavior

The response from the signup call does NOT include the changes to the raw_user_meta_data field

## Expected behavior

The response from the signup call should include the changes to the raw_user_meta_data field

**Comment by J0** [comment]
Hey @chipilov,

Wanted to check in and see if this is still an issue for you.

Let us know!

**Comment by chipilov** [comment]
Hey @J0,

Currently, this is not a blocker for me because my workflow changed a bit since I opened the issue.

However, I think it would be great if you fixed it because I can still see use cases for it.

For example, if users sign up with a specific invite code, you might want the response to include data based on the invite code (e.g. the user might be eligible for a promotion) - it would be nice if you can get that data directly from the response of the ```/signup``` call instead of having to do a second call (after all, in my example the data is generated at the time of the ```/signup``` call so it even makes logical sense to do that, not just for network optimization).

**Comment by hf** [comment]
I've made a fix for this in #712. I'll close this issue and comments can proceed on the PR.
