### ISSUE TITLE
Allow defining extra search path for database actions triggered by auth-specific APIs (e.g. sign-up)

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue#293]
# Feature request

## Is your feature request related to a problem? Please describe.

Supabase currently allows to declare any extra schemas to search for in the ```Extra search path``` settings in the API settings.

However, this setting has NO effect on APIs that go through the GoTrue server (e.g. sign-in, sign-up, etc).

## Describe the solution you'd like

For consistency, I think it would be best if the ```Extra search path``` was always applied, regardless of the type of API (i.e. regardless of whether the API goes through PostgREST or GoTrue).

Alternatively, a second config could be exposed, which allows setting the extra search path only for auth-specific APIs.

## Describe alternatives you've considered

It seems that the only use-case for the extra search path for auth-specific APIs are triggers attached to tables that are modified by auth APIs (e.g. ```auth.users```).

It is possible that the trigger function itself defines the necessary extra search path in its definition as suggested here: https://github.com/supabase/supabase/issues/4037#issuecomment-981238111

**Comment by kangmingtay** [comment]
Hi @chipilov, we don't plan on adding the `auth` schema to the extra search path. This is because the `auth` schema is meant to be private and not accessible via postgrest. Anything auth related should go through GoTrue. 

Do you have a specific use-case in mind that cannot be executed via the admin endpoints in gotrue?

**Comment by chipilov** [comment]
HI @kangmingtay,

I think there is a misunderstanding here - this issue is NOT about adding the ```auth``` schema to the extra search path.

This issue is about the fact that the ```Extra search path``` field in the Supabase dashboard is ignored for any calls that go through the GoTrue server (as opposed to PostgREST), regardless of whether the ```auth``` schema is part of the ```Extra search path``` or not.

For example, I could create a ```private``` schema and add it to the ```Extra search path```. I can then define a trigger function in this private schema and attach this trigger function to a trigger on ```auth.users``` (Supabase docs suggest to avoid making any changes to the ```auth``` schema, hence the trigger function is NOT defined in the ```auth``` schema). However, in this scenario the ```Extra search path``` is still ignored, even though I do NOT need the ```auth``` schema to be in the search path - I just need the ```private``` schema to be in the search path.

I think this should be implemented at least for consistency if NOT for anything else, but since there is a relatively easy workaround (described by @kiwicopple here: https://github.com/supabase/supabase/issues/4037#issuecomment-981238111),  I am fine either way.

**Comment by kangmingtay** [comment]
Ah ok i see, thanks for clarifying @chipilov, wasn't aware of the other thread, the extra context helps! At the top of my head, i think the easiest way would be to change the `NAMESPACE` config to accept a comma-separated list. Not too sure if that maps to the `search_path` and will have to take a deeper look.

**Comment by kangmingtay** [comment]
btw @chipilov, does this problem exist if you use fully qualified names instead of unqualified ones in your trigger?

**Comment by chipilov** [comment]
If I use fully qualified names, then the trigger runs just fine - so from that point of view, you could say that using fully qualified name is a way to workaround the problem (just like specifying the search path in the trigger function definition also works around the issue).

Does this answer your question?

**Comment by kangmingtay** [comment]
yup it does, i wouldn't say its a workaround the problem, rather it's probably a better practice to use fully qualified names since its more explicit than having to remember declaring it in the search path. 

We'll still look to add this into dashboard for consistency sake because it's definitely misleading! Thanks for raising this issue up :)

**Comment by RyannGalea** [comment]
I'm trying to use a 'set_claim' function from a user sign-up to set an organisation_id, and I think this issue is related but still cannot get it to work with suggestions here. 

Using a function from this package:
https://github.com/supabase-community/supabase-custom-claims/blob/main/install.sql

& trying to use a trigger function like this on the auth.users or public.users INSERT after still gives the same result saying the function does not exist. But I can use the function in the SQL window.
```
begin
  -- Set claim
  select set_claim(new.id,'organisation_id',new.organisation_id);
  return new;
end;
```

**Comment by chipilov** [comment]
@RyannGalea A fully qualified name is the name of the function prepended by the schema where it is defined. For example, if you defined your ```set_claim``` function in a schema named ```private```, the fully qualified name would be ```private.set_claim```. Does that help?

**Comment by RyannGalea** [comment]
@chipilov I thought as much, just wanted to clarify.

Would that be an issue when trying to fire it during the signup() process?

**Comment by chipilov** [comment]
Hm, I thought that ```public``` is always on the path, but maybe I am wrong. If it's NOT in the path, then yes - I expect that calling ```SELECT public.set_claim()``` should resolve your issue.

One thing to clarify here is that you have 2 functions - ```public.set_claim``` AND the trigger function itself (you didn't specify its name in your example). Note, that in the code you have provided, you have set the search path ONLY on the definition of ```public.set_claim``` to include ```public```. If you don't want to call ```set_claims``` function from within your trigger using its fully-qualified name, you also need to specify the search path in the definition of the trigger function itself.

**Comment by hf** [comment]
Hey I'll be closing this issue as it's not a direct problem with GoTrue and there is already quite a bit of information in here on how to solve problems with triggers if you run into them.
