### ISSUE TITLE
Admin password length for password resets

### ISSUE THREAD

**Issue by SupaDavid** [supabase/gotrue#294]
You can reset passwords to a password of length zero. The guardrails which apply to the password creation do not seem to apply to resetting the password.

Specifically just the guardrail that prevents zero length passwords. A password length of 1 character is not allowed.

Passwords of length zero should not be possible

**Comment by kangmingtay** [comment]
Just tried, gotrue doesn't allow a user to update their password to an empty string of 0 length. See [here](https://github.com/supabase/gotrue/blob/master/api/user.go#L83-L91). However, we should make the error explicit because it appears as though an empty password is accepted.
