### ISSUE TITLE
Add ability to modify Additional Redirect URLs list programmatically

### ISSUE THREAD

**Issue by chenkie** [supabase/gotrue#296]
# Feature request

## Is your feature request related to a problem? Please describe.

Hi Supabase team 👋

One of the features of [CourseLift](https://courselift.com) is that authors can add custom domains. Their course pages can then resolve to their own domain.

To make this work in the semi-sorta-multi-tenant setup I've got using Supabase, I need to be able to modify the Additional Redirect URLs on the fly.

When an author adds a custom domain, I need to be able to send a request to Supabase to modify the Additional Redirect URLs list at that moment.

## Describe the solution you'd like

It would be awesome if Supabase could expose some kind of admin endpoint to modify the list. 

Since it's a comma-separated string, it might get dicey to modify and save it back (I wouldn't want to accidentally nuke the whole list) so bonus points if it there is some way to have individual Additional Redirect URL records instead of just a string.

## Describe alternatives you've considered

Within Supabase, simply modifying the list manually. But that obviously won't work long-term.

## Additional context

Thanks 🖖

**Comment by J0** [comment]
Hey,

Thanks for the feature request! This should now be possible with the [Supabase Admin API](https://github.com/supabase/supabase-admin-api#configs)

There's also a corresponding [blog post](https://supabase.com/blog/supabase-cli-v1-and-admin-api-beta)

> POST /config/gotrue - sets new config - params: { raw_contents: <string-of-file-contents>, restart_services : <bool> }

Going to close this for now but feel free to re-open if it doesn't resolve all issues
