### ISSUE TITLE
Generic OpenID Connect auth provider

### ISSUE THREAD

**Issue by lostinpatterns** [supabase/gotrue#299]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like to use a third-party OpenID Connect provider for auth that isn't currently among those that Supabase supports for login like Twitch, Gitlab, etc.

## Describe the solution you'd like

I'd like support for a generic OIDC provider whereby the various required URLs can be configured and a response from the UserInfo endpoint can be parsed from within my JavaScript project where I'm using supabase-js as opposed to gotrue.

## Additional context

The OIDC provider I'd like to use is not a popular one and wouldn't be used by other customers so it wouldn't make sense to add my specific provider to this project.

**Comment by mstade** [comment]
Additionally, if the OIDC provider supports discovery through `/.well-known/openid-configuration/` ([see spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig)) the configuration could be as simple as just setting the issuer root. Aside from making it simple to configure, it also lets the OIDC provider configuration to change independently of the supabase configuration.

**Comment by J0** [comment]
Hey! 

I'd like to check if anyone is actively working on this issue, would be keen to discuss and/or work on this.

**Comment by koba-ninkigumi** [comment]
These issues are essentially the same thing.

https://github.com/supabase/gotrue/issues/159
https://github.com/supabase/gotrue/issues/299

It is recommended that you keep one of them and close the others.

**Comment by koba-ninkigumi** [comment]
@J0 
> Hey!
> 
> I'd like to check if anyone is actively working on this issue, would be keen to discuss and/or work on this.

Currently, id_token, nonce, and provider are required parameters in the IdTokenGrant method of gotrue/token.go.

It would be better if either issuer or provider is specified here. (If both are specified, we need to discuss which one should be adopted.)

All you have to do is to specify the issuer parameter directly in the "oidc.NewProvider(ctx, issuer)" part of the getVerifier method in gotrue/token.go.

Once the backend is changed to accept issuer parameters, gotrue-js will also need to be changed to allow issuer parameters to be specified.

**Comment by J0** [comment]
Hey @koba-ninkigumi,

Makes sense, let's keep #159. Closing this issue in favor of #159 

Feel free to comment/reopen still has further concerns with respect to this issue. 

Thanks!
