### ISSUE TITLE
App needs to know that Password Recovery happening

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#30]
the password recovery flow logs the user in and redirects the user to <SITE_URL>#access_token..etc.

need to add a query param either inside gotrue server, to let the user's app know that it's a password recovery

**Comment by icecream78** [comment]
@awalias I suggest just pass to redirected query parameter type. That parameter is coming as required field in verify method. It this way it will be cleaner way. 
What do you think about that?

**Comment by awalias** [comment]
so we should make the response like:

<SITE_URL>#access_token.....&type=recovery

or 

<SITE_URL>#access_token.....&type=signup

?

I think this is a good idea 👍

**Comment by icecream78** [comment]
I planned cover both cases.
1-st response <SITE_URL>#access_token.....&type=recovery cover task description.
2-nd response <SITE_URL>#access_token.....&type=signup is side affect. User's app can handle or ignore it
