### ISSUE TITLE
Chore: update Github description to supabase.com

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/gotrue#303]
# Chore

## Describe the chore

update Github description  from [supabase.io](https://supabase.com) to [supabase.com](https://supabase.com)

<img width="1392" alt="Screen Shot 2021-12-16 at 3 24 58 PM" src="https://user-images.githubusercontent.com/70828596/146444104-74c4de67-7b87-4234-9358-26407084cf34.png">

**Comment by kangmingtay** [comment]
done! thanks for pointing this out
