### ISSUE TITLE
Add "disableSignUp" option for magic links

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue#311]
# Feature request

## Is your feature request related to a problem? Please describe.

A hotly debated topic :)

https://github.com/supabase/supabase/issues/1176#issuecomment-973894582

## Describe the solution you'd like

Add a `disableSignUp` option to the magic link endpoint. If this is `true` then the endpoint should _not_ create a new user.

**Comment by aantn** [comment]
Yes please!

**Comment by kiwicopple** [comment]
Or perhaps a clearer flag will be `createUser`?

eg: `supabase.auth.signIn({ email: 'me@example.com', createUser: false })`

**Comment by TechBoyy6** [comment]
is this achievable using Bash?
