### ISSUE TITLE
Reset password email auth token can be used multiple times

### ISSUE THREAD

**Issue by nuurcodes** [supabase/gotrue#319]
# Feature request

After resetting the password, the same auth token can be used to reset the users password multiple times. Is there an option to invalidate the token after it has been used once?

**Comment by kangmingtay** [comment]
hey @nuurcodes, are you still experiencing this issue? we actually do delete the recovery token after the password reset link is clicked. 

See [here](https://github.com/supabase/gotrue/blob/master/api/verify.go#L230-L232) and [here](https://github.com/supabase/gotrue/blob/master/models/user.go#L323-L326).
