### ISSUE TITLE
Token isn't refreshing when "Enable Email Signup" is disabled.

### ISSUE THREAD

**Issue by PaganMuffin** [supabase/gotrue#321]
# Bug report

## Describe the bug

Bug is appearing after disabling "Enable Email Signup" in dashboard.
I'm using Discord as provider for OAuth.
When supabase-js client is trying to refresh token in react-app instead of getting new token I'm getting this response:

HTTP Code 400 with body:
`{
  "code": 400,
  "msg": "Email logins are disabled"
}`

After enabling "Enable Email Signup" I'm getting token with response.

## To Reproduce

1. Setup via discord sign in
2. Disable "Enable Email Signup" in supabase dashboard
3. Sign in with discord in your app
4. Wait for request

## Expected behavior

Getting new token with request.

## System information

- Version of @supabase/supabase-js: 1.22.5

**Comment by J0** [comment]
Hey! 

Thanks for reporting this issue -- there seem to be a few issues related to OAuth providers and enabling signups. We're going to close this issue and manage it at #193 as there seem to be many overlapping ponits.

Feel to re-open if you have any urgent questions or concerns.

Thanks!
