### ISSUE TITLE
Add Foursquare/Swarm OAuth Provider

### ISSUE THREAD

**Issue by alaq** [supabase/gotrue#325]
# Feature request

## Is your feature request related to a problem? Please describe.

Would love to be able to authenticate users with Foursquare/Swarm

## Describe alternatives you've considered

Currently using [passport-foursquare](https://github.com/jaredhanson/passport-foursquare)

**Comment by J0** [comment]
Hey all,

We plan on tracking all OAuth provider requests on https://github.com/supabase/gotrue/issues/451 so we'll be closing this issue in favor of the thread instead. Please feel free to follow along there instead.

Thanks!
