### ISSUE TITLE
Email + password login not allowed due to email signup being disabled

### ISSUE THREAD

**Issue by TomasHubelbauer** [supabase/gotrue#330]
# Bug report

## Describe the bug

It is possible to sign up a new user using the `supabase.auth.signUp` method. Once they are signed up, disabling the below pictured option prevents other users from signing up to the service:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/6831144/147787314-a20d18b9-7657-43e8-8b9f-e47979ce6936.png">

This is great as it allows service administrators to keep the service open to a limited set of users. They may even choose to never open any option of external signup and only manually invite users through the dashboard.

However, with this option disabled, logging in of existing users ceases to work. Both in case of magic link and a password based token grant flow. The endpoint being called by supabase-js fails with a 400:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/6831144/147787404-749ed5b2-a371-497b-9aad-fd26b0ac5da6.png">

This response is the same for both magic link (endpoint is `auth/v1/magiclink`) and password based token auth (endpoint is `auth/v1/token?grant_type=password`).

## To Reproduce

1. Enable email signup in the dashboard
2. Call `supabase.auth.signUp({ email, password })` and click the verification link in the email
3. Disable email signup in the dashboard
4. Call `supabase.auth.signIn({ email, password })`
5. Observe a 400 non-OK response and `supabase.auth.user()` returning `null`
6. Enable email signup in the dashboard
7. Call `supabase.auth.signIn({ email, password })`
8. Observe a 200 OK response and `supabase.auth.user()` returning an authorized user object

## Expected behavior

User sign in should work regardless of the ability of new users to sign up. Site operators may choose to cease accepting registrations while still providing service to existing accounts.

## System information

- Version of supabase-js: 1.25.2

## Additional context

Related discussion: https://github.com/supabase/supabase/discussions/4296

This is the problematic line: https://github.com/supabase/gotrue/blob/fa4b7e6435d4e88b19575a5e8b681fd6e6ef1794/api/token.go#L174

I believe the fix might be to just yeet the whole condition, but I am not able to determine whether that might break something else? if anyone can confirm this condition can be safely removed without any adverse effects, I will be more than happy to PR.

I opened the issue here as from the PoV of the Supabase user this is the SDK misbehaving, but an argument could be made this is an issue better suited for supabase/gotrue, so please move it as appropriate.

**Comment by TomasHubelbauer** [comment]
Related: netlify/gotrue#315. (I have asked folks at the upstream to see if they'd spare a moment and see if the change I proposed in the associated PR is safe and free of unintended consequences).

**Comment by kangmingtay** [comment]
Closing since it's related to #190

**Comment by TomasHubelbauer** [comment]
@kangmingtay let me answer your question from the referenced issue here as it relates to this issue specifically. You asked me what the use case is for enabling email sign in but not email sign up. I've provided an example in the original issue description but I'm happy to expand.

Imagine you're working on an application that's meant for a limited audience, like an internal tool for a company or an invite only site. In this scenario, it is desirable to seed the database with the allowed users by hand or to temporarily allow sign ups and have everyone make their account normally, then review the accounts in the database and close sign ups. From this point on sign ins should still work so existing users can use the site, but new sign ups should be closed so no uninvited people can join and no malicious actors can disrupt the service by finding a way to make an account.

This is a real world use case I'm hoping to solve by having the sign up and sign in logic split as suggested in my original issue description. I ask that you reconsider closing this issue or at the very least please offer a suggestion for an alternative. One thing that comes to my mind is that there probably is a way to use Postgres RLS to effectively prevent sign ups somehow once the service administrator decides that's what they want to do. However, I'm less keen on doing it this way because it seems more error prone. A mistake in such a policy means an attacker can join the site and exfiltrate data. Shutting down email sign ups at "Supabase level" seems much more solid and final.

I believe this ask while niche is useful enough to be reconsidered. It is an essential kit of functionality for any internal or invite based community website.
