### ISSUE TITLE
New OAuth Provider: Sign-in with Singpass

### ISSUE THREAD

**Issue by kangmingtay** [supabase/gotrue#340]
# Feature request
* Sign-in with Singpass 
* https://api.singpass.gov.sg/library/identiface/developers/backend-oauth2-jws

**Comment by J0** [comment]
@kangmingtay was on the supabase hangout with @thorwebdev and @awalias and I think we might want to hold off since the Gov might move to use [SGID](https://www.id.gov.sg/)

**Comment by J0** [comment]
Hey all,

We plan on tracking all OAuth provider requests on https://github.com/supabase/gotrue/issues/451 so we'll be closing this issue in favor of the thread instead. Please feel free to follow along there instead.

Thanks!
