### ISSUE TITLE
Adding Global.Id as OAuth Provider

### ISSUE THREAD

**Issue by Flajt** [supabase/gotrue#350]
# Feature request
Would it be possible to add global.id as OAuth Provider?
[Link to homepage](https://global.id)
[Link to docs](https://developer.global.id/documentation/index.html)

## Is your feature request related to a problem? Please describe.
Letting users in with a privacy-friendly OAuth Provider while accessing/verifying user data in a privacy-friendly manner if required.
For (at least currently) no cost.

## Describe the solution you'd like

Adding global.id as sign-in/up option and storing requested data in the user metadata.

## Describe alternatives you've considered

Didn't really find a good alternative to this provider.

## Additional context

I would like to implement that but I have never used go before, nor do I have a clue on how to integrate it in the existing codebase.
Also, the global.id docs are somewhat odd and I've never really dealt with implementing OAuth.
Maybe it can be done similar to using Auth0 but instead, use global.id but idk. [Article about Supabase with Auth0](https://supabase.com/docs/guides/integrations/auth0)

**Comment by J0** [comment]
Hey all,

We plan on tracking all OAuth provider requests on https://github.com/supabase/gotrue/issues/451 so we'll be closing this issue in favor of the thread instead. Please feel free to follow along there instead.

Thanks!
