### ISSUE TITLE
Add twitter as a provider

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#36]

**Comment by Eduardogbg** [comment]
I can create a PR for this, if it is of interest

**Comment by awalias** [comment]
would be amazing @Eduardogbg !

**Comment by awalias** [comment]
I started work on this but found that twitter doesn't use oauth 2.0 for accessing the user's email address:

![image](https://user-images.githubusercontent.com/458736/110804321-089e0100-82bb-11eb-8f2b-a7e832a71c2f.png)
from [here](https://developer.twitter.com/en/docs/authentication/overview)

the flow is therefore different to what we use for the other providers: https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

so I'm not sure how relevant methods like 

```go
p.Exchange(oauth2.NoContext, code)
```

are in this approach

**Comment by Eduardogbg** [comment]
Cool, I'll look into it!

**Comment by Eduardogbg** [comment]
@awalias it seems like the OAuth 2 protocol is fundamentally different from the OAuth 1.0 and as so I don't think we'll be able to reuse much from the OAuth providers code. If I can create an external dependency on a OAuth 1.0 library it would be easier, but I also understand if that's not preferred.

Also, I'm afraid some of the interfaces named OAuth could be confusing, as they wouldn't be satisfied for the OAuth 1.0 providers. That can be solved either by refactoring them to more generic ones (but I'm not sure that's either possible or good idea) or by renaming them to be OAuth 2 specific.

**Comment by awalias** [comment]
> If I can create an external dependency on a OAuth 1.0 library it would be easier
I'm happy to proceed on the basis of ease of implementation, we can optimize later if needed

> I'm afraid some of the interfaces named OAuth could be confusing
perhaps we can use `TwitterOAuth` or `OAuth1_0a` for anything twitter specific. And can always refactor if we require other OAuth 1.0 providers ?

**Comment by dbredvick** [comment]
Would love to have Twitter as an option for auth. Looks like the NextAuth folks had to go with OAuth 1.0A https://github.com/nextauthjs/next-auth/blob/main/src/providers/twitter.js

**Comment by awalias** [comment]
might be useful: https://github.com/markbates/goth/blob/19c3059c9ed44995940c8222a8eda10f6b604e01/examples/main.go#L75

**Comment by awalias** [comment]
some initial work here: https://github.com/supabase/gotrue/pull/96

**Comment by awalias** [comment]
previous PR superseded by https://github.com/supabase/gotrue/pull/95

**Comment by awalias** [comment]
fixed by #98 

will be available in supabase dashboard for new projects this evening

for existing projects it will be shipped tomorrow
