### ISSUE TITLE
Return Discord discriminator in user_metadata

### ISSUE THREAD

**Issue by itsnewtjam** [supabase/gotrue#377]
# Feature request

## Is your feature request related to a problem? Please describe.

The discriminator is needed with the username to visually identify Discord users. I see that it's already made available in the struct [here](https://github.com/supabase/gotrue/blob/c507d091724e51b4ae5a228ee6be71c03cc76b0d/api/provider/discord.go#L24), and even referenced [here](https://github.com/supabase/gotrue/blob/c507d091724e51b4ae5a228ee6be71c03cc76b0d/api/provider/discord.go#L83), it's just [not included in the `user_metadata`](https://github.com/supabase/gotrue/blob/c507d091724e51b4ae5a228ee6be71c03cc76b0d/api/provider/discord.go#L95-L107).

## Describe the solution you'd like

I'm not sure if it makes sense to create a new property in `user_metadata` as a generic solution for other providers, but just modifying Discord's `name` field to include the discriminator could suffice (would just mean if you only want the username, you would have to split the string on the front-end). 
```
user_metadata: {
  name: "username#1234"
}
```

## Describe alternatives you've considered

I'm sure you could use the Discord ID that is already returned to fetch the user's discriminator, but that's unnecessary when the OAuth is already providing it.

**Comment by kangmingtay** [comment]
hi @itsnewtjam, let's add it to the name field and leave it to the users to split it if they want to retrieve the discriminator - that way, we won't need to include a specific discord term in the generic oauth interface.
