### ISSUE TITLE
Whether issues related to oidc should be closed or not

### ISSUE THREAD

**Issue by koba-ninkigumi** [supabase/gotrue#378]
# Chore

## Describe the chore

https://github.com/supabase/gotrue-js/pull/207
https://github.com/supabase/gotrue/pull/360

With the above two PRs merged, I believe the following issue has already been resolved.
Does anyone think it should not be closed yet?

@J0 @kangmingtay @awalias @kiwicopple 

https://github.com/supabase/gotrue/issues/94
https://github.com/supabase/gotrue/issues/146
closed https://github.com/supabase/gotrue/issues/159
https://github.com/supabase/gotrue/issues/171
https://github.com/supabase/gotrue/issues/292
closed https://github.com/supabase/gotrue/issues/299
https://github.com/supabase/gotrue/issues/341
https://github.com/supabase/gotrue-js/issues/169

## Additional context

Add any other context or screenshots that help clarify the task.

**Comment by kangmingtay** [comment]
#341, #292, #94 aren't directly solved by this PR. It seems like a good alternative for now but will need to investigate further before concluding.

Gonna close this issue for now since it's more of a consolidation of issues to be closed rather than an actual issue.
