### ISSUE TITLE
Send a human-readable hash / slug instead of an email OTP

### ISSUE THREAD

**Issue by kangmingtay** [supabase/gotrue#383]
# Feature request
* Currently, the email otp sent isn't very user friendly. A better option would be to send a human readable hash instead of a randomly generated string.

**Comment by liaujianjie** [comment]
Is this already fixed by #446?

**Comment by kangmingtay** [comment]
@liaujianjie we've made it such that the email otp returned is more user-friendly but not a human-readable hash yet.

Also, `gotrue-js` supports email otp now with [verifyOTP](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L274) and [VerifyOTPParams](https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L191-L203) !

**Comment by J0** [comment]
Hey! Going to close this now as @kangmingtay has kindly modified the  OTP to return 6-10 digits. We might revisit in the future but probably won't be looking at this anytime soon.
