### ISSUE TITLE
Always redirect back to user site for recovery/magic link

### ISSUE THREAD

**Issue by thorwebdev** [supabase/gotrue#39]
# Feature request

Currently, if a recovery/magic link is expired, supabase will show a json error which is not a good user experience. Rather we should redirect back to the merchant site with an `error_description` URL param maybe?

## Additional context

![image](https://user-images.githubusercontent.com/5748289/99221969-95a8e000-281c-11eb-9ec6-226d9d040951.png)

**Comment by icecream78** [comment]
@awalias is this good enough improvement according to UX?

**Comment by awalias** [comment]
perhaps we should have `<USER-SITE>#auth_error_code=404&auth_error_message=user%20not%20found` as the query params, just because some webs apps may already use the `error-XXX` query param

but yes agreed that we should redirect back to user site :+1: nice suggestion @thorwebdev

**Comment by awalias** [comment]
closing this but noting that still need to solve for signup: https://github.com/supabase/supabase/issues/504
