### ISSUE TITLE
PUT /user should allow update of phone field 

### ISSUE THREAD

**Issue by kangmingtay** [supabase/gotrue#390]
# Bug report
* Currently, the `PUT /user` endpoint doesn't allow a user to update the phone field.

# Solution
* The `PUT /user` endpoint should update the phone field and also trigger sending out an OTP to verify the phone number used. 
* If `GOTRUE_SMS_AUTOCONFIRM` is enabled, then the `PUT /user` endpoint should update the phone field without sending out an OTP.

**Comment by akshayindianpix** [comment]
After registered with email and password, wanted to update phone in same account but it update as secondary number i.e new_phone field in user auth. Help me to update number as primary i.e phone field in User Auth.

**Comment by kangmingtay** [comment]
@shawnmclean are you self-hosting gotrue or using supabase? if you're self-hosting, then `GOTRUE_SMS_AUTOCONFIRM=true` should be set in the `.env` file of the root dir that gotrue is built in
