### ISSUE TITLE
Feature: Custom IDs when creating new users

### ISSUE THREAD

**Issue by iamclaytonray** [supabase/gotrue#411]
# Feature request

## Is your feature request related to a problem? Please describe.
It's a problem I have but I'm not sure it's applicable to most people. I use Supabase as a "SaaS" tool. Meaning, I use Supabase for auth and a chat service. We are planning to add more services on top of Supabase, such as a notification (in-app) service and any other realtime services we'll need in the future.

Our stack consists of Prisma + Node + GraphQL on the backend, and Supabase as described above. Because Supabase is a service-only thing for us, there's one minor flaw between Prisma + Suapbase; IDs. In our Prisma `users` table, we of course have an `id` column, which is UUID v4 and auto-generated, as you'd expect. On the Supabase side, we also have a `users` table with the same `id` column. However, it's currently not possible to dictate the ID of a new user when we create them. This leads to an extra column in both databases; `supabaseId` in our Prisma database and `prismaId` in our Supabase database. We need this because when we fetch conversations, we need to determine if a conversation already exists with both the currently logged in user and the user of the listing the logged in user is trying to communicate with. When we fetch conversations from Supabase, it has the supabase user id (what supabase generates) but we have to verify that's our internal user's `id` to prevent obvious bugs.

## Describe the solution you'd like
When creating the user, I would like to determine the `id` of the user instead of Supabase. Essentially:

```ts
const user = await prisma.users.create({ ... })
await supabase.auth.signUp(email, user.id);
```

## Describe alternatives you've considered
See above for the implementation I did. I couldn't think of a better way to handle this use-case.

## Additional context
N/A

**Comment by iamclaytonray** [comment]
@kangmingtay - i see the issue was transferred but not where it was transferred. Mind dropping a link so I can follow along?

**Comment by iamclaytonray** [comment]
Pinging this again. Where can I go to follow the progress on this?

**Comment by kangmingtay** [comment]
@iamclaytonray its already been transferred to the gotrue repo which is where it will be tracked. 

Also, could you please explain why creating an additional table that maps the prisma user id and the supabase user id doesn't work for you? It also helps to have an additional layer of abstraction to reduce potential breaking changes.

**Comment by J0** [comment]
Hey @iamclaytonray can we check if this is still an issue for you?

Let us know!

**Comment by hf** [comment]
@iamclaytonray GoTrue can't support externally generated UUIDs. There are many good reasons why this is the case. A major one is avoiding [Insecure Direct Object Reference](https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html) security issues. 

[You can add metadata to the user's profile using the `data` property of the `signUp` function.](https://supabase.com/docs/reference/javascript/auth-signup)
