### ISSUE TITLE
Add metadata on passwordless phone signup

### ISSUE THREAD

**Issue by maxcodefaster** [supabase/gotrue#416]
# Feature request
Similar to email signup it would be good to pass meta data on phone signup (without password) to allow for example to pass usernames.

## Describe the solution you'd like

Allow meta data on passwordless phone signup.

## Additional context

To add usernames to users, a valid approach is to create a profile entry with a trigger on signup. This works for email signups, but there is not way to do this with passwordless phone signup. Setting usernames on runtime can cause issues, as any savy user can just mitigate username creation alerts.

**Comment by wernst** [comment]
+1 for this
