### ISSUE TITLE
Feature request: Add Steam as an external OAuth provider

### ISSUE THREAD

**Issue by law-lin** [supabase/gotrue#417]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, Supabase does not support Steam as an external OAuth provider.

## Describe the solution you'd like

Support Steam as an external OAuth Provider. https://partner.steamgames.com/doc/features/auth

## Describe alternatives you've considered

N/A

## Additional context

This [article](https://owlspace.xyz/cybersec/steam-login/) describes how Steam's login method works.

**Comment by J0** [comment]
Hey all,

We're going to track all provider requests on #451 so we'll be closing this issue for now -- feel free to follow along there instead.
