### ISSUE TITLE
Disable users

### ISSUE THREAD

**Issue by Deliana90** [supabase/gotrue#420]
![Screenshot from 2022-03-11 12-51-39](https://user-images.githubusercontent.com/96174573/157810803-a26505d5-6a84-4475-a929-2a06daf5d397.png)

with firebase we can disable users,
https://firebase.google.com/docs/auth/admin/manage-users?hl=en&authuser=0#update_a_user

**Comment by liaujianjie** [comment]
Dropping in a potential use-case for this feature request:

Some IdPs support users states where we may want to disable the user account. For example, [Okta](https://developer.okta.com/docs/reference/api/users/#user-properties) has these states: `STAGED`, `PROVISIONED`, `ACTIVE`, `RECOVERY`, `LOCKED_OUT`, `PASSWORD_EXPIRED`, `SUSPENDED`, or `DEPROVISIONED`.

**Comment by kangmingtay** [comment]
hey @Deliana90, you can disable a user via the `/admin` endpoint - see https://github.com/supabase/gotrue#post-put-adminusersuser_id

**Comment by J0** [comment]
Hey,

Going to close this issue for now. Do feel free to reopen/let us know if there are still any remaining concerns.

Thanks!
