### ISSUE TITLE
Keycloak Auth - Unable to exchange external code

### ISSUE THREAD

**Issue by 108174** [supabase/gotrue#440]
Hi, 

Apologies for the long post.

I am having the same issue with other providers, (e.g. azure). Today I was glad to see Keycloak in the supported providers (much appreciated!). The issue is the same as written before in this issue: [#106](https://github.com/supabase/gotrue/issues/106)

![image](https://user-images.githubusercontent.com/10290865/161862584-551d00fe-2a3e-499f-a568-d993227c26ed.png)

Upon inspecting the state on jwt.io

![image](https://user-images.githubusercontent.com/10290865/161862648-196901e9-0dd8-4a0e-aa65-68454b58e51a.png)

Perhaps the fact that the id is set to 00000000-0000-0000-0000-000000000000 is a clue

After entering my user credentials I am being redirected to the frontend

![image](https://user-images.githubusercontent.com/10290865/161863101-21951e85-5f0f-48b6-a31b-8096d5850874.png)

The response headers from the Keycloak endpoint do contain valid JWT tokens, with email and user-id, Albeit inside cookie headers.

![image](https://user-images.githubusercontent.com/10290865/161862948-faab10a0-86d5-4d0c-bc26-431e8bc7820c.png)

The final redirection is to the redirect endpoint,

https://myprojectid.supabase.co/auth/v1/callback?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDkxOTg4MjAsInNpdGVfdXJsIjoiaHR0cHM6Ly92aGMuaXEtbW90aXZlLmNvbS8iLCJpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIm5ldGxpZnlfaWQiOiIiLCJmdW5jdGlvbl9ob29rcyI6bnVsbCwicHJvdmlkZXIiOiJrZXljbG9hayIsInJlZmVycmVyIjoiaHR0cHM6Ly92aGMuaXEtbW90aXZlLmNvbS8ifQ.CkUcJ0GTqpteEoQynTmywg9OMWOkpqgcTDXq7s0I338&session_state=cbb586d9-6fcf-454a-9f32-5479dc78c9f4&code=789d6ba4-85e8-4671-a9a1-f46012e3e696.cbb586d9-6fcf-454a-9f32-5479dc78c9f4.223ea6fc-1d5e-4f50-9a66-1a096bff98c8

This last redirect has the following response header:

location: https://mypublicurl.com/?error=server_error&error_description=Unable+to+exchange+external+code%3A+789d6ba4-85e8-4671-a9a1-f46012e3e696.cbb586d9-6fcf-454a-9f32-5479dc78c9f4.223ea6fc-1d5e-4f50-9a66-1a096bff98c8

```
error: server_error
error_description: Unable to exchange external code: <CODE>
```

The client id and secret are correctly entered, the sign-in also leaves a cookie around for other apps, and those are logged in after this session.

**Comment by kangmingtay** [comment]
Hi @108174, based on your project logs, it seems like gotrue is returning an error from keycloak with the following message: `x509: certificate signed by unknown authority` - have you taken a look at [our guide](https://supabase.com/docs/guides/auth/auth-keycloak) for setting up the keycloak provider?

**Comment by 108174** [comment]
Yes I have, to the letter

**Comment by 108174** [comment]
Upon further inspection, I have used this docker image: ```quay.io/keycloak/keycloak:latest```

instead of ```jboss/keycloak:latest```.

As this was the listed image on the official keycloak website. Well, the images are identical (```docker history --no-trunc jboss/keycloak```). Seems to be mirrored.

Could it have something to do with my SSL certificate?

**Comment by valerius21** [comment]
I am having the same issue. I've detailed the steps to reproduce it here: https://github.com/supabase/supabase/issues/7362

**Comment by koakh** [comment]
I have the same problem using [app.supabase.com](https://github.com/supabase/gotrue/issues/app.supabase.com)

redirect url with failure "Unable to exchange external code"

```
http://localhost:3000/?error=server_error&error_description=Unable+to+exchange+external+code%3A+a95bcaef-bb46-4c04-9ec6-2a81877a68f0.be71884e-2598-4dea-9d0f-61766b30e403.dfae8b4b-e82d-466c-ac57-d112d9b92d7c
```

I try many things but I don't a clue how to override this problem

I post here too [#516](https://github.com/supabase/gotrue/issues/516)

**Comment by wiwatsrt** [comment]
I have the same problem using Self Hosting

Fixed 

I added 
`EXTERNAL_KEYCLOAK_URL= http://host.docker.internal:8080/realms/supabase`
to .env and this to /etc/hosts
`127.0.0.1 host.docker.internal`

**Comment by hf** [comment]
Hey there is a common issue with Keycloak and leading space characters, as described in this discussion: https://github.com/supabase/supabase/discussions/1192#discussioncomment-848941

**Comment by J0** [comment]
Hey  @108174,

Thanks for your patience. Can I check if this is still an active issue after checking for leading spaces and special characters?

Let us know!
Jo

**Comment by J0** [comment]
Hey,

I'm going to close this issue for now as it seems to have gone stale but feel free to let us know if there are still remaining issues.

Thanks!
Jo
