### ISSUE TITLE
Discord discriminator base length isn't respected if it's #0999 or less.

### ISSUE THREAD

**Issue by PhaxeNor** [supabase/gotrue#442]
# Bug report

## Describe the bug

If you have a Discord discriminator that is `#0999` or lower, the metadata stored doesn't respect the 4 int/string length and will show up as `#999`. In my case it just shows up as `#1`.

## To Reproduce

1. Have a Discord account that has a discriminator no higher than `#0999`
2. Sign in using Discord as the provider
3. Check the user metadata, it should only show `{username}#999` or the respective discriminator.

## Expected behavior

Discriminator base length should be respected and show `{username}#0999` so that it contains the correct information for the user.

## Screenshots

I changed my discriminator for this one to be in line with what's written above.
![Screenshot 2022-04-08 at 00 35 04](https://user-images.githubusercontent.com/323222/162330715-64288117-ce21-46b5-bd0a-72361165eb31.png)

## System information

- OS: macOS
- Version of supabase-js: 1.33.3
- Version of Node.js: v16.14.2

## Additional
Looking at the `discord.go` file, I believe the Discriminator should be a string and not int, as that's what Discord is providing via the API.
But I'm not familiar with Go, so not sure what the *standards* are.

**Comment by bariqhibat** [comment]
Hi @kangmingtay @J0, can I take on this issue? Thanks

**Comment by J0** [comment]
Hey @bariqhibat,

Yup feel free to go for it!
