### ISSUE TITLE
The OTP generated and verified, either via mail, sms or third party authenticator should be HMAC based TOTP  

### ISSUE THREAD

**Issue by rnbokade** [supabase/gotrue#443]
I came to know about Supabase while I worked on developing Passwordless authentication backend for one for my client. I used @pyauth 's [PyOtp](https://github.com/pyauth/pyotp) for generating time based OTP's, which basically depended on a randomly generated string and current time for the random OTP. This method is as per [rfc6238](https://datatracker.ietf.org/doc/html/rfc6238). So instead of storing randomly generated otp in the database, we store the random string. Then During verification, we instantiate, the object with same store key, now if the otp being verified is being verified within valid amount of time, it will be valid, but if it isn't then it will be invalid. This will also make the workflow for MFA using third party TOTP authenticators like Google Authenticator and Microsoft Authenticator easier to integrate.

**Comment by J0** [comment]
Hey @rnbokade,

Thanks for highlighting this— we’re hoping to use TOTP for MFA and will eventually aim to incorporate TOTP into the OTP flow. We will take this into consideration as we build out MFA support. 

Going to close this now but feel free to post any concerns [on the MFA thread](https://github.com/supabase/gotrue/issues/14)

Thanks!
