### ISSUE TITLE
Unfork this repo and update README

### ISSUE THREAD

**Issue by lukecyca** [supabase/gotrue#444]
# Improve documentation

## Describe the problem

Currently this project is a "fork" of the netlify version, but it has diverged so much that it more of a standalone project now. It is cumbersome for a number of reasons:
* The README still documents netlify's version (e.x. it says the database driver "Must be mysql", etc.)
* New features of this fork are not documented on the README
* By sharing the "gotrue" name, it's hard to search the internet for other resources and know whether they're talking about this fork or the original
* Gitlab doesn't allow searching this repo's code

## Describe the improvement

* Unfork this repo
* Change the name of the project slightly (I propose "gotruman")
* Update the README to reflect this project

**Comment by J0** [comment]
Relevant RFC: https://github.com/supabase/rfcs/pull/2

**Comment by J0** [comment]
Hey! 

Thanks for the request. Unfortunately, we're a little swamped with the rest of the features we're working on(e.g. SAML, MFA, Multi-tenancy and more). We're going to close this for now but will revisit the issue when a slot frees up.

Appreciate your understanding on this!
