### ISSUE TITLE
Missing 00-init-schema migration

### ISSUE THREAD

**Issue by claudioquaglia** [supabase/gotrue#452]
# Bug report

## Describe the bug

When trying to start a GoTrue instance with an external database the first migration `00_init_auth_schema.up.sql` fails because the `auth` schema is not defined. In the supabase documentation and repo a volume is mounted with a sql script `00-initial-schema.sql` responsible for creating the user `supabase_admin`, roles and extensions. While the first script `01-auth-schema.sql` has as its first instruction the creation of the `auth` schema. It might be useful to bring it into the GoTrue repo as well to allow instances to be launched without manual intervention.

## Expected behavior

Migrations should have everything needed.

**Comment by bariqhibat** [comment]
Hi @claudioquaglia, does it mean we'd just need to add a line to create the schema if it doesn't exists in your local?

**Comment by claudioquaglia** [comment]
Hi @bariqhibat yup like it's done [here](https://github.com/supabase/supabase/blob/9db54c2269f5ceaba7588a823bbdac42b18ce06b/docker/volumes/db/init/01-auth-schema.sql#L2). Btw I think it's needed an initial migration like is done [here](https://github.com/supabase/supabase/blob/master/docker/volumes/db/init/00-initial-schema.sql) to create the user as well and enable needed extensions. This allow to have a full up and running instance without need to run scripts.

**Comment by J0** [comment]
Hey all,

Apologies on the confusion -- going to go ahead and close this issue for now.

Going to close the issue as per: https://github.com/supabase/gotrue/pull/458#issuecomment-1111585758

As documentation improves hopefully this will be less of an issue. Feel free to reopen if you have any questions/concerns though.

Thanks!
