### ISSUE TITLE
Telegram as an Auth Provider

### ISSUE THREAD

**Issue by Mi3liX9** [supabase/gotrue#464]
# Feature request
AS there are many people who use Telegram and in the last update 8.7 they provide Web Bots, a way to open web apps inside Telegram. I suggest supporting Telegram as an Auth Provider

## Links
https://core.telegram.org/widgets/login
https://core.telegram.org/bots/api#telegram-passport
https://core.telegram.org/bots/webapps

**Comment by kangmingtay** [comment]
merged into megathread (https://github.com/supabase/gotrue/issues/451#issuecomment-1102082954)
