### ISSUE TITLE
Auth token gap between token refresh

### ISSUE THREAD

**Issue by Skil3e** [supabase/gotrue#467]
# Bug report

Not sure what is happening but it seems like there is a time gap between the token refresh of a logged in user. I am getting a couple of minutes of "JWT expired" error then everithing returns to normal.

## To Reproduce

Not sure.

## Expected behavior

User should persist without errors.

## System information

create-react-app

**Comment by kangmingtay** [comment]
Hey @Skil3e, will be closing this issue since I can't seem to reproduce it at this point.
