### ISSUE TITLE
Improve `/logout` speed

### ISSUE THREAD

**Issue by thorwebdev** [supabase/gotrue#47]
# Chore

## Describe the chore

The `supabase.auth.logout()` function takes consistently more than 2 seconds to resolve. Is there anything we can do to speed this up? It's a bit awkward for that much delay after hitting the signout button.

## Additional context
Tested here: https://nextjs-subscription-payments-starter.vercel.app/
![image](https://user-images.githubusercontent.com/5748289/100179873-dcc85c80-2f11-11eb-88b3-5ce181a86fda.png)

**Comment by icecream78** [comment]
Somewhy mysql don't use index while logout. 
![image](https://user-images.githubusercontent.com/20445149/100192273-b2bb6e00-2f02-11eb-835a-9ebe069ecaca.png)
I'll try figure out how to tune perfomance of this query, but I'm not PRO in stuff like this and will take some time=)

**Comment by J0** [comment]
Should be resolved by [the move to sessions](https://github.com/supabase/gotrue/pull/600/files) and the change in the underlying query to  make use of the sessions model rather than refresh tokens. Going to close for now but feel free to re-open if issue persists.

cc: @kangmingtay
