### ISSUE TITLE
Use query params instead of fragments for callback

### ISSUE THREAD

**Issue by jackmerrill** [supabase/gotrue#472]
# Feature request

## Is your feature request related to a problem? Please describe.

Using a Go backend (with [supabase-go](https://github.com/nedpals/supabase-go)), I can't access the `#` fragment that holds the access token on successful authentication. The [server can't access the fragment](https://stackoverflow.com/questions/25489843/http-server-get-url-fragment).

## Describe the solution you'd like

Change the callback function back* to using query params, or allow the client to select which they'd like (likely unnecessary)

\* This seems like this was changed in #16, could be worth reverting again.

## Describe alternatives you've considered

There are no possible alternatives in my case, as I want to use little to no JavaScript for my authentication (and use cookies, etc)

## Additional context

N/A

**Comment by J0** [comment]
Hey @jackmerrill,

We originally switched to params but realised that it might not be as secure as # because params are sent to the server and can be modified in transit so we switched it back

We're looking into a stable and secure server side auth flow and will keep you posted this issue once out.

Thanks!

**Comment by jackmerrill** [comment]
> Hey @jackmerrill,
> 
> We originally switched to params but realised that it might not be as secure as # because params are sent to the server and can be modified in transit so we switched it back
> 
> We're looking into a stable and secure server side auth flow and will keep you posted this issue once out.
> 
> Thanks!

Yeah, I saw #279, hoping it gets fixed soon! Thanks though!

**Comment by superjose** [comment]
I think we can solve this by using the exact mechanism as webhooks; we verify the header with a signature and a key. 

It would be very convenient not to send any unnecessary JavaScript to the client, even for JavaScript fullstack apps (like Remix).
