### ISSUE TITLE
Server panics when operating in multi-instance mode

### ISSUE THREAD

**Issue by pratheekrebala** [supabase/gotrue#474]
# Bug report

When running the server under multi-tenancy using `gotrue multi` all requests to the server fail with a nil reference panic. This is most likely occurring here:

https://github.com/supabase/gotrue/blob/8689fd206f2c5d678880c2254ddf85b53fa22485/api/middleware.go#L97-L101

The panic is triggered because in this case, config is always null because the `withInstanceConfig` method (which updates the config) isn't called until the end of the function here:

https://github.com/supabase/gotrue/blob/8689fd206f2c5d678880c2254ddf85b53fa22485/api/middleware.go#L137

This is kind of a chicken or egg problem in acquiring the instance specific JWT Token. In the Netlify version of the service, the operator token is used to verify the JWS, which is non-ideal since the my understanding is that he client is supposed to posses this token.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run the server in multi-tenancy mode using: `gotrue multi`
3. Create an instance by sending a POST request to the `/settings` endpoint.
4. Send a request to the API using a signature in the `x-nf-sign` header with the following claims: `{
  "site_url": "https://example.netlify.com",
  "netlify_id": "2c2db737-649f-4572-9740-e8691d57806a",
  "id": "db6a5e12-c314-4b6b-8f35-d87709cdf32c"
}`
5. The server will now panic when the `config` variable (which is always nil) is accessed.

## Expected behavior

The API should respond without a panic when the request is called.

## System information

- OS: Ubuntu
- Server: supabase/gotrue v2.6.30

## Additional context

It seems the issue was introduced in https://github.com/supabase/gotrue/pull/124 (commit: https://github.com/supabase/gotrue/commit/0574ddcb7651232ed68cb1144c3b788636e4cd0e)

## Potential Solutions

One approach could be to use the unverified signature to lookup the instance configuration (and the instance specific JWT Secret) and using that to verify the signature. Another option could be to require that users provide the instance id in the header.

I think at the minimum, this error should be handled correctly and the behavior documented.

I tried both these solutions locally and am happy to send a PR to address this if you could provide some guidance on what the expected behavior here would be.

**Comment by J0** [comment]
Hey @pratheekrebala,

We have unfortunately decided to deprecate the `multi` command together with references to `instanceID` for now.  We will review this decision again when we expand as a team.

Feel free to let us know if you have any further questions!
