### ISSUE TITLE
Add the posibility to use wildcard paths in the "Additional redirect URLs" Setting

### ISSUE THREAD

**Issue by holderbaum** [supabase/gotrue#477]
# Feature request

## Is your feature request related to a problem? Please describe.

I have an application with non-enumerated deep-links, think of something like `https://eventmanager.example/signup/[UUID]`. Every page allows people to register or login via magic-link. And I must say, what an amazingly convenient feature. I love it and integration with Vue3 was a bliss.

Unfortunately, once a user gets the magic mail, clicking on the link will send the user back to the root page of my application. This breaks the user flow since they can not easily reach the UUID Page they clicked log-in on.

There is also no 1:1 relation between sub-pages and users, which means, I have no way to find out where the user came from, once they are logged in on the root page.

Adding all possible UUIDs to the allowed-list is not feasibly, they are user-managed and potentially changing frequently.

## Describe the solution you'd like

Like other de-facto standard SSO solutions (Keycloak, Okta, a.s.o.), it would be extremely helpful, if a path-wildcard could be specified, like: 'https://example.org/foo/*', which would allow all paths below https://example.org/foo/''.

## Describe alternatives you've considered

An alternative would be to have the possibility to attach context to a magic-link mail. If I could add a payload that is encoded in the access_token which is sent in the mail, the website entry point could theoretically handle the redirect after login.

But I think it would be preferable to support wildcard redirects, like Keycloak does as well. I love supabase and really want to base my current product on your service, but this missing feature feels like a major deal-breaker right now. I am super interested in the perspective of the supabase team, maybe I am missing an obvious solution to my problem :grin: 

All the best
Jakob

**Comment by holderbaum** [comment]
Hey JL,

thank you for the super fast reply! :partying_face: 

I saw the issue you mentioned and understood it like this: Wildcards only match for subdomains. Did I misunderstood? Let me quickly test it on the prototype...

I just tested and it did not work with the wildcard path.

Using the following path in the supabase settings:

```
https://myproduct.org/*
```

And using `https://myproduct.org/7c84922c-b811-4122-ba82-fbd9241ce02c` as redirect URL, I get the following error: `https://myproduct.org/#error=invalid_request&error_code=400&error_description=Verify+requires+a+token`.

Without wildcard, by specifying the full path ion the settings, login and redirect works.

I am a bit lost :smile:

**Comment by awalias** [comment]
`Verify+requires+a+token` is the token missing from the request? Can you share with us an example of the url that gets sent inside the email?

Trying to determine if the error is legit or if this error message being sent by mistake?

**Comment by holderbaum** [comment]
Yeah sure. As mentioned before, the only difference between working and getting this error is that I used the wildcard notation in the supabase settings. Here is the URL I got via Mail:

```
https://[....].supabase.co/auth/v1/verify?token=okiviuqkjqrhhfatzxwj&type=signup&redirect_to=https://myproduct.org/7c84922c-b811-4122-ba82-fbd9241ce02c?
```

Compared to previous links I got via mail, this looks legit, I think.

**Comment by J0** [comment]
Hey @holderbaum,

Thanks for reporting this! Let me test it out and get back to you in a bit.

**Comment by J0** [comment]
Hey,

I'm going to close this issue for now but do feel free to re-open or send in a ticket if you are still facing issues.

Thanks!

**Comment by holderbaum** [comment]
Hey @J0 , thanks for the reply. I am sure that I missed a specific thing, I will try again as soon as I can spare the time (still a hobby project, unfortunately).

Your tests are replicating the exact behavior I am looking for, so it is definitely supported. I am sure that I will figure out what part is missing on my side :slightly_smiling_face: 

Thank you so much!

**Comment by J0** [comment]
No worries @holderbaum, feel free to reach out again if you end up stuck. We're always looking to improve our documentation and developer experience and I'll make sure this gets raised to the team so we can better document it.
