### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by captDaylight** [supabase/gotrue#481]
I don't know what "JAM projects" means, was hoping to ask in the discussions... but it doesn't look like it's set up. Would you consider enabling discussions for these kinds of questions?

**Comment by J0** [comment]
Hey @captDaylight,

Thanks for the query! We actually have a discussions forum [on the main Supabase repo]( https://github.com/supabase/supabase/discussions) so do feel free to fire away with any questions that you might have over there.

Just wondering, at which part of our docs/site/repos did you come across the term "JAM projects"? We'd love to clean the section up and make it clearer

**Comment by J0** [comment]
Going to close this for now but let me know if there are any further questions/concerns.

Thanks!
