### ISSUE TITLE
Test phone number auth with predictable OTP

### ISSUE THREAD

**Issue by osejrafael** [supabase/gotrue#483]
# Feature request

## Is your feature request related to a problem? 

Submitting to an app store requires developer to provide apple/google with credentials. There's no way to do this if your app does login with phone number unless you can create a test phone number with a predefined OTP verification code.

## Describe the solution you'd like

Create a test phone number with a predefined OTP verification code.

## Describe alternatives you've considered

Provide an additional field where you enter Twilio/MB credentials to enter a phone number with a OTP.
When a user tries to login with that phone number no sms is sent and when ask to enter OTP you enter the test verification code and the test user is able to authenticate.

## Additional context

Firebase has a similar feature.

**Comment by J0** [comment]
Reference Firebase feature: https://firebase.google.com/docs/auth/web/phone-auth

**Comment by kangmingtay** [comment]
Closing since this is similar to #901
