### ISSUE TITLE
support for facebook external auth?

### ISSUE THREAD

**Issue by andykais** [supabase/gotrue#49]
# Feature request

## Is your feature request related to a problem? Please describe.
Our app would like to authenticate users via facebook and then pull a list of friends from that user.

## Describe the solution you'd like
Ideally supabase can authenticate with facebook for us, and store an auth token in the database that we can use to pull data from facebook in a long running task somewhere on a daily interval.

## Describe alternatives you've considered
The alternative is not really feasible using postgrest. There is a good amount of complicated client to server communication that I do not want to write in sql statements. That means the alternative we are using for now rolling our own rest server that talks to a postgres database

## Additional context

facebook is an oauth provider https://en.wikipedia.org/wiki/List_of_OAuth_providers

**Comment by awalias** [comment]
looking at this today, there is some discussion on this on the netlify forums: looks like the backend implementation may not be complete: https://community.netlify.com/t/add-additional-social-logon-providers/20125/16

**Comment by awalias** [comment]
ok this is working on the backend, I just need to add the relevant bits to the supabase dashboard and we should be good to go!

**Comment by awalias** [comment]
ok will be in the next release of the dashboard @andykais 👍 (which will likely be tomorrow or monday)
