### ISSUE TITLE
Confirmation emails not sending.

### ISSUE THREAD

**Issue by EnzoPujol** [supabase/gotrue#492]
Hello! I'm having problems with confirmation emails when I register accounts. Basically, when I send the data through my project API to handleSignUp function, the user is created and keeps waiting for verification, but the email does not reach destination.

## To Reproduce

1 - Register an user with a valid email and password calling the following method: 
```
const { data: user, error } = await supabase.auth.api.createUser({
      password,
      email,
      data: {
        rol: Rol.GUEST,
      },
    });
```
2 - Go to either your email or another you have and check if the confirmation message is there.
3 - No message is there, and the accounts stays on waiting for verification.

## Expected behavior

The user is created and the email confirmation reaches destination.

## System information

- Version of supabase-js: ^1.35.3
- Version of Node.js: 14.17.6

## Additional context

This procedure was working normally until yesterday, I think: I don't know if anybody else is having this issue or if it's just me. Any feedback is appreciated.

Thank you for your attention!

**Comment by kangmingtay** [comment]
hey everyone (@mzalevski, @EnzoPujol), can you please file a support ticket via https://app.supabase.com/support/new so we can investigate the issue?

**Comment by mzalevski** [comment]
@kangmingtay done :)

**Comment by J0** [comment]
Hey @mzalevski @EnzoPujol wanted to check in and see if this is still an issue for you.

Let me know!
Joel

**Comment by hf** [comment]
Hey, please make sure you read our [Production Readiness](https://supabase.com/docs/going-into-prod) document. The basic SMTP sending feature is best effort only and there to get you started, but it is definitely not meant for production. You should bring your own SMTP server which is configured properly.

Email deliverability is a complex topic, and often there's no easy way to figure out why some emails are not reaching their destinations. It's always a good idea to setup DKIM, DMARC and SPF rules on your domains which significantly increases deliverability.
