### ISSUE TITLE
Expose HTTP headers from auth APIs to database triggers

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue#498]
# Feature request

## Is your feature request related to a problem? Please describe.

Developers would like to be able to restrict sign-ups and/or sign-ins ONLY to specific domains (see https://stackoverflow.com/questions/71591949/restrict-supabase-sign-up-to-a-specific-domain).

## Describe the solution you'd like

It seems that this can be easily implemented if database triggers that were fired in response to auth changes (e.g. adding a new user to the ```auth.users``` table) could access the HTTP headers from the request. That way, the trigger can inspect the ```Origin``` header  (or ```Referer```) and abort the transaction if the ```Origin``` are NOT in the allowed list.

## Describe alternatives you've considered

It seems like there are 2 existing options:

1. Re-define the sign-up/sign-in APIs in a custom server app which then call the Supabase APIs. The drawback is having to re-implement the APIs only to check the ```Origin``` header.

2. Another option is to add an additional db table with some triggers and an additional call from the client to the server which would generate and return a nonce ONLY if the ```Origin``` of the first request is allowed. For example, here is how this can work for the sign-up flow:
   - define a table which will store nonces - e.g. ```auth_nonce``` - with a single UUID auto-generated column; 
   - define a ```BEFORE INSERT``` trigger on the ```auth_nonce``` table. If the ```Origin``` HTTP header inside the trigger is NOT allowed, abort the transaction;
   - define a ```BEFORE INSERT``` trigger on the ```auth.users``` table and inspect the ```raw_user_meta_data``` - if it does NOT contain a valid nonce (i.e. a nonce present in the ```auth_nonce``` table), abort the transaction; if it contains a valid nonce - allow the insertion into ```auth.users``` and remove the nonce from the ```auth_nonce``` table (so it cannot be re-used);
   - before sending a sign-up client request, send a client request to insert a new record inside the auth_nonce table. This call will succeed ONLY if the domain is allowed and should return the generated nonce (because of the second step above);
   - the client sends a sign-up request by including the nonce returned from the previous call;

This second option involves multiple steps and additional calls, so it's also not a convenient workaround for the task;

**Comment by hf** [comment]
Hey this is a great suggestion. We are planning to introduce proper webhook and trigger support in GoTrue which will enable you to customize the account creation and other behaviors. 

There is no clear timeline for this yet.

**Comment by J0** [comment]
Hey Circling back on this,

We're looking into webhooks soon and we'll keep this ticket in mind - do let us know if theres anything else you feel that's worth noting or any other use cases you'd like to see supported.

Thansk!

**Comment by lauri865** [comment]
Any update on this? Major hindrance for e.g. implementing multi-account sign-in, etc.

**Comment by hf** [comment]
These hooks are coming in the next few months, at which point you can build your custom blocking rules.

**Comment by hf** [comment]
I will close this specific issue as we are not planning on exposing HTTP headers to triggers _at all_. Headers can be exposed in the Auth Hooks though.

**Comment by lauri865** [comment]
@hf, how can one use headers with auth hooks? There was no documentation about it last I checked.

**Comment by J0** [comment]
@lauri865 at the moment it's not possible to use headers with Auth Hooks (Postgres).  Auth Hooks (HTTP Functions) are coming soon shortly though - you'll be able to access the headers on the HTTP Functions.

**Comment by lauri865** [comment]
@J0, any idea when this will be launched? It's a major blocked for a multi-account / account-switcher pattern with Supabase. And I don't personally see a reason why this couldn't be solved easily on Postgres hooks level, and needs an extra HTTP call.

Say we have an account:
´lauri@gmail.com´

Lauri belongs to teams ´Alpha´ and ´Beta´. Teams have vanity subdomains ´alpha.app.com´ and ´beta.app.com´. If Lauri signs in from ´alpha.app.com´, we want to issue a token for the ´Alpha´ team, and vice versa, if logged in from ´beta.app.com´. 

This could easily be derived from the Origin header, but also manipulated with arbitrary headers set from the backend. The result would be 100x better than other implementations we have seen, which create a new db-level layer for picking an active account, which means that the source of truth no longer lives in the JWT, and you cannot use Postgres roles with PostgREST – all making it a security nightmare where errors are easy to come by.
