### ISSUE TITLE
Are the server responses format documented? (email address is already used, password too short, etc).

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue#5]
# Question

## Additional context

From https://github.com/supabase/supabase/issues/143

Are the server responses format documented ? If they are I couldn't find them otherwise they should definitely be added to the doc at some point. It would make it easier to display accurate errors to the user (e.g. this mail address is already used, password too short, etc).

Edit: To be clear I did find some documentation here but I'm interested in the format of errors which are not in the readme.

**Comment by icecream78** [comment]
Errors format described as
{code: <int>, msg: <string>}
As I understand your question properly - in project there no centralized place where all errors are placed. In my opinion if someone implement issue #20 , so it will replace documentation from README to more attractive way

**Comment by kiwicopple** [comment]
Thanks @icecream78 - agreed that once there is a swagger we can autogen the docs into our website: https://supabase.io/docs/gotrue/server/about
