### ISSUE TITLE
Add wildcard for any number of subroutes for auth redirect urls

### ISSUE THREAD

**Issue by dreinon** [supabase/gotrue#505]
With the actual implementation of auth redirect url wildcards, we can set this kind of url https://domain.com/sub1/sub2/*/*, so any pair of subroutes of https://domain.com/sub1/sub2 are valid redirect urls, but it would be nice to have a wildcard (for instance, `**`) to handle any number of subroutes, so we could use it like https://domain.com/sub1/sub2/**. This would englobe:
- https://domain.com/sub1/sub2/*
- https://domain.com/sub1/sub2/*/*
- https://domain.com/sub1/sub2/*/*/*
- etc.

Hope I explained myself and please, feel free to ping me in case the feature is not well explained.

**Comment by J0** [comment]
Hey @dreinon,

Nice to hear from you. To make sure I'm understanding correctly would the feature request be for something like `https://google.com/sub1/sub2/**` and have it match `https://google.com/sub1/sub2/sub3/sub4` or any other pattern of enumeration.

We actually use Go globbing under the hood for matching so you should be able to use the `**` wildcard operator like:

<img width="910" alt="CleanShot 2022-06-27 at 13 37 16@2x" src="https://user-images.githubusercontent.com/8011761/175867153-74210963-ec89-4269-bfba-044df7b466ee.png">

Let me know if this covers your use case!

**Comment by dreinon** [comment]
@j0 yeah that's the case, but somehow it didn't work for me in supabase. Could you test it in production, please?

**Comment by J0** [comment]
Hey,

Tested this on a [fresh supabase instance](https://supabasetest.aceofspade.repl.co) with the following settings:

<img width="970" alt="CleanShot 2022-06-28 at 16 17 25@2x" src="https://user-images.githubusercontent.com/8011761/176129909-69ca9b44-6e91-43d5-b29d-6e34765c4d70.png">

and it seems to work for the following URL: 
![CleanShot 2022-06-28 at 16 18 51@2x](https://user-images.githubusercontent.com/8011761/176130283-5c7f0870-2fe2-407a-9383-bccabb21f668.png)

Could I trouble you to try again on your instance? Also feel free to open a support ticket at support@supabase.io if there are still persistent issues

**Comment by dreinon** [comment]
It works now! Thanks Joel 🙂
