### ISSUE TITLE
Azure AD external auth

### ISSUE THREAD

**Issue by tehnorm** [supabase/gotrue#52]
# Feature request

## Is your feature request related to a problem? Please describe.

Our organization is standardized on the Azure stack and as such we are required to use Azure AD for auth.

## Describe the solution you'd like

Ability to authenticate via Azure AD over OAuth.

## Describe alternatives you've considered

An alternative is not really feasible using Supabase without some hackery. I suppose we could have some weird callback system through another auth system that works with Azure AD that then creates a user in Supabase but it's going to get messy quickly.

## Additional context

Azure AD supports OAuth 2.0 - https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/auth-oauth2

**Comment by awalias** [comment]
thanks for this one @tehnorm will take a look at what's involved

**Comment by tehnorm** [comment]
Hi @awalias - we have opened a PR for this here: https://github.com/supabase/gotrue/pull/54 Please let us know if needs any additional work.

**Comment by awalias** [comment]
great @tehnorm checking now thanks for the heads up

**Comment by kiwicopple** [comment]
Fixed by Levet: https://github.com/supabase/gotrue/issues/52
