### ISSUE TITLE
Support multiple Google OAuth platforms

### ISSUE THREAD

**Issue by He1nr1chK** [supabase/gotrue#523]
# Feature request

## Is your feature request related to a problem? Please describe.

Developing apps that work across platforms necessitates having the OAuth work across those platforms.  When setting up the Google provider in the console, the client ID field only allows one single client ID which limits you to one platform. More specifically, if say one has a website and iOS app and Android app you will have a specific client ID for each platform. With the great work that @kangmingtay, @koba-ninkigumi and others have done with the recent support of OIDC id_token support in these PRs #189 & [#207](https://github.com/supabase/gotrue-js/pull/207), this has now become a problem.

## Describe the solution you'd like

Support for multiple client IDs for Google (and maybe others, not sure) would solve the problem.

## Describe alternatives you've considered

The alternative up to this point has been to use the web-based flow on all platforms which is not ideal as it does not support a fully native feel on mobile platforms.

## Additional context

When using the OIDC sign in method on iOS for example with a web client ID in the Supabase portal results in the following error: 
```
{"message": "oidc: expected audience "_redacted Google web client ID_" got ["_redacted Google iOS client ID_"]", "status": 400}
```

**Comment by hf** [comment]
This is definitely something we'll be looking to add for the next major version. Thanks for the feedback and suggestion.

**Comment by ath88** [comment]
I have the same issue - but for the Keycloak provider. Currently it's impossible to configure multiple Keycloak realms, since only one client id and client secret can be provided. 

I can add another issue - but the author mentioned that it might apply to other providers too, so I figured the solution to both issues will be very similar.

**Comment by hf** [comment]
At this time we don't support multiple providers, and we're definitely having this in mind for the future. Thank you for the suggestion!

**Comment by ath88** [comment]
@hf Do you have a solution for tracking interest into different features? May I suggest using [Canny](https://canny.io)?

**Comment by connorlindsey** [comment]
Experiencing the same issue with Sign in with Apple

**Comment by sinameraji** [comment]
has this been revisited/resolved by any chance? it's a must in 2025
