### ISSUE TITLE
Dart auth stating If "Email Confirmations" is turned on, both a user and a session will be null

### ISSUE THREAD

**Issue by wanttobuyaboat** [supabase/gotrue#529]
# Improve documentation

## Link 

https://supabase.com/docs/reference/dart/auth-signup

## Describe the problem

The document states:
If "Email Confirmations" is turned on, both a user and a session will be null.
This is not true as I can get a user.id returned from the signUp with Email Confirmations turned on. 

## Describe the improvement

If "Email Confirmations" is turned on, a user will be returned.

## Additional context

Maybe the docs are correct and the behavior is wrong.

**Comment by J0** [comment]
Hey!

 Not too familiar with the Dart lib but in the [JavaScript SDK](https://supabase.com/docs/reference/javascript/auth-signup) if email confirmation is enabled a user will be returned and session will be null. 

cc: @dshukertjr

**Comment by dshukertjr** [comment]
@wanttobuyaboat 
Thank you for spotting this. The behavior on the documentation is the behavior until version 0.2.0 of gotrue-dart, but it was fixed on v0.2.0 to align the behavior with js client. I will update the docs now!
