### ISSUE TITLE
Integrated Zanzibar-style AuthZ system

### ISSUE THREAD

**Issue by RichiCoder1** [supabase/gotrue#530]
# Feature request

The addition of a [Zanzibar-style](https://zanzibar.academy/) AuthZ system for modeling relationship that can then be queried and updated via Postgres helpers.

## Is your feature request related to a problem? Please describe.

While Row Level Security is incredibly powerful, it can get very complex and intimidating very quickly to setup effective and performant policies. There's been a recent wave of OSS and SaaS Zanzibar providers whose whole goal is to simplify and make scalable AuthZ systems. It'd be great to be able to model and work with a system built specifically for AuthZ, which still being able to take advantage of the power of RLS and Supabase.

## Describe the solution you'd like

Integrating a solution like https://docs.authzed.com/ or https://www.ory.sh/docs/keto, and exposing (via the SDK and Postgres functions) the ability to write to and query from these systems.

## Describe alternatives you've considered

Alternatively adding something like https://age.apache.org/?l=overview# to model these graph-like relationships manually.

## Additional context

This is probably a pretty big ask, but would (hopefully) greatly simplify setting up effective AuthZ.

**Comment by hf** [comment]
Hey this is an interesting suggestion, but right now our focus is to make it easy to build apps with Postgres and PostgREST in the Supabase platform. Adding Zanzibar support, although a great idea, only adds unnecessary complexity to our system. The great thing about Supabase is that you can bring your own solutions if you think they can help you more. 

I'll be marking this as Close as not planned, but we'll definitely keep it in mind for any future major versions.

**Comment by joshxyzhimself** [comment]
I think a list of Authorization solutions for supabase would be nice
