### ISSUE TITLE
Add token info to the response of the /admin/generate_link API

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue#538]
# Feature request

## Is your feature request related to a problem? Please describe.

When sending custom sign-up emails with a mail provider via a REST API (e.g. via MailJet), it's important to provide the confirmation token inside the email. This way, the confirmation email can contain a link the the app's domain (e.g. ```myapp.com```) and used a redirect on the server side to redirect to Supabase's ```/verify``` API. The token can then be passed through in the redirect - the benefit of this is that the user will only see app links in the email and not some random looking link to a Supabase project. 

## Describe the solution you'd like

Currently, this is possible by parsing the link returned by ```/admin/generate_link``` API. However, it would be great if the response (which is already formatted as JSON) already included the sematic parts of the link in separate fields in the returned JSON so the dev does NOT need to parse the link in order to extract them (e.g. return the token, redirect url, etc).

## Describe alternatives you've considered

Parsing the url using regex or a URL parser library (depending on the environment).

**Comment by hf** [comment]
Interesting, we'll take it into consideration for the next major version of the library.

**Comment by chipilov** [comment]
@hf It seems that @kangmingtay has already implemented this in [2.8.1](https://github.com/supabase/gotrue/releases/tag/v2.8.1).

If so:
 - this issue can be closed;
 - I have created a PR with an update to the docs: https://github.com/supabase/gotrue/pull/583 - it would be great if someone can review it so it can be merged;

**Comment by kangmingtay** [comment]
hey @chipilov, thanks for the feedback to help make this possible!
