### ISSUE TITLE
Verify password validity before existence of a user during /admin/generate_link calls of type 'signup'

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue#539]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to use the ```/admin/generate_link``` API to sign-up new users. In order to prevent leaking information about registered users, it's important to be able to return no error if someone tries to sign-up with an email which already exists. Currently, this is problematic because the ```/admin/generate_link``` uses the same error code for weak password and existing user (HTTP 422) but prioritizes the user existence error first. This means that a rogue user can check the existence of a user if they supply a weak password - if the user already exists they will get no error but if the user does NOT exist they will get a weak password error.

## Describe the solution you'd like

Prioritize the weak password error when returning the result for ```/admin/generate_link``` OR return a list of errors codes instead of a single error message.

## Describe alternatives you've considered

Currently, I am manually checking the strength of the password before calling the API.

**Comment by hf** [comment]
Hey thanks for this issue.

Do have in mind that you're calling an `/admin` endpoint which is meant to be used _only_ by those who have access to an admin JWT. By extension, then, anyone with access to that token already has access to the list of users in the system.

Please make sure you're using calling the `/admin/generate_link` API from a secure location like a server you control that is not open to the public at large (e.g. has some authentication to be used).

**Comment by chipilov** [comment]
@hf I understand that and I do call it from a server environment. I guess I did NOT explain it well enough - the fact that a user cannot call this API directly does NOT mean they cannot call my custom sign-up API directly (if they can't, my own UI app would not be able to either). So the problem is that in my API implementation, I call this admin endpoint but I still need to return something to the client.

The workaround I have right now is that I manually check for the password length BEFORE I make a call to the admin API.

Does that make sense?

**Comment by hf** [comment]
Hey @chipilov it does make sense. The password strength check in this API call is just a basic length check. You are encouraged to use a better password strength checking strategy, such as ZXCVBN or HaveIBeenPwned.org.

Even if we did reorder the response errors, it would be up to your API to properly mask any information about the existence of a user. (This is very hard - practically impossible - to do well, though.)
