### ISSUE TITLE
Feature Request - New Ory Hydra OAuth2 Provider Integration

### ISSUE THREAD

**Issue by koakh** [supabase/gotrue#540]
# Feature request

I want a new Ory Hydra OAuth2 Provider Integration

## Describe the solution you'd like

Waiting for someone/team/community integrate Ory Hydra OAuth2 Provider

## Describe alternatives you've considered

The alternative is integrate it, and contribute with PR of the Integration with some info how to setup and a online demo of everything working, and a deployed OryHydra server if supabase members wants to test integration without deploy it

## Additional context

This same feature request will be in repos supabase-js and supabase gotrue repos

- [related issue](https://github.com/supabase/gotrue-js/issues/316)

**Comment by J0** [comment]
Hey we're going to move this to the mega thread(#451 ), please do upvote it there if you'd like it implemented.

Thanks!
