### ISSUE TITLE
"Database error granting user" on sign up/sign in

### ISSUE THREAD

**Issue by nstrelow** [supabase/gotrue#541]
I have been very inconsistently getting a this error "Database error granting user" with a 500 HTTP status code.

Sometimes I try it a bit more and then it starts working again.

Has anyone had that before?

**Comment by kangmingtay** [comment]
Hey everyone, these errors are usually returned when there is a failing trigger created on one of the tables in the auth schema. If anyone's still facing this issue and require assistance, please contact Supabase at our support link (https://app.supabase.com/support/new)

**Comment by saltcod** [comment]
Super old, but ran into this tonight. It was an issue with a trigger function having a misnamed param. To debug, start with a basic trigger like this and work back: 

```
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$$;

-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

```

**Comment by kangmingtay** [comment]
@saltcod yeah, this error is returned if you have a trigger on the auth schema that fails - it causes the entire transaction to be rolled back

**Comment by TomasSestak** [comment]
For me it was because i was hashing the password by myself first - then i inspected that supabase makes that for ya

**Comment by TomasHubelbauer** [comment]
Happened to me when running my project locally and I had to manually remove all Docker Supabase volumes in addition to `supabase stop --no-backup`. I also deleted all images for good measure and made sure I was starting absolutely everything from zero, but I think the image refetch step is not necessary.

**Comment by EvoTechMike** [comment]
I had this error due to importing a backup.  Clearing out the refresh tokens fixed it for me:

```
psql "postgresql://postgres:postgres@127.0.0.1:54322/postgres" -c "DELETE FROM auth.refresh_tokens WHERE revoked = true OR created_at < NOW() - INTERVAL '7 days';"
```
