### ISSUE TITLE
Revoke Refresh Token

### ISSUE THREAD

**Issue by Deliana90** [supabase/gotrue#543]
![Screenshot from 2022-03-11 13-07-57](https://user-images.githubusercontent.com/96174573/157812078-af5b2345-3cba-4ac8-a7e5-26ea8cc44fc9.png)

firebase have this https://firebase.google.com/docs/auth/admin/manage-sessions#revoke_refresh_tokens

**Comment by J0** [comment]
Hey @Deliana90,

Thanks for the request -- we currently have a `Logout` endpoint which revokes all refresh tokens.

Hope this helps! Feel free to let us know if there are further questions or feedback.

Thanks!
