### ISSUE TITLE
Sign in automatically authenticates email of an user that did not authenticate his email

### ISSUE THREAD

**Issue by SeekSaveServe** [supabase/gotrue#544]
# Bug report

## Describe the bug
await supabase.auth.signIn({
        email: formState.email,
        password: formState.password,
      });
Automatically authenticates email despite the user not clicking their confirmation email.

## To Reproduce
There are 2 ways to create this bug
Method 1:
1. Create a DB using quickstart : react
2. Sign up an user using email and password
3.  Repeated attempts at signing in the unauthenticated new account will change the 'confirmed at' column of that account from 'null' to a new timestamp.
(might take a second log in attempt to trigger)
4. User will be logged in despite not confirming his email

Method 2:
1. Create a DB using quickstart : react
2. Sign up an user using email and password
3.  Confirm the user's email
4. Delete the account from auth.users using sql command
5.  Recreate an account using the same email and a different password
7.  Repeated attempts at signing in the unauthenticated new account will change the 'confirmed at' column of that account from 'null' to a new timestamp.
9. User will be logged in despite not confirming his email

## Expected behavior

User should not be able to login with email and password if they did not confirm their email

**Comment by SeekSaveServe** [comment]
Hi @J0 ! Apologies for the very late reply, it is working after we redeployed it :)

**Comment by J0** [comment]
Not at all -- good to hear that it's working! Going to close for now but feel free to reach out again if you run into any issues :)
