### ISSUE TITLE
Social Login with Chrome extensions

### ISSUE THREAD

**Issue by geordidearns** [supabase/gotrue#546]
# Feature request

## Is your feature request related to a problem? Please describe.

Yes, the problem being that Social login such as google does not seem to work as intended in Chrome extensions. I have followed this discussion here: https://github.com/supabase/supabase/discussions/5787

Which has the same issue, and I'm hoping to find improved documentation, or help towards a solutions to be able to build extensions with Supabase.

## Describe the solution you'd like

Improved documentation around how to make social logins work with extensions.

## Describe alternatives you've considered

Building with Firebase instead, as they have Google OAuth that works with extensions as documented here: https://developer.chrome.com/docs/extensions/mv3/tut_oauth/

## Additional context

I asked this in the discord and it was suggested to create an issue here :) Thanks!

**Comment by der-ofenmeister** [comment]
I think there shouldn't be an issue now. If anyone's still having issues I'm more than happy to direct them/show some (more) code.

**Comment by J0** [comment]
Gotcha, thanks so much @der-ofenmeister! Closing this for now
