### ISSUE TITLE
OTP by email should not send email verification link, email should be verified when user inputs correct OTP

### ISSUE THREAD

**Issue by fergusmeiklejohn** [supabase/gotrue#547]
# Bug report

## Describe the bug

Email OTP for new users is sending an email with a link to confirm the email instead of the OTP. This is unnecessary with email OTP, since if the user can successfully paste the OTP into the app they have access to this email address, and it's bad UX since the user expects an OTP not a link. The bug is that to prevent this we must turn off email verification, so users are verified immediately they enter an email.

## Expected behavior

I think solution to this for email OTP only is to send an OTP instead of a confirmation link with new users and to mark the email as verified when the user enters a valid OTP.

**Comment by J0** [comment]
Hey all,

You should now be able to generate a 6-10 digit email OTP via the [ admin generateLink endpoint](https://github.com/supabase/gotrue#post-admingenerate_link) which you should then be able to use to perform the following behaviour.

Going to close this for now but feel free to re-open if there are further questions or queries.

Thanks!
