### ISSUE TITLE
Add the generate_link endpoint to the GoTrue Auth Server reference page 

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue#548]
# Improve documentation

## Link 

[GoTrue Auth Server](https://supabase.com/docs/gotrue/server/about)

## Describe the problem

This page lists the endpoints exposed by the Supabase GoTrue server, however, it seems that it's out of date since it is missing the recent addition of ```/generate_link``` in the endpoints.

## Describe the improvement

Add a reference to the ```/generate_link``` API (and any other APIs that might have been added recently).

**Comment by J0** [comment]
Please find the OpenAPI Specification for GoTrue [here](https://github.com/supabase/supabase/tree/master/spec)

PRs are welcome :)
