### ISSUE TITLE
Reddit OAuth2 Support

### ISSUE THREAD

**Issue by aetinx** [supabase/gotrue#577]
# Feature request

## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

It would be cool if Reddit OAuth could be used in Supabase.

## Describe alternatives you've considered

Making my own. 💀

## Additional context

N/A

**Comment by amosbastian** [comment]
I would love this too 👍 I need this for one of my projects and have been using NextAuth + Planetscale, when I'd much rather use Supabase

**Comment by J0** [comment]
Hey @aetinx  and @amosbastian,

Thanks for the interest! Going to move this to the main thread on #451 so do feel free to upvote the request there. This helps us to better gauge which providers to implement.

Thanks!
