### ISSUE TITLE
allow wildcards in redirect URLS for dynamic dev environments like Gitpod

### ISSUE THREAD

**Issue by stukennedy** [supabase/gotrue#578]
On Gitpod I can't get Magic Link auth working in my dev environment without setting the redirect URL to whatever the current path the app is being laucnhed on 
(in my case https://3000-continuata-viqrio-t16z9w4kls9.ws-eu54.gitpod.io)

The subdomain is dynamically allocated.

It'd be great to be able to add a more agnostic redirect URL e.g,
`*.gitpod.io` or `%.gitpod.io`
So I can develop without having to edit my supabase settings.

**Comment by stukennedy** [comment]
Yes that looks great.
Thanks for the swift reply. 

Some description of the redirection rules and formatting possibilities in the docs would be really helpful, was quite tricky to figure out what site URL and redirect URLs are doing by trial and error.

**Comment by J0** [comment]
Noted, this is good feedback. We've created an internal issue with the documentation team so that we can track this. Closing this for now.
