### ISSUE TITLE
Error messages allows malicious actors to probe if an account with a specific email exists.

### ISSUE THREAD

**Issue by malobre** [supabase/gotrue#59]
# Bug report

## Describe the bug
When signing in, GoTrue can return different error messages:
- `No user found with this email`
- `Invalid Password`

This allows malicious actors to probe if an account with a specific email exists.
The same goes for the password recovery feature, where GoTrue can return `User not found`.

## Expected behavior
When signing in, return a unified error message, e.g `Invalid email or password`.
When recovering a password, do not tell the user if the email is not associated with an account.

**Comment by icecream78** [comment]
@awalias @kiwicopple close the issue

**Comment by kiwicopple** [comment]
Thanks @icecream78 !
