### ISSUE TITLE
Redirect URLs set in Supabase console are ignored

### ISSUE THREAD

**Issue by dshukertjr** [supabase/gotrue#590]
# Bug report

## Describe the bug

When setting `Redirect URLs` from the Supabase console and calling `signin()` with `redirectTo` option, the user still redirected to site URL and not the URL set as `redirectURL`.

**Comment by J0** [comment]
Hey all, 

We've rolled out a patch which should resolve this issue -- going to close for now but feel free to re-open if you're still facing issues.


Thanks!
