### ISSUE TITLE
Improve email change DX

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#60]
current email change email is sent to user

- [ ] add template to supabase dashboard
- [ ] gotrue confirmation url should be a get request to users endpoint with the `email_change_token` as a query param, which is confirmed and returns a new valid login session (hence invalidating older refresh_tokens that may have been opened on the old email) this is current implemented [here](https://github.com/netlify/gotrue/blob/76da595b29fc8a436d8b881bb73f0fe862960c7e/api/user.go#L104)

**Comment by J0** [comment]
Taking the liberty to close but feel free to reopen if there's more to be done w.r.t templating. 

Will follow up with the sub-issues like #67 when a slot frees up. Have replicated the bug but need to discuss the fix 

cc: @kangmingtay @hf
