### ISSUE TITLE
Game Center and Google Play Services integration

### ISSUE THREAD

**Issue by bdlukaa** [supabase/gotrue#601]
# Feature request

Support Game Center OAuth

## Additional context
- https://github.com/supabase-community/supabase-flutter/issues/156
- https://developers.google.com/games/services

**Comment by hf** [comment]
Thanks for this. We'll be taking a look and discussing with the team.

**Comment by J0** [comment]
Hey as with the rest of the requests, we will be moving this to the thread on  #451 Going to move this thread there but feel free to re-open if there are still issues.

Thanks!
