### ISSUE TITLE
Limit sms per phone number

### ISSUE THREAD

**Issue by myemuk** [supabase/gotrue#605]
# Feature request
## Is your feature request related to a problem? Please describe.

First of all, SMS price is high in my country. Secondly, competitors or enemies can use this feature or bug in order to send a lot of expensive SMS messages, so it will lead us to loose money.

## Describe the solution you'd like

First of all, add a configuration let's say 5 sms per 24 hours.
Secondly, please add how much time and how many attempts left until SMS code is valid in method `supabase.auth.verifyOTP`

## Describe alternatives you've considered

Whatsapp phone verification will not allow you to send more than 6 SMS in 24 hours.

**Comment by hf** [comment]
Hey please take a look at the hCaptcha functionality we have built in. Unfortunately there isn't much that can be done when implementing phone-based logins, if that's something you need.

**Comment by myemuk** [comment]
Thank for info. Sad that it is not in the plan. Btw, there is a PR what adds custom SMS provider: [558](https://github.com/supabase/gotrue/pull/558). Can you have a look at it and merge as soon as possible since it will help me a lot in mu case.
