### ISSUE TITLE
Add Linkedin as an External Auth Provider

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#61]
can follow existing code for google/github etc.

**Comment by gozeloglu** [comment]
Hi @awalias. Do you mean [Google](https://github.com/supabase/gotrue/blob/master/api/provider/google.go) and [GitHub](https://github.com/supabase/gotrue/blob/master/api/provider/github.go)? If yes, I'd like to take that issue. My plan is that following processes on Google and GitHub for LinkedIn.

**Comment by anindha** [comment]
@gozeloglu I am also wanting this feature. Happy to work with you if you need help.

**Comment by gozeloglu** [comment]
> @gozeloglu I am also wanting this feature. Happy to work with you if you need help.

Thanks, @anindha. I'll ping if I'll need help.

**Comment by FlorianBouron** [comment]
I also would like that feature, I can have a look during the code review.

**Comment by gozeloglu** [comment]
Hi @FlorianBouron. I don't have enough time to look at this issue right now. I am little bit busy nowadays. You or @anindha can take that issue.

**Comment by riderx** [comment]
Hi guys, i know nothing of golang but i started the work here : https://github.com/supabase/gotrue/pull/238
If someone is willing to help, i will love him forever !

**Comment by sbutler-gh** [comment]
Hey all, just noting that I'd love this feature as well!

**Comment by HarryET** [comment]
> Hey all, just noting that I'd love this feature as well!

There is a PR open however it looks stagnant. Might include LinkedIn in my latest PR if @riderx has "abandoned" his implementation?

**Comment by sbutler-gh** [comment]
> > Hey all, just noting that I'd love this feature as well!
> 
> There is a PR open however it looks stagnant. Might include LinkedIn in my latest PR if @riderx has "abandoned" his implementation?

Awesome @HarryET!  Would it be possible to do with [Member Auth/three-legged auth](https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?tabs=HTTPS) flow?  According to [this documentation](https://docs.microsoft.com/en-us/linkedin/shared/authentication/authentication), the Member Auth is required in order to access various resources/capabilities on behalf of the authenticated user.

**Comment by riderx** [comment]
@HarryET i need help on the PR, i did the max i can do in golang...
if you are good in golang, please use my Pr as base or Fix it if that easy but i can't on my side

**Comment by riderx** [comment]
@HarryET thanks a lot <3

**Comment by HarryET** [comment]
> @HarryET thanks a lot <3

Np, included it in my PR now 😀
