### ISSUE TITLE
Snapchat external provider login

### ISSUE THREAD

**Issue by wweevv-johndpope** [supabase/gotrue#611]
# Feature request

## Is your feature request related to a problem? Please describe.
signup for client / secret keys here
https://docs.snap.com/snap-kit/developer-portal/developing-your-app

I want to enable like this
```

      GOTRUE_EXTERNAL_SNAPCHAT_ENABLED: "true"
      GOTRUE_EXTERNAL_SNAPCHAT_CLIENT_ID: "111"
      GOTRUE_EXTERNAL_SNAPCHAT_SECRET: "asdf"
      GOTRUE_EXTERNAL_SNAPCHAT_REDIRECT_URI: "https://localhost:9999/callback"


```

**Comment by J0** [comment]
Closing as it is a duplicate of #451

**Comment by johndpope** [comment]
drafted here https://github.com/supabase/gotrue/pull/449/files
