### ISSUE TITLE
Add admin functionality to sign up/in a user account with a provider identity

### ISSUE THREAD

**Issue by bensalilijames** [supabase/gotrue#635]
# Feature request

## Is your feature request related to a problem? Please describe.

We have a use case where we wish to sign in/sign up a Supabase user from a game. Ideally, this would use the Steam flow described here under "Linking From In-game": https://partner.steamgames.com/doc/features/auth

That flow requires a custom server/endpoint to verify the session ticket, so I'm thinking that expanding the Admin API capabilities to support this would be very useful here.

## Describe the solution you'd like

The game would send the session token to our custom endpoint (a Next.js API route), which could do something like the following:

1) Verify the session token with the Steam server and retrieve the Steam ID
2) Use a new admin API to retrieve an existing user by the Steam ID (provider identity ID):
```ts
const user = await supabase.auth.admin.getUserByProviderIdentity({
  "provider": "steam",
  "identityId": "STEAM_ID",
});
```
3) If the user does not exist, sign up the user using their Steam ID:
```ts
const user = await supabase.auth.admin.createUser({
  "provider": "steam",
  "identityId": "STEAM_ID",
});
```
4) Create a Supabase session for the user:
```ts
const session = await supabase.auth.admin.signIn({ userId: user.id });
```
5) Return the session to the client in order to continue using Supabase client-side

An alternative could be to create a single admin API which combines all three steps into one:

```ts
const session = await supabase.auth.admin.signIn({
  "provider": "steam",
  "identityId": "STEAM_ID",
});
```

Note that it is important this is an admin/server-side API, if you could do this from a client you could log in as anybody if you had their provider's identity ID (in this case Steam ID)!

## Describe alternatives you've considered

- Using the [OAuth 2.0 Steam flow](https://partner.steamgames.com/doc/webapi_overview/oauth). Slightly worse UX than the "linking from in-game option" since the OAuth flow opens the Steam browser overlay, and there are a few sources that suggest this functionality no longer exists. I'm in contact with Steam support to see if that's the case. If it *does* still exist, we could write an OAuth 2.0 provider, so long as #414 lands.
- Using the [OpenID Steam flow](https://partner.steamgames.com/doc/features/auth#website). However, I think this is a non-starter, as it uses OpenID 2.0 and not OpenID Connect.

## Additional context

Essentially, we're looking for a way for users to sign up/sign in to Supabase using Steam as the only available provider, to reduce friction in the game as it will be published on Steam only.

Would be very grateful to hear your thoughts - thanks! 🙂

**Comment by kangmingtay** [comment]
Hi @bensalilijames, this seems very specific to steam. It might be worth to consider handling this custom behaviour on your own in the `public` schema. You can create `public.users` table that contains a `steam_id` and `user_id` column. The `user_id` column should map to `auth.users.id` so that you can easily retrieve the user information using the `steam_id`. 

If the user doesn't exist, then you can call `supabase.auth.admin.inviteUserByEmail` (assuming steam allows you to retrieve the user's email somehow) and invite the user. (Although i'm not sure if this would help to achieve your usecase)

**Comment by hf** [comment]
Thank you @bensalilijames for the suggestion. As @kangmingtay explains, this is a fairly Steam-specific behavior. We're going to look into adding Steam login to GoTrue in the future, though and we'll make sure we take your input when that happens. There's no clear timeline for this yet.
