### ISSUE TITLE
Return token links

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue#65]
# Feature request

## Is your feature request related to a problem? Please describe.

At the moment an invite handled by sending an email. It would be nice to:

- return the invite link when the `/invite` route is called
- optionally choose to send emails (eg, send by default, parameter to _not_ send)

## Additional context

- Requested by monitoro
- https://github.com/supabase/supabase/discussions/715

**Comment by awalias** [comment]
updated to include all token types:

invite, magiclink, reset password, confirmation etc.

**Comment by MoSheikh** [comment]
Hi, just came across this and I was wondering if this is still on the roadmap (or if I missed the explanation in the docs)? It would be great to be able to use a custom ConfirmationURL to support a fully offline testing environment for a user signup auth flow, for example. Thanks for all your incredible work!
