### ISSUE TITLE
Roblox OAuth provider

### ISSUE THREAD

**Issue by cursecodes** [supabase/gotrue#656]
Roblox recently opened up a private alpha for their new OAuth2 system, and should become public in a few months. I can keep this issue updated with any news, so that once it becomes public it can be implemented into Supabase.

Until then, I will come up with a basic draft and see if I can get it functioning properly locally.

Roblox is what my app is based around, but I am currently using Discord OAuth through Supabase and authenticating them using other means afterwards. Adding this OAuth would make my life incredibly simple.

**Comment by kangmingtay** [comment]
hey @cursecodes, we're closing this in view of #451
