### ISSUE TITLE
Docker image not deployed

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue#66]
# Chore

## Describe the chore

In the latest release (https://github.com/supabase/gotrue/actions/runs/560510377) the docker image didn't deploy:

![image](https://user-images.githubusercontent.com/10214025/107867922-48d7b280-6eba-11eb-8926-807104373051.png)

I tried re-running the GitHub action and it skipped the release.

I then tried on my local machine and I'm getting 

```
storage/dial.go:71:36: not enough arguments in call to columns.ForStructWithAlias
	have (interface {}, string, string)
	want (interface {}, string, string, string)
```

https://github.com/netlify/gotrue/blob/f023c23d846c98fafc8e227608d6059fb02845df/storage/dial.go#L71

This is the same as what I saw on the logs for the GitHub action (before they were cleared)

**Comment by awalias** [comment]
fixed
