### ISSUE TITLE
Redirection issue with Notion OAuth

### ISSUE THREAD

**Issue by NagariaHussain** [supabase/gotrue#674]
# Bug report

## Describe the bug

Getting "No API key found in request" instead of expected redirection to the given URI when using Notion OAuth.

## To Reproduce

Setup Notion OAuth (as described in the docs) and form the OAuth URI as below:

`${SUPABASE_URL}/auth/v1/authorize?provider=notion&redirect_to=${returnUrl}`

> In my case, returnUrl was a local expo uri ('exp://192.168.43.73:19000/--/auth/callback'), but I also tried with in browser with returnUrl set to localhost:xxx.

Visit the above URL and start the authentication flow. After the last step (i.e. selecting the notion pages to grant permission), I am being redirected to a URL of the following form:

```
<SUPABASE_URL>/#access_token=<LONGACCESSTOKEN>&expires_in=3600&provider_token=<SOMEOTHERTOKEN>&refresh_token=<SOMEOTHERTOKEN>&token_type=bearer
```

with the following response:

```
{"message":"No API key found in request"}
```

## Expected behavior

It should redirect to the provided `returnUrl` with necessary params.

cc: @zernonia

**Comment by gprieto** [comment]
Have you set up your Notion API key as per the docs ?

https://github.com/supabase/gotrue#external-authentication-providers

**Comment by NagariaHussain** [comment]
> Have you set up your Notion API key as per the docs ?
> 
> 
> 
> https://github.com/supabase/gotrue#external-authentication-providers

Yup, followed the exact steps.

**Comment by gprieto** [comment]
Have you set them up in your Supabase dashboard as per the docs?

https://supabase.com/docs/guides/auth/auth-notion#add-your-notion-credentials-into-your-supabase-project

**Comment by NagariaHussain** [comment]
BTW it is on a managed cloud project, not self hosted supabase.

**Comment by kangmingtay** [comment]
hey @NagariaHussain, can you please drop us a support email [here](https://app.supabase.com/support/new)? We would love to help you get to the bottom of this!
