### ISSUE TITLE
user metadata with magic link 

### ISSUE THREAD

**Issue by rlee1990** [supabase/gotrue#699]
It would be nice to allow for the ability to add user metadata when someone is using the magic link or to make a password option on the signup field to allow for magic links.

**Comment by kangmingtay** [comment]
hey everyone, closing this out because we've added this to gotrue already (https://github.com/supabase/gotrue/pull/506, https://github.com/supabase/gotrue/pull/658)

**Comment by rlee1990** [comment]
> hey everyone, closing this out because we've added this to gotrue already (https://github.com/supabase/gotrue/pull/506, https://github.com/supabase/gotrue/pull/658)

That's nice any clue when it might land on the flutter or dart package?

**Comment by J0** [comment]
Hey @rlee1990,

Not too sure at the moment, but we're looping in the Flutter maintainer: @dshukertjr into the thread so that there's visibility on the feature.

**Comment by dshukertjr** [comment]
@rlee1990 Hopefully not too long from now! We are in the process of making the developer preview version of gotrue-dart to be aligned with gotrue-js rc right now!

**Comment by rlee1990** [comment]
@dshukertjr is there any thing on github for us to follow for progress on this?

**Comment by dshukertjr** [comment]
I just tried calling `signInWithOtp` with some metadata, and it seems like the metadata is not being saved on the server side.  I wonder if it's a server side issue or a client side issue.


Code that I used:
```typescript
    const { error } = await supabase.auth.signInWithOtp({
      email: 'my_email@gmail.com',
      options: {
        data: { name: 'something' },
      },
    })
```

**Comment by rlee1990** [comment]
Same issue I had

**Comment by kangmingtay** [comment]
Yup, good catch @dshukertjr! I've made a PR in gotrue to fix this issue already, it should go out to all supabase projects next week.

One caveat though: If the user has already signed up, you can't use the `data` param to update the user_metadata field. The user will have to update it using the `updateUser` method in gotrue-js

**Comment by rlee1990** [comment]
> Yup, good catch @dshukertjr! I've made a PR in gotrue to fix this issue already, it should go out to all supabase projects next week.
> 
> One caveat though: If the user has already signed up, you can't use the `data` param to update the user_metadata field. The user will have to update it using the `updateUser` method in gotrue-js

Is there a pr or something I can follow so I now when this has been fixed?

**Comment by thecodingpapa** [comment]
Hi, It's been a while. and I have just tried to get the data via magic link and it seems the data does not go through. 
am I missing something??

I develop vite react ts.

```typescript
    const { error } = await supabase.auth.signInWithOtp({ email:email, options: {data: {
      Title: "Вашият магически линк",
      H2: "Магически линк",
      P: "Следвайте този линк, за да влезете в профила си:",
      Link: "Влезте в профила си"
  }} });
```

in Email Templates

```html
<h2>{{ .Data.H2 }}</h2>

<p>{{ .Data.P }}  {{ .Email }} {{ .Data.To }}  {{ .NewEmail }}:</p>
<p><a href="{{ .ConfirmationURL }}">{{ .Data.Link }}</a></p>
```

Thank you.

**Comment by thecodingpapa** [comment]
@kangmingtay Thank you for reply.
will it change to dynamic value when user signin(not only sign up) in the future?
for my use case, I am afraid user somehow change the languages that they set in first signup in my application. 
and email language does not sync with my application.
Thank you again!
