### ISSUE TITLE
Add scopes to Github OAuth

### ISSUE THREAD

**Issue by mateomorris** [supabase/gotrue#70]
Related to this [discussion](https://github.com/supabase/supabase/discussions/397). 

We're using Firebase at the moment to sign up new users with 'Sign in with Github'  _and_ read/write to their repos. This is possible because Firebase lets you [add scopes](https://firebase.google.com/docs/auth/web/github-auth) to the OAuth request so the user can grant additional permissions. 

It looks like the current GoTrue Github scopes are [hard-coded ](https://github.com/supabase/gotrue/blob/4bb48144368a5636abd05c6f0078382968eb10c0/api/provider/github.go#L57) to just be the user's email. 

I've tried doing a second trip to get the additional permissions manually (like [repository.surf's workaround](https://github.com/supabase/repository.surf/blob/10c3a52f3ce004d596f641428f01fd454b35bc00/lib/auth.js#L48)), but I'm hitting a wall. 

I imagine the functionality in `supabase-js` might look like
```
const { user, session, error } = await supabase.auth.signIn({
  provider: 'github',
  providerOptions: {
    scope: 'repo admin:org'
  }
})
```

We're eager to migrate over to Supabase (love it so far), so let me know if there's anything I can do to help with this.

**Comment by awalias** [comment]
hey @mateomorris this is a great idea, we'd def be open to help on this one

**Comment by mateomorris** [comment]
thanks @awalias, I'm gonna take a whack at this with @Beamanator today

**Comment by mateomorris** [comment]
Okay @awalias, ready for your review: https://github.com/supabase/gotrue/pull/77

Once that's ready, I'll open PR's for `gotrue-js` and docs in `supabase`

**Comment by awalias** [comment]
@mateomorris if you want to open a PR in gotrue-js for https://github.com/supabase/gotrue-js/commit/72324e7fb707ec67266c4f4468a64a316f9b98e4

then I will merge it once we have deployed the new backend to prod
