### ISSUE TITLE
supbase-js v2 : signInWithOTP doesn't support the data object in the options params. Breaks i18n templating support.

### ISSUE THREAD

**Issue by mtin79** [supabase/gotrue#735]
# Bug report

## Describe the bug
signInWithOTP doesn't support the data object in the options params. Breaks i18n templating support.

Using supabase-js v2 (latest) seems not able to forward the data object in the option params when using it like here:
```
supabase.auth.signInWithOtp({
      email,
      options: {
        emailRedirectTo: `http://localhost:3000/${language}/app/auth`,
        data: { language: "en" },
      },
```
In order to be able to use GO's template variables to render and appropriate i18n strings in the magicLink Email templates hosted via supabase backend, we need a way to distinguish the user's locale , e.g.: via the data object or similar

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
Use the following snippet when submitting magicLink auth in your webapp:
```
supabase.auth.signInWithOtp({
      email,
      options: {
        emailRedirectTo: `http://localhost:3000/${language}/app/auth`,
        data: { language: "en" },
      },
```
then go to the supabase auth settings and recognize that the following GO template variable is an empty array or null:
{{ .Data }}

## Expected behavior
supabase.auth.signInWithOtp should honour the data object in the options and make it available in the magicLink templates in the supabase auth backend settings.

**Comment by hf** [comment]
Fixed in https://github.com/supabase/gotrue-js/pull/512.
