### ISSUE TITLE
raw_user_meta_data is empty

### ISSUE THREAD

**Issue by rlee1990** [supabase/gotrue#780]
When using the signInWithOtp for the magic link and providing information in data. Checking the data in my trigger function its always empty.

**Comment by rlee1990** [comment]
@kangmingtay are you able to look at this?

**Comment by kangmingtay** [comment]
hey @rlee1990, i noticed you've reopened the issue, can you please provide some reproducible steps for this? thanks!

**Comment by rlee1990** [comment]
> hey @rlee1990, i noticed you've reopened the issue, can you please provide some reproducible steps for this? thanks!

@kangmingtay its in reference to https://github.com/supabase/supabase-flutter/issues/246
