### ISSUE TITLE
Support Native Apple (iOS) and Google (Android) log in 

### ISSUE THREAD

**Issue by wiverson** [supabase/gotrue#782]
# Feature request

I would like to be able to use native Apple/iOS and Google/Android log in options using Capacitor. Plugins already exist which allow for the bulk of the flow:

- Apple (https://github.com/capacitor-community/apple-sign-in)
- Google (https://github.com/CodetrixStudio/CapacitorGoogleAuth)

I would like the option to sign in using the values returned by these plugins.

## Describe the solution you'd like

These plugins both return values that can be used for auth. Both follow a fairly straight-forward flow for then validating the tokens. I would like to be able to use these values to create, validate and log in users.

## Describe alternatives you've considered

Pondered writing these values directly to the tables via server-side code, but that seems like a terrible hack. Unless it's what I should do!

## Additional context

This is one of the biggest features in Firebase (mobile auth support) that I need to be able to use Supabase as a replacement.

**Comment by Jonatthu** [comment]
Why is this ignored for 7 months? :(

**Comment by wiverson** [comment]
So, as an FYI there is some movement on this issue. The full flow is included and working for the Dart/Flutter and CSharp clients. In theory it could be added to the JS client, perhaps with a patch to the JS client (it's just a single REST method to add to hit the server with the native flow data). Or, alternatively, by invoking the GoTrue server-side APIs to send the native Sign in with Apple JWT and nonce to the server and then initializing the JS client with the returned session.

I did a bunch of [PRs for the CSharp](https://github.com/supabase-community/gotrue-csharp) version and made a [demo video](https://youtu.be/S0hTwtsUWcM) of it working in Unity.

This issue should still be open to 1) add the flow to the JS client and 2) write up the docs.

**Comment by J0** [comment]
Hey team,

This should now be possible [with the JS library as well](https://supabase.com/blog/native-mobile-auth). Here's the [corresponding function call](https://supabase.com/docs/reference/javascript/auth-signinwithidtoken)

Going to close for now but feel free to let us know if there are any remaining unresolved issues.

Thanks!
