### ISSUE TITLE
Supabase auth in Node returns error 500

### ISSUE THREAD

**Issue by user72356** [supabase/gotrue#784]
supabase-js version: 2.0.4

I'm trying to build an API using Vercel serverless functions (NOT a Next.js API). I can't seem to be able to retrieve the user object from within the API handler. I'm not sure what I'm doing wrong and I see no meaningful error message in the returned error object or the Supabase log. This is the error object:

```
error:  AuthApiError: Internal server error
    at C:\XXX\node_modules\@supabase\gotrue-js\src\lib\fetch.ts:41:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  __isAuthError: true,
  status: 500
}
```

The Supabase event that appears to be raised by the call (what is `invalid claim: subject missing`?):

```
{"component":"api","error":"invalid claim: subject missing","level":"error","method":"GET","msg":"Unhandled server error: invalid claim: subject missing","path":"/user","referer":"","remote_addr":"xxx.xxx.xxx.xxx","time":"2022-10-29T19:23:01Z","timestamp":"2022-10-29T19:23:01Z"}
```

And the code:

```ts
const supabaseClient = createClient(supabaseUrl, supabaseKey);

const user = await supabaseClient.auth.getUser();
```

user is null and user.error contains the information pasted above.

I have no problem with auth in a Next.js API using createServerSupabaseClient from the auth-helpers-nextjs package.

**Comment by j4w8n** [comment]
At this point in your code, there's no user logged in, so this is an expected error.

`getUser()`, without passing in an `access_token`/`jwt`, will try and find the user by calling `getSession()`. If that isn't successful, then `getUser()` will set the jwt to `undefined`, and pass that into a fetch for `{your-supabase-url}/user`.

**Comment by user72356** [comment]
I'm closing this because I found out the issue was that createClient() does not do any cookie management behind the scenes. It doesn't send/parse an auth cookie, so none was being sent over the wire. As a result the session was blank. The solution was to fork auth-helpers-nextjs and modify it to work with Vercel API functions.
