### ISSUE TITLE
Adding a delete user API

### ISSUE THREAD

**Issue by inian** [supabase/gotrue#79]
Currently there is no Gotrue method for deleting users. 

We do have a delete user on the dashboard, but Copple says it directly removes the user from `auth.users`. We should support this directly in Gotrue so that others can call this via supabase-js and better for our audit trails, etc. 
 
[User request](https://twitter.com/No_Guile/status/1374731465649446919?s=20)

**Comment by icecream78** [comment]
@inian actually, Gotrue has method for deleting users. Delete request to /admin/user/{user_id} will do what you need

**Comment by NathBabs** [comment]
@icecream78 but this method doesn't exist on supabase-js

**Comment by awalias** [comment]
I think we have this already:

[`DELETE /admin/users/{user_id}`](https://github.com/supabase/gotrue/blob/8cb3d71a8c3fcbd9fd0e23586f1203d5861a56a5/api/api.go#L157) but the JWT role needs to be `service_role` or `supabase_admin`

might just need adding to gotrue-js as @NathBabs says

**Comment by nicholaschiang** [comment]
@inian @NathBabs it looks like it does exist (as [documented here](https://supabase.io/docs/reference/javascript/delete-user)):

```javascript
const { user, error } = await supabase.auth.api.deleteUser(
  '715ed5db-f090-4b8c-a067-640ecee36aa0',
  'YOUR_SERVICE_ROLE_KEY'
)
```

**Comment by awalias** [comment]
yes fixed here: https://github.com/supabase/gotrue-js/pull/85
