### ISSUE TITLE
/admin/users/<user_id> admin role?

### ISSUE THREAD

**Issue by tschuehly** [supabase/gotrue#794]
# Improve documentation

## Link 

https://github.com/supabase/gotrue#post-put-adminusersuser_id

## Describe the problem

In the code sample the comment says `// admin role required`

## Describe the improvement

The endpoint cannot be called with a user that has the role set to "admin".
It works when the user has assigned the role "service_role" with the anon_key

Is this problematic to assign a user the role "service_role" so he can set the app_metadata of other users?
I want to move the role management of my application to the app_metadata json

**Comment by J0** [comment]
Hey,

Thanks for the query! The service role is needed to execute `/admin` functions and correspondingly any `supabase.auth.admin`  bindings in the `supabase-js` library. I've amended the README to reflect this.

Role wise,  our recommendation is to not expose the service key (which grants the service role) in the browser. An options which might be worth considering are to expose a server side route which calls the admin route and sets the metadata for you

Hope this helps - let me know if there are further queries.

Thanks!

**Comment by J0** [comment]
Updated the docs to reflect this
