### ISSUE TITLE
Create User Account with Multiple Providers

### ISSUE THREAD

**Issue by burggraf** [supabase/gotrue#81]
# Feature request: Allow a user to log in with multiple providers

## Requirement

A user should be able to log in with more than one provider.  For example:
1.  A user authenticates with Facebook and creates an account in my app.
2. The user decides to quit Facebook.
3. The user wants to log back into my app at a later time, but cannot.  The user should be at minimum be able to "sign in with email" and enter their email address and a password, then verify their email, and get access to their user account.

Another example:
1. User creates an account in my app with Google.
2. User comes back a month later and can't remember which provider they used, so they try to log in with Facebook.  They can't -- because they already have a Google-provider account.
3. The user should be able to authenticate with Facebook now as well, assuming they use the same email address with both providers.

Firebase handles this, albeit not very elegantly.  This is an opportunity to make a much more flexible authentication system.

## Describe alternatives you've considered

At this time, it appears that you'd need to create a separate user account, which would not give the user access to data they have previously created inside my app.

## Additional thoughts

If a change to the core user object isn't possible here, how about a table of user aliases at least, where a user can log in using a provider (even if it's not their "first" or "main" provider) then once logged in the credentials are set to that of the main account.  Not super clean, but might be quicker to implement.

**Comment by Nick-Mazuk** [comment]
I would find this useful as well.

**Comment by burggraf** [comment]
@Nick-Mazuk It appears that this is now working.  I set up an app with multiple providers and I can log in using any of them and it appears to access my same account as long as my email address is the same for each provider.  Works great!
