### ISSUE TITLE
Leaking signup info

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#818]
looks like we're using https://github.com/supabase/gotrue/blob/e187280ed8496d86a99aef4b458a229a6ab5f785/api/errors.go#L18 and https://github.com/supabase/gotrue/blob/e187280ed8496d86a99aef4b458a229a6ab5f785/api/errors.go#L19 in a few places - we should mask them on public endpoints to avoid leaking info about which email/phones are registered

**Comment by kangmingtay** [comment]
closing since we don't plan to obfuscate this in the future
