### ISSUE TITLE
After email change, cannot receive password reset email

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#821]
tested on supabase prod so didn't dig into the logs yet

**Comment by GaryAustin1** [comment]
Several users are hitting this, support is aware.  
It is the actual password reset email process.  The UI reset does not work but magiclink does.  
Also appears region dependent.  I have 2 US-West not working and 2 US-East working.  One customer is at least on EU-West

**Comment by J0** [comment]
Hey,


Tested this and it seems fine now. It's worth noting that it takes a while for emails to reach and on the free tier reset password emails are also being flagged as  spam on gmail.

Closing for now but feel free to reopen if there are issues
