### ISSUE TITLE
signal SIGSEGV: segmentation violation after fresh docker install

### ISSUE THREAD

**Issue by criation** [supabase/gotrue#852]
# Bug report

## Describe the bug

Hej folks,
i just pulled the docker container incl. docker compose file and filled the .env files regarding to my needs, afterwards I started the whole thing with docker-compose up -d.
All containers are up & running but gotrue wont.
SSL Certs are fine as well.

After all Containers are running I went to the gotrue containers logs and found this:

```sh
goroutine 1 [running]:
net/url.(*URL).Query(0xc00004a017?)
        /usr/local/go/src/net/url/url.go:1115 +0x14
github.com/netlify/gotrue/cmd.migrate(0xc0004dfcf8?, {0xc0004dfcd0?, 0x0?, 0x0?})
        /go/src/github.com/netlify/gotrue/cmd/migrate_cmd.go:55 +0x229
github.com/netlify/gotrue/cmd.glob..func4(0x1921d40, {0x1973c10?, 0x0?, 0x0?})
        /go/src/github.com/netlify/gotrue/cmd/root_cmd.go:17 +0x25
github.com/spf13/cobra.(*Command).execute(0x1921d40, {0xc00003e1f0, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1921d40)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
main.main()
        /go/src/github.com/netlify/gotrue/main.go:31 +0x139
{"level":"info","msg":"Go runtime metrics collection started","time":"2022-12-08T18:59:39Z"}
{"level":"info","msg":"received graceful shutdown signal","time":"2022-12-08T18:59:39Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x60fcb4]
```

## To Reproduce

Starting 
Steps to reproduce the behavior, please provide code snippets or a repository:

Started with fresh git clone

## Expected behavior

Not crashing and restarting the gotrue container caused by a SIGSEGV.

## System information

Server:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Docker version 20.10.21, build baeda1f

**Comment by JulianKropp** [comment]
I can reproduce this error:
If the 'POSTGRES_PASSWORD' variable contains a '#' or an '%' this weird looking SIGSEGV accrues. I didn't test it with other special characters.

Also have a look here: https://github.com/golang/go/issues/41153

**Comment by criation** [comment]
This resolved my bug, perfect thanks a lot @JulianKropp
