### ISSUE TITLE
load user after sign-*in* to pull data from triggers 

### ISSUE THREAD

**Issue by lauri865** [supabase/gotrue#861]
Related to: https://github.com/supabase/gotrue/pull/712

Would like to have the same functionality for sign in method. We use database triggers to manipulate user data, but it only works for the sign-up method, whereas the sign in method receives out of date user data.

**Comment by hf** [comment]
@lauri865 What does your trigger do to notice a new sign-in?

**Comment by lauri865** [comment]
Every sign-in triggers a new update on the users table (e.g. updating last_sign_in_at, etc.). So a trigger that listens to UPDATES on the auth.users table picks up new sign-ins.

**Comment by J0** [comment]
For internal tracking: Included as part of Actions RFC

**Comment by J0** [comment]
Hey @lauri865,

Thanks for the query - you can do this now via the [`custom_access_token` hook](https://supabase.com/docs/guides/auth/auth-hooks#hook-custom-access-token)
and add data when a sign in attempt is made say via an `authentication_method` of say email password.

Hope this helps. Going to close this for now but  let us know if there are further issues
