### ISSUE TITLE
Support for Essential Twitter Account for Authentication

### ISSUE THREAD

**Issue by surajondev** [supabase/gotrue#867]
# Feature request

Twitter authentication only works with an elevated Twitter developer account. The elevated account is not easy to get approved and Twitter also does not explain the exact problem with the elevated account request application. So, having support for an essential account will be a good option for indie developers and personal/school/college projects. 

## Is your feature request related to a problem? Please describe.

NO.

## Describe the solution you'd like

I wish that Supabase also supports essential Twitter developers' accounts for Authentication.

## Additional context

Also, the docs for Twitter Authentication on Supbase are outdated. It does not mention having an elevated account as mandatory. Would love to see some updates to the docs.

**Comment by hf** [comment]
@surajondev Please correct me if I'm wrong, but by "essential Twitter account" you mean:

[Twitter Docs; Step Four](https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api#:~:text=step%20four)

> With Essential access, you are only able to make requests to the Twitter API v2 endpoints, and not the v1.1 or enterprise endpoints. You are limited to [500K Tweets/month](https://developer.twitter.com/en/docs/twitter-api/tweet-caps), and unable to take advantage of certain developer portal functionality such as [teams](https://developer.twitter.com/en/docs/developer-portal/team-management) and access to additional App environments.

I believe the Twitter API v2 endpoints are not designed for authenticating users (which is separate from the OAuth 2.0 authorization flow for users). Regardless, from what I can tell you still need to register an app with Twitter, which asks for elevated mode only.

Thus, I'll close this issue but do comment further.
