### ISSUE TITLE
allow whitelisting multiple domains in supabase auth

### ISSUE THREAD

**Issue by d-mok** [supabase/gotrue#87]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to use supabase auth both during development (http://localhost:3000) and production (https://myawesome.domain.com).  But I can only set one 'site url' in the auth setting. I can't enable auth for both domains (dev and prod) at the same time.

## Describe the solution you'd like

I want to be able to add two or more domains to 'site url', so that both the dev and prod domain can use supabase auth at the same time.

## Describe alternatives you've considered

During development, I need to switch supabase auth 'site url' to my dev domain (http://localhost:3000), but this brings down my production website since people can't login anymore.

**Comment by rasreee** [comment]
^ Bump - my team would very much appreciate support for this.

**Comment by awalias** [comment]
solved with `URI_ALLOW_LIST`

you need to however use exact URIs (unlike the `SITE_URL` param which allows a catch all domain)

and you can specifiy where you want to redirect to using supabase-js redirectTo: https://supabase.io/docs/reference/javascript/auth-signin#sign-in-with-redirect (there is an open bug being worked on [here](https://github.com/supabase/gotrue-js/issues/65))

and set it the dashboard here:
![image](https://user-images.githubusercontent.com/458736/118761386-e3bf9e80-b8a6-11eb-96e8-c82c9a21e9a8.png)

**Comment by awalias** [comment]
note that catch all secondary domains might also be in the pipeline: https://github.com/supabase/gotrue/issues/99

**Comment by KoltonG** [comment]
Any chance of wildcard support for this as well? This would be for dynamic preview branches that share a subdomain like Vercel preview branches?
