### ISSUE TITLE
Token endpoint grant refresh_token should read from HttpOnly cookie

### ISSUE THREAD

**Issue by wmaurer** [supabase/gotrue#873]
# Feature request

## Is your feature request related to a problem? Please describe.

The GoTrue password grant type flow sets two HttpOnly cookies, one each for the `access_token` and the `refresh_token`. A custom API endpoint can subsequently read the `access_token` cookie and verify the validity of the token without the client having sent it explicitly as a header bearer token. As a result, the client does not have to save the `access_token` in local storage. This helps against XSS attacks because when the `access_token` is only stored as an HttpOnly cookie, it cannot be read by client side script code.

Whilst this works, one piece of the puzzle is missing: the `refresh_token` grant type flow expects the refresh_token as a parameter in the body of the POST request. This means that the client must store the `refresh_token` in either memory (too fleeting) or in local storage.

However in the case of a web client, the token endpoint also receives the `refresh_token` HttpOnly cookie, in which case it is not necessary to send the `refresh_token` in the body of the POST request.

## Describe the solution you'd like

The fact that the HttpOnly cookies are set should be properly taken advantage of.
The token endpoint implementing the `refresh_token` grant should check the `refresh_token` HttpOnly cookie, in which case the body `refresh_token` parameter can be ignored and, in fact, be optional.

## Describe alternatives you've considered

The alternative is to store the `refresh_token` in local storage, which can increase the severity of an XSS attack (i.e. someone could steal the refresh_token).

**Comment by hf** [comment]
Hi @wmaurer, the HttpOnly cookies are only there for backward compatibility only and are not consumed by GoTrue. This is because GoTrue is used in non-browser environments too which do not have browser-like cookie handling.

I'll close this issue for now.
