### ISSUE TITLE
signInWithOtp - First OTP always expired

### ISSUE THREAD

**Issue by florianwalther-private** [supabase/gotrue#876]
# Bug report

## Describe the bug

When I use `signInWithOtp`, using an actual OTP and not the magic link, the first code is almost always expired when I use it in `verifyOtp`. Only when I request a new code (using `signInWithOtp` again), do I get a working one. It happens in development and production.

## To Reproduce

1. Sign in with OTP (this happens inside a modal dialog):

``` 
const { error } = await supabaseClient.auth.signInWithOtp({
    email: email,
    options: { data: { ...Object.fromEntries(gameStats) } }
});
```

2. Verify the OTP (this happens in another modal):

```
const { error } = await supabaseClient.auth.verifyOtp({ email: emailToVerify, token: otp, type: "magiclink" });
```

3. The verify method throws an error (expired OTP) -> repeat steps 1 & 2 in the exact same way, now it works (the second OTP is valid).

## Expected behavior

The first OTP should work.

## System information

- OS: Windows
- Browser: Chrome
- Versions: 
- "@supabase/auth-helpers-nextjs": "^0.5.2"
- "@supabase/auth-helpers-react": "^0.3.1"
- "@supabase/supabase-js": "^2.2.1"

## Additional context

I'm using React + NextJS together with Supabase's helper packages.

**Comment by kangmingtay** [comment]
Hi @florianwalther-private, this is because if a user invokes `signInWithOtp` for the first time, the "type" used should be "signup" instead of "magiclink". Currently, the workaround for this would be to do this:

```
// try with type: magiclink first
try {
  const { error } = await supabaseClient.auth.verifyOtp({ email: emailToVerify, token: otp, type: "magiclink" });
  if (error) throw error
} catch (error) {
  // if there's an error, then try type: signup since it could be the user's first time calling `signInWithOtp` 
  const { error } = await supabaseClient.auth.verifyOtp({ email: emailToVerify, token: otp, type: "signup" });
}
```

We do plan to change this behaviour in the future so this workaround isn't necessary by introducing a generic type for verifying email OTPs regardless of whether the user exists or not. But until that lands, you'll need to handle the error returned for now.

**Comment by florianwalther-private** [comment]
Thank you for the clarification. Please implement this generic identifier!

By the way, is it normal that the old OTP is still valid after calling `signInWithOtp` a second time (with `shouldCreateUser: false`)?

**Comment by kangmingtay** [comment]
@florianwalther-private hmm can you provide more details how that happens?

If you call `signInWithOtp` for the first time with `shouldCreateUser: false`, then no user will be created if the user doesn't exist yet so there won't be an OTP sent out. 

Setting the `shouldCreateUser` param just prevents the user from being created. If you called `signInWithOtp` before that and a user is created already, then calling it again with the param set to false won't do anything.

**Comment by florianwalther-private** [comment]
@kangmingtay I use `signInWithOtp` (with `shouldCreateUser: true`) to sign up a user and `signInWithOtp` with `shouldCreateUser: false` as the "resend verification email" button because you don't provide this feature out of the box.

**Comment by alphakex2** [comment]
@florianwalther-private Thanks Florian for the quick reply, Kindly help clarify this for me...A user signs up using 
const { error, data } = await supabase.auth.signUp({
      email: values.email,
      password: values.password,
    }) 
a confirmation email is sent to the email provided with a 6 digit token which the new user tries to verify using 
 const { data } = await supabase.auth.verifyOtp({
        email,
        token: otp.join("").toString(),
        type: "signup",
      }) 
and the user gets a token expired, how do I work around the issue? since I'm not using magic links

**Comment by kangmingtay** [comment]
hey @florianwalther-private, the generic identifier has been implemented since this release (v2.40.3) and we'll be looking to roll it out to all projects on Supabase soon.

**Comment by kangmingtay** [comment]
hi @alphakex2, you can do a couple of sanity checks on your end:
1. Check that the value of `otp.join("").toString()` matches the OTP sent in the email
2. Check your project's auth logs and inspect the `/verify` routes to see if your email client has accidentally prefetched the email link sent in your email. 

If you're still facing issues with this, please contact us at support through the dashboard.

**Comment by altryne** [comment]
@kangmingtay hey, following up on this, as I've seem to find out about the same issue happening to all my new clients. 

1) was the generic identifier implemented? I don't see any mention of one in the docs. 

2) the highest NPM package version goes up to v2.21 as of the time of this writing. What package did you mean by v2.40? 🙏

**Comment by altryne** [comment]
Ok found it. (it was https://github.com/supabase/gotrue/pull/885 )

This pull requests introduces a generic identifier called `email` that works for both new and existing users, without the need for the above workaround. 

It's not documented yet (@kangmingtay where whould I open a ticket for documentation?) 🙏 

To solve the above, replace `await supabaseClient.auth.verifyOtp({ email: emailToVerify, token: otp, type: "magiclink" });` with `await supabaseClient.auth.verifyOtp({ email: emailToVerify, token: otp, type: "email" });` and it should work for both new and existing customers

**Comment by MartinzJoy** [comment]
Hi
I'm also getting this issue in 18th April 2025 on production. I don't have this issue on my local environment though.
I did everything suggested in the docs and in this _issue_. I'm using `supabase/ssr` version **0.5.2**, `supabase/supabse-js` version **2.49.4** on NextJS 14

**Comment by nextglabs** [comment]
Having a similar issue as of April 23rd 2025

**Comment by Larront** [comment]
I'm also having this issue in production but not locally
