### ISSUE TITLE
Rename Azure to Microsoft Account?

### ISSUE THREAD

**Issue by hyperknot** [supabase/gotrue#877]
# Feature request

## Is your feature request related to a problem? Please describe.

Is the Azure integration the same as what other providers call "Microsoft Account"? For example Auth0 has this page: 
https://marketplace.auth0.com/integrations/microsoft-account-social-connection

## Describe the solution you'd like

If so, can we use the proper name "Microsoft Account" and logo? In the general public almost no one knows that Azure is, nor they are familiar with the logo especially.

How it should look:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/494223/209931045-7e881e90-b648-46f1-83b4-4767c0049d1e.png">

**Comment by J0** [comment]
Hey Hyperknot,

Thanks for pointing this out! AFAIK, applications make use of Azure Active Directory for OAuth sign ins so they should generally be the same. Agree that the general population might not be as familiar with Azure - not sure about the developer population though. 

As this would require renaming across the board it might take some time before we can get to this  - I'm going to close this issue for now but will open an internal ticket to track this.

**Comment by PoorRican** [comment]
Has there been any progress on this?
