### ISSUE TITLE
Passkey support

### ISSUE THREAD

**Issue by felixb1010** [supabase/gotrue#879]
Sign in with passkeys
[resources](https://fidoalliance.org/passkeys/)

**Comment by J0** [comment]
Hey all, 

This should come together with Webauthn support - please track #92 for updates on both Webauthn (MFA) and Passkeys

**Comment by zdarin** [comment]
If someone interested in Passkey here basic setup by @oouazize and reduced code for basic integrations by me @zdarin 
<br> [Supabase, Simplewebauthn for Passkey, Nextjs 15, Tailwind v4, Shadcn](https://github.com/zdarin/supabase-passkey-simplewebauthn)
