### ISSUE TITLE
Auth webhook with link

### ISSUE THREAD

**Issue by gawlk** [supabase/gotrue#88]
Hi !

Would it be possible to have add a webhook on the auth setting so that we could send the email ourselves with the link passed as a parameter ?

Currently auth are different from my other emails because they're cannot be sent to same way my other emails are. I'm sure that I'm not the only one in this situation. Also, they're more frequently sent to spam than my normal ones because of the link and the smtp connection.

**Comment by awalias** [comment]
hey @gawlk you can use custom SMTP server on the supabase dashboard and also set the template (any html/css) from there (both in Auth > Settings)

![image](https://user-images.githubusercontent.com/458736/118761897-d22ac680-b8a7-11eb-8e2a-d550cf491084.png)
![image](https://user-images.githubusercontent.com/458736/118761863-c50dd780-b8a7-11eb-9f45-792d122bce74.png)
 
the reasons I think webhook might work better is:
- can replace the link with one on your own domain which redirects to the actual one
- can keep your templates under version control or in the same system that you currently manage
- i18n of templates https://github.com/supabase/gotrue/issues/80

**Comment by gawlk** [comment]
I completely agree with the pros of a webhooks

**Comment by kangmingtay** [comment]
Hey @gawlk, we just merged a PR that's gonna help with this [here](https://github.com/supabase/gotrue/pull/133). Basically, you can now generate the email action links via the `/admin/generate_link` endpoint, and send the link via your own dedicated email service provider (e.g. Sendgrid, etc...). We're testing it in our staging environment now and will release it soon! Hope this helps!
