### ISSUE TITLE
Confirmation of E-Mail Change has no Effect

### ISSUE THREAD

**Issue by ccssmnn** [supabase/gotrue#896]
# Bug report

Using the E-Mail provider, I cannot change the email that is used to sign-in the user. A mail with a confirmation link is sent, but this link does not lead to a change of the auth email address. It does sign out the user, but the old email address needs to be used to sign in.

## To Reproduce

See also the screen recording below.

1. Create a user with email + password
2. Perform an update with `supabase.auth.updateUser({ email: newEmail })`
3. The user will receive an email with the confirmation link. Press the link.
4. You will be redirected to the frontend-URL and signed out.
5. ⚡️ you have to sign in with the old email address

## Expected behavior

The new and confirmed email should work for sign in.

## Screenshots

https://user-images.githubusercontent.com/29344072/213483584-01b1ff7b-1a2b-40a0-aaa7-54d42d675e5e.mov

## System information

- Supabase CLI v1.33
- Supabase JS 2.4.0

I have the same behavior in my deployed instance.

**Comment by kangmingtay** [comment]
hey @ccssmnn, i'm not able to reproduce the bug described above, but you should be able to take a look at your project's logs to see what's causing the error:

* Auth logs: https://app.supabase.com/project/_/logs/auth-logs
* Postgres logs: https://app.supabase.com/project/_/logs/postgres-logs

**Comment by ccssmnn** [comment]
@kangmingtay thanks for pointing me to the logs. The Auth logs show the failed `/verify` request. The Postgres logs are pointing me to **my** error within a trigger (`after update on auth.users`).
