### ISSUE TITLE
Can't verify email change OTP code - "User not found"

### ISSUE THREAD

**Issue by nicolantean** [supabase/gotrue#897]
# Bug report

## Describe the bug

After creating a user with the **signInWithOtp** method using a phone and then adding an email for that user using **updateUser**, I get a **User not found** error while calling **verifyOTP** method with the email added before.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a user using `SupabaseClient.auth.signInWithOtp(phone: "XXXXXXXX");`
2. Verify the phone with `SupabaseClient.auth.verifyOTP( phone: "XXXXXXXX", token: "XXXX", type: OtpType.sms);`
3. Add an email for the user calling `SupabaseClient.auth.updateUser(UserAttributes(phone: "XXXXXXXX", email: "XXX@XXX.XX"));`
4. Verify the OTP code sent to the email for confirmation using `SupabaseClient.auth.verifyOTP(email: "XXX@XXX.XX", token: "XXXX", type: OtpType.emailChange);`
5. See an exception `AuthException(message: User not found, statusCode: 404)`

## Expected behavior

As the users table on the auth schema has **email_change** and **email_change_sent_at** values updated with the email added before, the verifyOTP has to find the email and respond successfully.

## System information

- Version of supabase_flutter: 1.2.2
- Version of Flutter: 3.3.6

## Additional context

Sometimes after updating the same email multiple times on the same user I could verify it successfully but only a few times.

**Comment by mirland** [comment]
Hi @dshukertjr @kangmingtay, we are a bit stuck with that. Do you have any news? Can we help with something? 

Thanks for the hard work and the great tool!

**Comment by kangmingtay** [comment]
Hey @nicolantean and @mirland, I've made a PR to fix this bug already. Thanks for reporting this!

**Comment by nicolantean** [comment]
Thank you so much @kangmingtay for the fix! I've tried the same flow but it is still not working. What do I have to do to use the latest version of gotrue on my flutter project? Because I couldn't find the gotrue version that is using my project.

**Comment by mirland** [comment]
Hi, @kangmingtay thanks for the fix! I'm currently testing it again and I'm having the same issue. How can I update supabase to fix the issue? Do you know if this fix has already been released on Supabase? I'm not finding documentation about it

**Comment by kangmingtay** [comment]
hey @mirland, apologies for the late reply but in the future, it would be great if you can contact us through [support](https://app.supabase.com/support/new). It's quite challenging to keep up with the github notifications and we have a support team that helps with making sure that your questions reach us.

**Comment by mirland** [comment]
Yes, thanks! The support team gave me the suggestion! I tried it again and it worked Thanks again
