### ISSUE TITLE
redirectTo either ignored or stripped of /#/

### ISSUE THREAD

**Issue by nstrelow** [supabase/gotrue#90]
### Problem

I am getting unexpected behavior using the redirectTo in gotrue-dart (I added it through a PR). The URL is constructure with `&redirectTo=<url>`.

I have 2 scenarios.

SiteUrl: `https://someapp-something.codemagic.app/#/`
redirectTo: `http://localhost:3000/#/`
**Redirects to:**  `https://someapp-something.codemagic.app/#/`

SiteUrl: `http://localhost:3000/#/`
redirectTo: `http://localhost:3000/#/`
**Redirects to:** `http://localhost:3000/`

In both cases I would want it to redirect to  `http://localhost:3000/#/` including `/#/`.

**Comment by awalias** [comment]
I think the server may be overwriting `redirectTo` with the value passed by the browser in the `referer` header (in this case presumably `http://localhost:3000/`

this is a bug, we should prioritize `redirectTo` if it's set

**Comment by KrisCoulson** [comment]
@awalias I have also been running into this issue. It looks like there are other open tickets regarding the same issue.
https://github.com/supabase/gotrue-js/issues/65

**Comment by nstrelow** [comment]
Any chance this will be able to get fixed?

Thanks for the hard work and all, don't feel pressured ❤️

**Comment by awalias** [comment]
@icecream78 do you want to take a look at this one? we need to make sure `redirect_to` takes priority over `Redirect` Header if set

**Comment by icecream78** [comment]
@awalias yeah. I'll look on it

**Comment by icecream78** [comment]
@nstrelow please add extra info about your problem.
Have you inserted your redirect_uri in settings? 
![image](https://user-images.githubusercontent.com/20445149/118361412-0777a180-b594-11eb-8672-6c84a9c64a6c.png)

Because I've checked flow with generating magic link + verification it and Gotrue redirected me by provided redirectTo field's value

**Comment by nstrelow** [comment]
@icecream78 I somehow have not seen the "Additional Redirect URLs". Was it always there? If added later on, I have not checked it out yet, but will do now.

Am I correct to assume all my redirects need to be listed, otherwise it won't work?

**Comment by icecream78** [comment]
3 month ago I've added logic for restricting redirect url according to that list, but I don't know when UI was updated to handle this setting.
And yes, you are correct. If redirect url distincts from site url, so you need add it to list. 
@nstrelow please try again with filled setting and say results

**Comment by emschwartz** [comment]
The behavior I’ve observed is that the paths on the redirects seem to be
ignored. I have the base URL listed in the allowed URLs but redirecting to
a specific page didn't work.

**Comment by nstrelow** [comment]
@icecream78 I will try again now, but I had the problem @emschwartz is having as well.

My url needs to have a `/#/` attached for parsing correctly.

I will try it and report back

**Comment by nstrelow** [comment]
@icecream78 I am still having the same behavior, even though I have defined the "Additional redirect URLs". I think this comes from (as mentioned by @emschwartz) stripping the URL path.

SiteUrl: http://localhost:3000/#/
redirectTo: http://localhost:3000/#/
**Redirects to:** http://localhost:3000/
Somehow the url without the `/#/` path is still allowed. I would expect `http://localhost:3000/` to be not allowed, because it does not match SiteUrl or additional redirect urls.

SiteUrl: https://someapp-something.codemagic.app/#/
redirectTo: http://localhost:3000/#/
**Redirects to:** https://someapp-something.codemagic.app/#/
I think here my valid redirectTo `http://localhost:3000/#/` fails, because it compares `http://localhost:3000/#/` to the additional redirect URLs and those probably have removed the URL path `/#/`. Because redirectTo does not match it will be redirected to the SiteURL. Am I correct?

A working example:
SiteUrl: https://someapp-something.codemagic.app/#/
redirectTo: http://localhost:3000/
**Redirects to:** http://localhost:3000/
This actually works, because there is no URL path specified.

@icecream78 Is the URL path ignored or removed at some point? If yes, this would have to be revised, to allow paths such as `/#/` which is necessary for some form of webapps.

**Comment by icecream78** [comment]
Redirect url doesn't stripped or normalized in any way. When request comes only thing that matter is that if url in allowed list or not.
One thing is weird in that process. Redirect url in verify constructs by hardcode adding # char + encoded payload. In your case redirect url looks like http://localhost:3000/#/%23access_token.....  I've written code for handling that case but that fix doesn't coordinately help you. 
Also I've written few tests with input data you've provided https://github.com/icecream78/gotrue/commit/c0f3c3e7187305b0828cbc81da55e57c86c947b3 but they all pass.
Maybe I've missed something and it will be nice if somebody point me in it

**Comment by emschwartz** [comment]
Does that mean that the full URL, including the path, needs to be in the
allowed list in order for it to work?

If so, would it be possible to change it to only look at the domain? That
would allow redirecting to pages with dynamic paths. It also shouldn't be
any different from a security perspective because all of the paths are
under the control of whoever controls the domain.

>

**Comment by nstrelow** [comment]
@icecream78 I think I have to apologize. I added the redirectTo option to the dart SDK. And I did not encode the URL to use it as a parameter. So probably that URL escaping messed it all up. Sorry and thanks for investigating.

With that my stuff seems to work now. Will upload a fix soon.

PS: What @emschwartz suggests sounds sensible, if there is no case where somebody would not control a domain but only a path on it.

**Comment by icecream78** [comment]
@emschwartz it's not necessary to include full URL in allowed list, because only domain part is essential for redirect url correctness. If domain part is in allowed list - redirect url will pass, if it is not - redirect will be made to site url value

**Comment by icecream78** [comment]
@nstrelow no problem. I'm glad that I helped you=)

**Comment by emschwartz** [comment]
@icecream78 I just tried it again and the redirect with a path is definitely not working for me. I have localhost:3000 and another domain listed in my allowed domains. When I set the redirect value to `http://localhost:3000/some_path`, the link in the email has `...&redirect_to=http://localhost:3000/` and it's the same when I use the proper domain.

In the console I see the warning `Attempt to set a forbidden header was denied: referer`.

**Comment by awalias** [comment]
> If so, would it be possible to change it to only look at the domain? That
> would allow redirecting to pages with dynamic paths. It also shouldn't be
> any different from a security perspective because all of the paths are
> under the control of whoever controls the domain.

the difficulty here is that in some cases, the mobile URIs/Deep links are reversed e.g. `com.company.mobiletestapp://oauth`, we couldn't come up with a way to parse the strings that guarantees security

so we chose for now to force Additional URIs to be **exact** 

now there is a bug in the client library at the moment which is what @emschwartz is experiencing:

`Attempt to set a forbidden header was denied: referer` since browsers no longer allow you to set the Referer header manually.

The proposed fix is to:
a) change the client use `redirect_to` query param instead of setting the Referer header
b) change the back end to prioritize the `redirect_to` query param over the Referer header

I have raised a [separate issue](https://github.com/supabase/gotrue/issues/99) for being able to add arbitrary paths to urls that are not the primary domain (aka. SITE_URL) - it will require some more thought

**Comment by awalias** [comment]
@nstrelow do you require the `/#/`? Gotrue appends it's parameters using the same fragment delimiter `#`. (will redirect to `SITE_URL/#access_token=x&expires_at....`) Which is presumably why it's currently being stripped

**Comment by nstrelow** [comment]
@awalias This part is working now as expected ^^.  Redirect to `http://localhost:3000/#/`
I was able to fix it, by encoding the url parameter `redirectTo`.  I added this to the gotrue-dart SDK, so I introduced the feature and bug. Sorry for that.

**Comment by simonh1000** [comment]
I can see that this broadly works for the Site Url but it does not seem to work for the additional redirect urls. I want to have a variable in the redirect, so it is not possible to provide a `exact` url
