### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by xluk9** [supabase/gotrue#904]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to have a custom authentication function when self-hosting. I was planning to use it in my organization, but they require LDAP Auth. It would be great to sign-in just the username, for example changing a little bit from the documentation:
```js
async function signInWithEmail() {
  const ldapAuthSuccess = await customSignInFunction(username, password)
  if ( ldapAuthSuccess) {
    const { data, error } = await supabase.auth.signInWithUsername({ 'username' : username })
  } else {
  // Return error
 }
}
```

This way the credential are verified by an external function. If that function is successful we can tell supabase to generate the JWT token just with the username without password ( or whatever field we prefer).

For reference, Laravel Sanctum, provide a similar functionality, where it is possibile to issue token just with user model.
https://laravel.com/docs/9.x/sanctum#issuing-api-tokens
```php
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
 
Route::post('/sanctum/token', function (Request $request) {
    $request->validate([
        'email' => 'required|email',
        'password' => 'required',
        'device_name' => 'required',
    ]);
 
    $user = User::where('email', $request->email)->first();
 
   // Custom auth logic
    if (! $user || ! Hash::check($request->password, $user->password)) {
        throw ValidationException::withMessages([
            'email' => ['The provided credentials are incorrect.'],
        ]);
    }
 
    // Issue token when successful custom login
    return $user->createToken($request->device_name)->plainTextToken;
});
});
```

I'm willing to extend supabase, but I need to study a little more about the codebase. It will take time.

**Comment by hf** [comment]
Could you elaborate more on what you need to do with LDAP? This is fairly uncommon nowadays, as most use cases can be covered by SSO with SAML (which is supported).

**Comment by xluk9** [comment]
I would like to authenticate via LDAP, given the LDAP settings in some conf file (hostname, cn....).
My organization has self-hosted Microsoft AD without SSO/SAML. How should I proceed?

To add to these, some users are from AD and some other are simple database users. How to proceed? That's why it is crucial that you provide API to do custom auth, as given by example with Laravel. 

My current API works this way
1. Authenticate through LDAP
2. If it fails, then authenticate via database username/password.

How should I do it?

**Comment by xluk9** [comment]
Any updates on this?

**Comment by hf** [comment]
We do not plan on working on LDAP, there's almost zero asks for it. 

Feel free to draw up a plan on how that might work and the team can help review it and guide you with implementation once we feel comfortable with it.

Some support for custom authentication systems will be landing with anonymous sign-ins soon, so that may unblock you.

I'll close this issue as not-planned, but please continue commenting on it or open a new one with your implementation plan suggestion.
