### ISSUE TITLE
Universal single OTP verification method that works for new users and existing users.

### ISSUE THREAD

**Issue by catdoglt** [supabase/gotrue#905]
# Feature request

Universal OTP verification call for **signup** and **magiclink** methods.

`supabase.auth.verifyOtp({ email, token, type: 'signupandmagiclink'})`

## Is your feature request related to a problem? Please describe.

At the moment on your email providers settings if you have "Confirm email" toggled(which is default). On the first login attempt users will be sent "Confirm your Signup" email, the problem is that - that OTP only works with this method:
`supabase.auth.verifyOtp({ email, token, type: 'signup'})`, because of that you will have to build 2 extra screens - one for users that want to create new account, one for verifying account creation OTP.

It's an extra unecessary logic that is not needed and could create confusion for users and developers, what if user forgets that he already created account, goes to "create account" screen and requests code, receives magic link code, but this time this magic link code no longer works for `type: 'signup'` and user will receive generic `OTP code is invalid or expired` error.

## Describe the solution you'd like

All we need is a simple `verifyOtp()` method that works for both "signup" and "magiclink" codes.

## Describe alternatives you've considered

This can be prevented by toggling `Confirm email` option to false in the auth provider settings, but:
1. What if you want to verify email signups with passwords
2. Developers might not know that they need to toggle it, because by definition OTP is email verification anyways?
3. You still want to send the "Confirm your signup" email template with some "Welcome to my app message" instead "here is your one time code"

## Additional context

Also, I noticed apart from "signup" and "magiclink" there is a "recovery" type, if you are using passwordless sign in, what are you exactly recovering?

![Screenshot 2022-11-02 at 17 02 43](https://user-images.githubusercontent.com/20464922/199554286-0fb46d4f-c3a6-47ed-b801-f9487d41ef5d.png)

**Comment by Lewitje** [comment]
It would be amazing to have this feature.

**Comment by petedavisdev** [comment]
I would love this feature too, but for now, here's a workaround which works for me:
```
const logInResponse = await supabase.auth.verifyOtp({
	email: email.value,
	token: token.value,
	type: 'magiclink',
});

if (logInResponse.error) {
	const signUpResponse = await supabase.auth.verifyOtp({
		email: email.value,
		token: token.value,
		type: 'signup',
	});
}
```

**Comment by kangmingtay** [comment]
Hey @Lewitje, @petedavisdev  and @catdoglt, we have this already, you can use the `type: 'email'` which would cover both `magiclink` and `signup` verification types.

**Comment by IM-Deane** [comment]
> Hey @Lewitje, @petedavisdev and @catdoglt, we have this already, you can use the `type: 'email'` which would cover both `magiclink` and `signup` verification types.

Strange, I just hit this error in my development environment while on `@supabase/supabase-js@^2.21.0`


After getting the code from the magic link email, we attempt to verify it like so:
```typescript
else if (type === 'email') {
        response = await supabase.auth.verifyOtp({
          email: userEmail,
          token: data.token,
          type,
        });
      }

if (response.error) throw response.error;
```


And then get the following error in the browser:
<img width="369" alt="Screenshot 2023-05-11 at 12 42 45 AM" src="https://github.com/supabase/gotrue/assets/59102133/f5728c79-d350-4fba-853a-f6fcde5f7564">


From the screenshots below you can tell the access code matches the request payload:
<img width="539" alt="Screenshot 2023-05-11 at 12 42 11 AM" src="https://github.com/supabase/gotrue/assets/59102133/dcaba06f-6f5e-45c2-affe-fece819c4580">

<img width="754" alt="Screenshot 2023-05-11 at 12 40 16 AM" src="https://github.com/supabase/gotrue/assets/59102133/86010164-e2bf-43ce-833f-e98d562c8c2e">

**Comment by kangmingtay** [comment]
hi @IM-Deane, a quick sanity check would be to see if the `auth.users.confirmation_token` or `auth.users.recovery_token` columns are populated before you call the `verifyOtp` method. If you are calling the `signInWithOtp` method for a new user, the `confirmation_token` column should contain a value. If it's an existing user, the `recovery_token` column should contain a value. There are also the `confirmation_sent_at` and `recovery_sent_at` columns which you can check to see if the verification request is being made outside of the valid window.

**Comment by landsman** [comment]
> Hey @Lewitje, @petedavisdev and @catdoglt, we have this already, you can use the `type: 'email'` which would cover both `magiclink` and `signup` verification types.

oh, thank you for this reply! you saved me. I did not find it in code...

**Comment by willieee802** [comment]
> > Hey @Lewitje, @petedavisdev and @catdoglt, we have this already, you can use the `type: 'email'` which would cover both `magiclink` and `signup` verification types.
> 
> @kangmingtay Strange, I just hit this error in my development environment while on `@supabase/supabase-js@^2.21.0`
> 
> After getting the code from the magic link email, we attempt to verify it like so:
> 
> ```ts
> else if (type === 'email') {
>         response = await supabase.auth.verifyOtp({
>           email: userEmail,
>           token: data.token,
>           type,
>         });
>       }
> 
> if (response.error) throw response.error;
> ```
> 
> And then get the following error in the browser: <img alt="Screenshot 2023-05-11 at 12 42 45 AM" width="369" src="https://user-images.githubusercontent.com/59102133/237595585-f5728c79-d350-4fba-853a-f6fcde5f7564.png">
> 
> From the screenshots below you can tell the access code matches the request payload: <img alt="Screenshot 2023-05-11 at 12 42 11 AM" width="539" src="https://user-images.githubusercontent.com/59102133/237595495-dcaba06f-6f5e-45c2-affe-fece819c4580.png">
> 
> <img alt="Screenshot 2023-05-11 at 12 40 16 AM" width="754" src="https://user-images.githubusercontent.com/59102133/237595008-86010164-e2bf-43ce-833f-e98d562c8c2e.png">

I am getting the same error. I called signUp with email and password, and I received the signup email with 6-digit otp. But the verify otp never succeed
```typescript
    const { data, error } = await this._client.auth.signUp({
      email: email,
      password: password,
    });
    const { data, error } = await this._client.auth.verifyOtp({
      email: email,
      token: code,
      type: 'email',
    });
```

BUT, if I click on the confirmation url with that token hash, the user is confirmed which I believe passed the verify otp process.

Any suggestions ?
