### ISSUE TITLE
Provide the option to disable auth.signup and make it available server-side only

### ISSUE THREAD

**Issue by hugonteifeh** [supabase/gotrue#906]
# Feature request

## Is your feature request related to a problem? Please describe.

In many cases, it's very useful, at times even necessary, to make certain sensitive actions exclusive to the server such as signing up and deleting a user.

## Describe the solution you'd like

This could probably be broken down into two separate but closely related feature requests:

1. Expose a `signup` function on `auth.admin` that sends confirmation emails, or update `auth.admin.createUser` to let it send confirmation emails.
2. Allow the option to disable `auth.signup`, that is to disallow users from directly signing up.

## Describe alternatives you've considered

I've considered `auth.admin.createUser` but this function doesn't send confirmation emails.

I've also considered `auth.signup` on the server, but this is obviously not optimal as Supabase won't able to differentiate between a request coming from the server vs one coming from a user.

🌳🌿 Keep up the BEAUTIFUL work 🌳🌿

**Comment by kangmingtay** [comment]
hey @hugonteifeh, have you seen the [`generateLink` method](https://supabase.com/docs/reference/javascript/auth-admin-updateuserbyid) ? It won't send the email for you but it returns an email link which you can send via your own custom email provider.

**Comment by hugonteifeh** [comment]
@kangmingtay Thank for your reply. Yes I'm already aware of `generatedLink`. But then:
1. One would need to set up and maintain a custom email provider just for this little feature.
2. This still does't prevent sign ups directly from the front end, right?

**Comment by kangmingtay** [comment]
> 1. One would need to set up and maintain a custom email provider just for this small feature.

Yeah you're right, this requires one to setup and maintain a custom email provider which isn't ideal. Is there a reason why you're opting to call the signup function from the server-side instead? 

> 2. This still doesn't prevent signups directly from the front end, right?

It does because it's an admin endpoint which means that you can toggle the option to disable signups so that the signup method is blocked.

**Comment by hugonteifeh** [comment]
> Yeah you're right, this requires one to setup and maintain a custom email provider which isn't ideal. Is there a reason why you're opting to call the signup function from the server-side instead?

It gives the system the ability to check business rules on the server before allowing users to sign up.

> It does because it's an admin endpoint which means that you can toggle the option to disable signups so that the signup method is blocked.

Interesting!

**Comment by kangmingtay** [comment]
Hey @hugonteifeh, i'll be closing this issue for now since the generate link endpoint seems to help with this.
