### ISSUE TITLE
Cannot use OAuth after signing up with UN/PW

### ISSUE THREAD

**Issue by mchappeldev** [supabase/gotrue#911]
# Bug report

## Describe the bug

Using OAuth after signing up with Magic Link or UN/PW results in: 
`ERROR: duplicate key value violates unique constraint "users_email_partial_key" (SQLSTATE 23505).`

If you signup with OAuth, and then set a password or use a magic link, everything works as expected, but if you do things the other way around you get the error. 

For clarity:
Sign Up with Google or Microsoft OAuth -> Add Password/Use Magic Link -> User logs in correctly
Sign up with Google OAuth -> Try to Sign-in with Microsoft OAuth (same email) -> User logs in correctly
Sign up with Password/Magic Link -> Try to Sign-In with OAuth -> 500: Database error saving new user

## To Reproduce
1. Set up User Management Starter
2. Add Google or Microsoft OAuth
3. Send user a magic link to login (creating user in Users).
4. Use signInWithOAuth to try and authenticate a user with the same email:

```
const { error } = await supabase.auth.signInWithOAuth({
provider: providerVar,
});		
```
5. See error in response and in Auth Logs.

Alternatively, if you do this the other way around it works:
1. Have user signup/signin with OAuth
2. Add a PW or use a Magic Link to Login
3. User Authenticates correctly. 

And Lastly:
1. Have user signup/signin with Google OAuth
2. Use Microsoft OAuth to Login
3. Supabase ties the login to the existing account with the same email. 

## Expected behavior

I'd expect OAuth to associate to the same email as the UN/PW User, just like using different OAuth Providers does. 

## Additional context

The use case here is for us to be able to keep User Signups disabled so that we can allow OAuth signups, but only with invited users. Or to allow existing users to switch to OAuth Login. This is possibly related to #434.

**Comment by kangmingtay** [comment]
Hi @mchappeldev, I'm unable to reproduce this:

Sign up with Password/Magic Link -> Try to Sign-In with OAuth -> 500: Database error saving new user

It would be great if you could contact us at support (https://app.supabase.com/support/new) so we can investigate the issue with your project.
