### ISSUE TITLE
`issuer or client_id must not be supplied` when users are signing in with Google or Apple.

### ISSUE THREAD

**Issue by DanMossa** [supabase/gotrue#932]
# Bug report

## Describe the bug
I'm using Flutter and Dart and I have existing code that lets users create an account or sign in using their Apple Id. Now when a user tries to create an account or log in, the error message returned is `issuer or client_id must not be supplied`

## To Reproduce

This is the reproducible code

```dart

  final String randomNonce = uuidV4();
  final String hashedNonce = sha256.convert(utf8.encode(randomNonce)).toString();
  const String clientId = 'com.datefirefly';

  final credential = await SignInWithApple.getAppleIDCredential(
    scopes: [
      AppleIDAuthorizationScopes.email,
    ],
    nonce: hashedNonce,
  );

    GotrueSessionResponse signInRes = await _supabase.client.auth.signIn(
      oidc: OpenIDConnectCredentials(
        idToken: idToken,
        nonce: nonce,
        provider: provider,
        clientId: clientId,
      ),
    );
```

## Expected behavior

The previous, correct, behavior is creating an account or signing into an existing account.

## Screenshots

![original](https://user-images.githubusercontent.com/10294777/216687616-a682cbce-4f97-4e9f-a07a-2daa482a1b71.jpg)

## System information

- OS: iOS sign in with Apple. Android sign in with Google
- 
## Additional context

This was working before and now it isn't with the same code.
I believe it has to do with this PR that was merged:
https://github.com/supabase/gotrue/pull/927

**Comment by hf** [comment]
Hey @DanMossa,

There is a security vulnerability with this flow and this is why you get this error message. Please remove any `client_id` or `issuer` properites from the requests and only use the `provider` property instead. Please review the last security advisory published on this repo for more details.

I believe this specific issue was resolved if you were using the Apple or Google issuers and your project was correctly setup. https://github.com/supabase/gotrue/blob/master/internal/api/token.go#L421

Please also reach out to support@supabase.com if you need direct support on a production project, as GitHub issues are not meant for rapid support but rather about issues with the project itself.
