### ISSUE TITLE
Auth Facebook error: unable to find email with Facebook provider

### ISSUE THREAD

**Issue by larrasu** [supabase/gotrue#936]
# Bug report

## Describe the bug

I'm trying to test out my Nuxt app with Facebook login but I keep getting an error on the address bar:

`?error=server_error&error_description=Error+getting+user+email+from+external+provider#_=_`

Supabase logs: `unable to find email with Facebook provider`

I got all set up: Facebook app, Facebook advanced access on `email` and `public_profile`, callback URLs, app ID, and keys. It would go through Facebook's auth page then it redirects to my localhost with the error. User won't be registered to `auth.users` as well.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Followed Facebook Auth tutorial on the docs
2. Used Supabase Nuxt module.

```vue
<script setup>
const supabase = useSupabaseAuthClient();
const socialAuth = async (provider) => {
  const { error } = await supabase.auth.signInWithOAuth({ provider: provider });
  if (error) {
    console.log(error);
  } else {
    console.log("Social Auth success.");
  }
};
</script>
<template>
  <div>
    <button @click="socialAuth('facebook')">Login with Facebook</button>
  </div>
</template>
```

## Expected behavior

Login with Facebook and get user data using `useSupabaseUser()`.

## System information

- OS: Windows
- Browser: Chrome, Edge
- Version of supabase-js: 2.1.0 (using @nuxtjs/supabase: 0.3.0)
- Version of Node.js: 16.15.1

**Comment by J0** [comment]
Hey @larrasu,

Unfortunately, it sounds like this is an issue specific to the Facebook API graph endpoint - we don't have access to permissions on the Facebook Graph API endpoint. We would suggest that you contact Facebook support, or handle errors at the application level for cases where the user has decided not to make their email available.

Going to close the issue but feel free to re-open if there are still questions

Thanks!

**Comment by Developer27149** [comment]
No, Twitter is same.
**unable to find email with Twitter provider**

**Comment by titusdecali** [comment]
This is now a year old and I am having the same issue with Twitter. Can we reopen this and get it fixed please!?!

**Comment by michaelmagan** [comment]
Same this is also affecting my project. Any work arounds?

**Comment by matthiasguentert** [comment]
Checkout the solution here https://github.com/supabase/auth/issues/1791#issuecomment-3406564184
