### ISSUE TITLE
Oauth2 popup flow

### ISSUE THREAD

**Issue by Sacramentix** [supabase/gotrue#942]
### Discussed in https://github.com/supabase/supabase/discussions/4487

<div type='discussions-op-text'>

<sup>Originally posted by **dovenokan** December 14, 2021</sup>
is there a way to make it with popup instead of redirecting?</div>

It would be nice if we can have a integrated way use Oauth2 popup flow instead of redirection as you lose the state of your app when using redirect

**Comment by J0** [comment]
Hey,

We would generally discourage from using a popup. However, if  you wish, you can call `signInWithOAuth` with the [`skipBrowserRedirect`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L1022) option set to `true` and then call `window.open`  to render a button with the given URL

**Comment by J0** [comment]
Hope this helps - going to close but feel free to re-open if there are still issues

**Comment by jonatino** [comment]
@Rhywden @J0 a use case for this is a web based game. The game has to load all its assets and start the rendering engine before the login buttons are visible. It'd suck to have to load all the assets twice just because we need to redirect to login.
