### ISSUE TITLE
signInWithOAuth discord OAuth scope

### ISSUE THREAD

**Issue by haode333** [supabase/gotrue#956]
# Bug report

## Describe the bug

The default scope for sign in with discord is ```identify+email```. I want to use identify scope only.
Using ```scope``` parameter will not remove the default ```identify+email``` but can only add other scopes to it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. use ```supabase.auth.signInWithOAuth``` with ```provider: discord```
2. See error

## Expected behavior

discord OAuth able to set scope manually

**Comment by J0** [comment]
Hey! 

Thanks for the query As @haode333 mentioned one can do something like

```

const { data, error } = await supabase.auth.signInWithOAuth({
  provider: 'discord'
  options: {
    scopes: '<my-scopes>'
  }
})
const oAuthToken = data.session.provider_token // use to access provider API
```

Feel free to check out [our reference docs](https://supabase.com/docs/reference/javascript/auth-signinwithoauth) for details. Closing for now but feel free to re-open if there are issues

Jo

**Comment by haode333** [comment]
Hi @J0 ,

The original issue is that there's a default scope ```identify+email``` and the options parameter can not replace it but only add to it.
I believe it's not fixed still.

**Comment by J0** [comment]
Hm @haode333,

Thanks for the clarification!  The fix would probably be to [remove this line](https://github.com/supabase/gotrue/blob/master/internal/api/provider/discord.go#L41) and test that the OAuth provider works.

**Comment by haode333** [comment]
Hi @J0 ,

I'm totally fine with its defaulting to ```identify+email```. I'm just unsure why changing it only adds onto default instead of replacing it.
This is what I think should be changed.
```oauthScopes = append(oauthScopes, strings.Split(scopes, ",")...)```

**Comment by J0** [comment]
Hey @haode333,

That makes sense. I may be missing something but by [Hyrum's Law](https://www.hyrumslaw.com/) I think this would also break the existing setup for users who may have assumed that the default is `identify+email`

It's likely that we'll be leaving it as is for now but we can definitely revisit this if we do a revamp of the API.

Going to close for now but let me know if there are major concerns about this.
Jo

**Comment by salahmak** [comment]
@J0 Instead of closing the issue and not doing anything about it for the excuse of "muh breaks existing setups" and not just **add some option tell if you want to use default setup (current one) or provide your own set of scopes**

This is tiring, you shouldn't assume what users want and hardcode scopes straight from your a**

I've spent hours debugging this and got embarrassed after the signin didn't work for some users who created their discord accounts using their phone numbers (their accounts didn't have an email attached so resulted in the sign in failing)

so please fix this by at least giving the users **choice**

**Comment by RayanZaki** [comment]
shame😡

**Comment by euphemism** [comment]
> Do you mind also expanding a little bit more as to why you'd like to drop the email scope

@J0 Just now coming across this issue. As to why _I_ want to drop the email scope:

It's unnecessary PII. I simply want to rely on the OAuth provider (Discord, in my case) telling me who is who--nothing more. The opaque provider id would and should be sufficient.
