### ISSUE TITLE
Clarify how to use updateUser() v2

### ISSUE THREAD

**Issue by 3v0k4** [supabase/gotrue#960]
# Improve documentation

## Link 

See description (it's about two pages).

## Describe the problem

The `Notes` for [resetPasswordForEmail()](https://supabase.com/docs/reference/javascript/next/auth-resetpasswordforemail#notes) say:

> Sends a password reset request to an email address. When the user clicks the reset link in the email they are redirected back to your application. Prompt the user for a new password and call auth.updateUser()

The documentation for [updateUser()](https://supabase.com/docs/reference/javascript/next/auth-updateuser) says:

> Updates user data, **if there is a logged in user.**

Also in the `Notes` further down the page:

> In order to use the updateUser() method, **the user needs to be signed in first.**

I was confused because I couldn't understand how the user could be logged in after they clicked on the link in the reset password email.

I had to look into the source, in particular [this line](https://github.com/supabase/supabase-js/blob/affe5b5c66c35f96380d0a73783993b72eda2e52/src/SupabaseClient.ts#L16) in the `constructor()` for the `SupabaseClient` to understand that the link automatically logs in the user **when `detectSessionInUrl` is true** (I need to make sure of this).

## Describe the improvement

I'd add:
- a sentence to `updateUser()`'s notes `In order to use the updateUser() method, the user needs to be signed in first.` explaining that the link in `resetPasswordForEmail()` auto-logs in the user
- a similar sentence to `Sends a password reset request to an email address. When the user clicks the reset link in the email they are redirected back to your application. Prompt the user for a new password and call auth.updateUser()`

**Comment by kangmingtay** [comment]
hey @3v0k4, we've included the feedback on the docs you've provided to the [updateUser](https://supabase.com/docs/reference/javascript/auth-updateuser) and [reset password](https://supabase.com/docs/reference/javascript/auth-resetpasswordforemail) methods already - please let us know if you'd like to see anything else! 

@Crenshinibon I've made a fix in the client library method for updateUser to allow passing a custom redirect url when updating the user's email (https://github.com/supabase/gotrue-js/pull/610) - will update the docs when that is merged!

**Comment by gabrielsestrem** [comment]
Do you guys know if `supabase.auth.updateUser({ password: newPassword })` it's working properly on server side? I'm getting `Auth session missing!` error even when if I do **getUser** ou **refreshSession**. It's weird because in supabase-js v1 this chage-password thing was working normal. And it broke after upgrading the library.

I used to use: updateuserById. But this method it's obsolete now.

`await supabaseAuth.auth.api.updateUserById(
        loggedUser.id,
        {password: password}
      )`

**Comment by gabrielsestrem** [comment]
Nevermind... I found the methond under the **admin**:

`supabase.auth.admin.updateUserById(user.id, {password: password})`

**Comment by davegonzalez** [comment]
I ended up calling setSession right before the `updateUser` call to get this to work:
```js
await supabase.auth.setSession({
  access_token: session.get("access_token") as string,
  refresh_token: session.get("refresh_token") as string,
});

const {
  data: { user },
  error,
} = await supabase.auth.updateUser({
  password: new_password as string,
});

// no longer throws AuthSessionMissingError
```
