### ISSUE TITLE
auth bug: token expired in client, but UI does not reflect this, allows user to make changes

### ISSUE THREAD

**Issue by fergusmeiklejohn** [supabase/gotrue#963]
# Bug report

If we create a bucket then delete it we cannot create a new bucket with that name: error is "Invalid Signature" 

## To Reproduce

Create a bucket, delete it, try to create a bucket with the same name as the deleted bucket

## Expected behavior
We should be able to create a bucket, delete it, then create it again

**Comment by J0** [comment]
Hey all,

This shouldn't be surfacing again with the new token-refresh algo and tab-syncing. Going to close for now but feel free to re-open if issue re-appears

cc: @hf for visibility
