### ISSUE TITLE
Supabase Service Key mode will not override RLS if a user token is applied.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/gotrue#965]
# Bug report
In looking at a user issue with SilentWorks on Discord, a strange result was happening with SvelteKit server side requests being blocked by RLS with service_key used to init the Supabase client (in this case on server).   

Seems setting a user token overrides the service_key mode of createClient.

If true this could cause strange results with left over, or applied tokens to the supabase object.
This is probably the way things are supposed to work, but not sure that is well understood.

## To Reproduce

I don't use server side code, so the mock up test I did is simple JS.  So not a normal service_role mode, BUT I believe the results will still apply to server side code based on the network requests to PostgREST.

First Run with service key and no user signin.  Table returns value.
Sign in user.  
Run with service key and table returns [].
Turn off Signin.
Still returns [].
Clear local storage.
Table returns value.

Difference in network requests without and with user token:

Service Key and no signed in user.  Note bearer token matches service key (short)
![image](https://user-images.githubusercontent.com/54564956/161457145-ee4c3575-e743-402e-8946-9cbc47eaf452.png)

Service Key and signed in user.  Note longer bearer token.
![image](https://user-images.githubusercontent.com/54564956/161457257-f8a92076-cdfb-4a23-8c4d-8a9bcf7db38f.png)

## Expected behavior

I acknowledge my test is not real world as browser should not run with service role, but I believe on a server with a left over user token from session or set on purpose the same result would occur based on the network request.

At a minimum it should be made clear service_key role applied to supabase client object only works with no user token applied. 

Code to reproduce:
```
var supabase = supabase.createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)
async function app () {
/*
    const {user} = await supabase.auth.signIn({
        email:'gabbott@sommapp.com',
        password:'testpass'
    })
    */
    const { data, error} = await supabase
        .from('test')
        .select('*')
        .eq('id',55)
    console.log(data,error)
}
app()
```

This could be known, but 3 of us on Discord assumed service_role would always override.   
Once again, I note that on the server side maybe the issue can not occur, but I suspect if the supabase object gets a user token, it overrides the service role key.

**Comment by nathancahill** [comment]
If you run in to this, use a bogus cookie name for the service role client so it won't grab on to the user session:

```js
cookieOptions: {
    name: 'no-cookie-for-you'
}
```

**Comment by TheAnimatrix** [comment]
```
  event.locals.supabaseServer = createServerClient(PUBLIC_SUPABASE_URL, SUPABASE_KEY, {
    cookies: {
      get: () => '',
      set: (_, __, ____) => undefined,
      remove: (_, __) => undefined,
    },
  });
```

this is what i do

**Comment by ThatGuySam** [comment]
A temporary solution I use is it to sign out right after it's likely to get a session or right before I need to bypass RLS. 
```ts
await supabase.auth.signOut()
```

Not ideal, but it's simple workaround

**Comment by tdgao** [comment]
If anyone is encountering the issue now and using Vercel serverless functions, try to purge the cache in Vercel. It should get rid of what ever cookie that was there overriding the service key.

**Comment by ianscott313** [comment]
I also use Vercel serverless functions. I had trouble with this as well and then I realized it was because I was calling supabase.auth.signUp with _Confirm email_ disabled. 

When _Confirm email_ is disabled, supabase.auth.signUp returns a user and session. When its enabled, only the user is returned without the session.

The user session was getting cached on my backend essentially overriding the service role and making all the other service role jobs fail. I was able to resolve this by just signing out the user after signing them up.

Forewarning - This issue is compounded if you delete the user before signing them out because supabase.auth.signOut fails when a user does not exist in the auth table even though the session stays cached on server. If that happens, you'll have to somehow clear the cookies/session management your backend uses.

**Comment by ssadel** [comment]
Setting global auth header with the service key seems to bypass any user session stuff instead of signing out users before making service requests

```
const client = createClient<Database>(
    url, serviceKey, 
    { 
        auth: {
            autoRefreshToken: false,
            persistSession: false,
            detectSessionInUrl: false
        },
        global: {
            headers: {
                Authorization: `Bearer ${serviceKey}`
            }
        }
    }
);
```
