### ISSUE TITLE
"Confirm email" option in Studio does not work anymore

### ISSUE THREAD

**Issue by d-e-h-i-o** [supabase/gotrue#987]
# Bug report

## Describe the bug

I have the "Confirm email" toggle turned off in my Studio for the Email provider. Until recently, I could create users with the `await supabaseAdmin.auth.admin.createUser` function, and they could log in without confirming their email. However, since this morning logging in to such a newly created user is throwing an "Email not confirmed" error. 

## Expected behavior

Users should be able to log in without confirming their email.

## System information

- Version of supabase_flutter: ^1.0.1
- Version of Node.js: 2.10.0

Thank you for looking into this issue!

**Comment by hf** [comment]
Fixed in #929 but this is not yet deployed on all projects. Can you try on a new project (which has this version) if the issue persists? If yes, please close this issue.

A new version is going out in the next few days on all projects and this will be resolved.

**Comment by J0** [comment]
Hey @d-e-h-i-o ,

Going to close this issue as the deploy has been rolled out. Feel free to re-open if the issue persists though.

Thanks!
