### ISSUE TITLE
Arbitary paths on secondary redirect domains

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#99]
today we have two fields:

![image](https://user-images.githubusercontent.com/458736/118474862-1dc16100-b73e-11eb-8580-06cd77f6b783.png)

Site Url is a domain, and gotrue will allow redirects on any path that is on that primary domain

Additional Urls are **exact** Urls (including path, query param etc.) that do **not** have to be on the primary domain. The primary use case for these was mobile deep links that look like: `com.mydomain.sub://customscheme`, hence why they have to be exact, because they are difficult to verify securely

Now it appears that a new use case has developed for these Additional URLs: multiple environments

people may wish to use the same backend for multiple environments and therefore require arbitrary paths on a secondary domain

options here seem to be:

- figure out a way to securely parse Additional URLs - supporting reverse URLs with custom schemes
- introduce "Additional Site URLs" that are restricted to standard  `scheme://sub.domain.com`
- make use of gotrue's multi-tenancy (you can dynamically load configs in and out, but thus far we haven't dug into this capability)
- other?

**Comment by emschwartz** [comment]
Another use case for this is requiring a user to login to perform a certain action on a specific page.

For example, if you had a blog with a comment section, reading a post would not require logging in but commenting would. If the user goes to comment, you would prompt them to login. If they login with an email link, you would want it to redirect to that same blog post page instead of to the main page. Redirecting to a specific blog post would require having a dynamic segment in the path.

Also, this behavior should work on both the Site URL and the Additional Redirect URLs.

**Comment by KoltonG** [comment]
Wondering if this would resolve the use-case of preview environments such as Netlify and Vercel expose in Pull Requests? These all have a similar base domain with a dynamic sub-domain. Something like `*.vercel.app` wildcard support would be very helpful as we can't figure out the exact URL until build time.

**Comment by emschwartz** [comment]
FWIW, for the preview environment use case, you can create branch based
subdomains and add those to supabase. It's not quite as flexible as
supporting every build domain but it's pretty close.

**Comment by emschwartz** [comment]
> Another use case for this is requiring a user to login to perform a certain action on a specific page.

For anyone else trying to do this, I got around the current limitation by adding a query string `?redirect=/path/after/login` to the `redirectTo` parameter and handled the redirect in my app.

**Comment by emschwartz** [comment]
Did something about the handling of these URLs change in the past 2 weeks? It looks like query strings are now being stripped from the URLs.

**Comment by J0** [comment]
Hey, 

Think might be mostly resolved by #334 . Or, at least the use case  for something `*.vercel.app` 

Feel free to re-open if there are still pressing use cases that you'd need.

Thanks!
