### ISSUE TITLE
# instead of ? in URL for query parameters returned from an expired email link

### ISSUE THREAD

**Issue by mchappeldev** [supabase/gotrue#992]
# Bug report

## Describe the bug

Errors in the URL from an expired email link are returned like this:
`https://example.com/#error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired`

## To Reproduce

1. Send a password reset email
2. Click the link.
3. Click the link a second time.
4. Inspect the URL

## Expected behavior

Errors should be returned as query parameters:
`https://site.com/?error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired`

## Additional context

This causes URL objects returned on server-side code (Sveltekit in my case) to return without the query parameters:

With the #:
```
URL {
  href: 'http://localhost:5173/login/update-password',
  origin: 'http://localhost:5173',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:5173',
  hostname: 'localhost',
  port: '5173',
  pathname: '/login/update-password',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''}
```

With the ?:
```
URL {
  href: 'http://localhost:5173/login/update-password?error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired',
  origin: 'http://localhost:5173',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:5173',
  hostname: 'localhost',
  port: '5173',
  pathname: '/login/update-password',
  search: '?error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired',        
  searchParams: URLSearchParams {
    'error' => 'unauthorized_client',
    'error_code' => '401',
    'error_description' => 'Email link is invalid or has expired' },
  hash: ''}
```

Additionally, I am using custom URLs in my emails with redirects. Here is a sample in case that is related:
`https://{supabaseproject}.supabase.co/auth/v1/verify?token={{ .TokenHash }}&amp;type=recovery&amp;redirect_to=http://localhost:5173/login/update-password`

**Comment by hf** [comment]
Hey, we're working on adding PKCE support which will let you get the errors on the server side. We're going to be deprecating this way of returning errors.
